/**
 * iqFleetSync product page.
 * Copy matches the service at fleetsync.iqsoftcore.fi as of October 2026.
 * Nothing is promised beyond that description.
 */
const FLEETSYNC_PAGE = {
  fi: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync on raskaan kaluston huolto selaimessa. Ei asennusta. QR-tarra tunnistaa yksikön. 30 päivän kokeilu.",
    kicker: "Raskaan kaluston huolto selaimessa. Mitään ei asenneta.",
    lead: "iqFleetSync on verkkopalvelu kuorma-autoille, perävaunuille, pyöräkuormaajille, kaivinkoneille ja muulle kalustolle. Kuljettaja, huolto ja pääkäyttäjä käyttävät sitä selaimessa puhelimella tai tietokoneella. Kukaan ei asenna sovellusta.",
    langs: "Käyttöliittymä on monikielinen.",
    hosting: "Palvelun tiedot sijaitsevat EU:ssa. Tietokanta ja kirjautuminen ovat Supabasen EU-alueella. Sovellus toimii Vercelissa.",
    rolesHeading: "Roolit",
    roles: [
      "Pääkäyttäjä näkee kaiken, myös kustannukset, laskutuksen, henkilöt ja audit-lokin.",
      "Huolto käsittelee yksiköt, QR-tarrat, raportit, viat ja työmääräykset. Ei kustannuksia, laskutusta eikä henkilöitä.",
      "Kuljettaja näkee vain hänelle osoitetut yksiköt ja QR-skannauksella lisätyt yksiköt. Hän tekee vikailmoituksia sekä kilometri- ja tuntikirjauksia ja näkee vain omien vikailmoitustensa etenemisen. Kustannuksia ja hintoja ei näytetä.",
    ],
    qrHeading: "QR-tarrat",
    qr: [
      "Jokaisella yksiköllä on QR-tarra. Tarrat voi tulostaa sovelluksesta.",
      "Puhelimen oma kamera avaa yksikön. Skannaus lisää yksikön kuljettajan omiin yksiköihin.",
      "Tarra tunnistaa yksikön. Se ei kirjaa ketään sisään.",
      "Pääkäyttäjä näkee, kuka käytti mitäkin yksikköä ja milloin.",
    ],
    signInHeading: "Kirjautuminen",
    signIn: [
      "Pääkäyttäjä kutsuu henkilön sähköpostilinkillä.",
      "Sen jälkeen kirjautuminen on sormenjäljellä tai kasvoilla (passkey). Varalla on 6-numeroinen sähköpostikoodi.",
      "Jaetussa ajoneuvopuhelimessa voi olla valinnainen 4 numeron PIN. Pääkäyttäjä voi katsoa PIN-koodit.",
      "Puhelinnumero on vain valinnainen yhteystieto.",
    ],
    workHeading: "Huolto ja raportit",
    work: [
      "Kuljettajan viikko- ja jaksoraportit: kilometrit ja tunnit, perävaunun aliraportit ja kuvat.",
      "Vikailmoitukseen voi merkitä, että yksikkö ei ole liikennekelpoinen.",
      "Huolto kuittaa vian, merkitsee sen käynnissä olevaksi ja korjatuksi. Kuljettaja saa tiedon sovelluksessa.",
      "Työmääräykset.",
      "Huoltohistoria ja kustannusrivit pääkäyttäjälle.",
      "Huoltosuunnitelmat ja määräajat kilometreinä, tunteina tai päivämääränä.",
      "Myöhässä olevat ja tulevat muistutukset sähköpostilla tai sovelluksessa.",
      "Yksikön voi arkistoida. Historia säilyy.",
      "Henkilöitä voi muokata ja poistaa. Historia säilyy.",
    ],
    priceHeading: "Hinta",
    prices: [
      "Käyttäjiä on rajattomasti. Hinta määräytyy yksiköistä.",
      "Perusmaksu 10 € kuukaudessa.",
      "Yksiköt 1–15: 1,50 €. Yksiköt 16–50: 1,30 €. Yksiköt 51–100: 1,10 €. Yli 100 yksikköä: 0,90 € yksiköltä kuukaudessa.",
    ],
    vatNote: "Hinnat näytetään alv 0 %. Arvonlisävero lisätään laskulle.",
    trial: "30 päivän ilmainen kokeilu.",
    billing: "Maksu kortilla Stripen kautta. Lasku on kuukausittainen ja jälkikäteen.",
    audience: "Yritysasiakkaille. Rekisteröitymiseen tarvitaan suomalainen Y-tunnus.",
    cta: "Aloita 30 päivän kokeilu",
    login: "Kirjaudu",
    pricing: "Hinnasto",
    terms: "Käyttöehdot",
    privacy: "Tietosuojaseloste",
    home: "Etusivu",
    faqHeading: "Kysymyksiä",
    faq: [
      {
        q: "Pitääkö sovellus asentaa?",
        a: "Ei. Kuljettaja, huolto ja pääkäyttäjä käyttävät selainta puhelimella tai tietokoneella.",
      },
      {
        q: "Miten kirjaudutaan?",
        a: "Pääkäyttäjä lähettää kutsun sähköpostilinkillä. Sen jälkeen kirjautuminen on sormenjäljellä tai kasvoilla, ja varalla on 6-numeroinen sähköpostikoodi. Jaetussa ajoneuvopuhelimessa voi olla valinnainen 4 numeron PIN, jonka pääkäyttäjä näkee. Puhelinnumero on vain valinnainen yhteystieto.",
      },
      {
        q: "Mitä kuljettaja näkee?",
        a: "Vain omat ja skannaamalla lisätyt yksiköt, vikailmoitukset, kilometrit ja tunnit sekä omien vikailmoitusten etenemisen. Ei kustannuksia eikä hintoja.",
      },
      {
        q: "Mitä palvelu maksaa?",
        a: "Perusmaksu 10 € kuukaudessa ja yksikköhinnat 1,50 / 1,30 / 1,10 / 0,90 €. Käyttäjiä on rajattomasti. Hinnat alv 0 %, arvonlisävero lisätään laskulle. 30 päivän ilmainen kokeilu. Maksu kortilla Stripen kautta, lasku kuukausittain jälkikäteen.",
      },
    ],
    backApps: "Kaikki sovellukset",
  },
  en: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync is heavy-fleet maintenance in the browser. Nothing to install. A QR sticker identifies the unit. 30-day trial.",
    kicker: "Heavy-fleet maintenance in the browser. Nothing to install.",
    lead: "iqFleetSync is a web service for trucks, trailers, wheel loaders, excavators and other equipment. Drivers, maintenance and admins use it in the browser on a phone or a computer. Nobody installs an app.",
    langs: "The user interface is multilingual.",
    hosting: "The service data is hosted in the European Union. The database and sign-in run in a Supabase EU region. The application is hosted on Vercel.",
    rolesHeading: "Roles",
    roles: [
      "An admin sees everything, including costs, billing, people and the audit log.",
      "Maintenance handles units, QR stickers, reports, defects and work orders. No costs, billing or people.",
      "A driver sees only units assigned to them and units added by scanning a QR sticker. They file defect reports and km or hour readings, and they see the progress of their own defect reports only. Costs and prices are hidden.",
    ],
    qrHeading: "QR stickers",
    qr: [
      "Each unit has a QR sticker. Stickers can be printed from the app.",
      "The phone’s normal camera opens the unit. Scanning adds it to the driver’s own units.",
      "The sticker identifies the unit. It does not log anyone in.",
      "The admin sees who used which unit, and when.",
    ],
    signInHeading: "Sign-in",
    signIn: [
      "An admin invites a person with an email link.",
      "After that, sign-in is fingerprint or face (passkey). A 6-digit email code is the fallback.",
      "A shared vehicle phone can use an optional 4-digit PIN. The admin can view PINs.",
      "A phone number is only an optional contact field.",
    ],
    workHeading: "Maintenance and reports",
    work: [
      "Drivers file weekly or periodic reports with km and hour readings, trailer sub-reports and photos.",
      "A defect report can be marked not roadworthy.",
      "Maintenance acknowledges the defect, marks it in progress and marks it fixed. The driver is notified in the app.",
      "Work orders.",
      "Maintenance history with cost lines for the admin.",
      "Service plans and deadlines by kilometres, hours or date.",
      "Overdue and upcoming reminders by email or in the app.",
      "A unit can be archived. The history is kept.",
      "People can be edited or removed. The history is kept.",
    ],
    priceHeading: "Price",
    prices: [
      "Users are unlimited. The price is based on units.",
      "Base fee 10 € per month.",
      "Units 1–15: 1.50 €. Units 16–50: 1.30 €. Units 51–100: 1.10 €. Over 100 units: 0.90 € per unit per month.",
    ],
    vatNote: "Prices are shown at VAT 0%. VAT is added on the invoice.",
    trial: "30-day free trial.",
    billing: "Card payment through Stripe. The invoice is monthly, in arrears.",
    audience: "For businesses. Signup requires a Finnish business ID (Y-tunnus).",
    cta: "Start the 30-day trial",
    login: "Sign in",
    pricing: "Pricing",
    terms: "Terms",
    privacy: "Privacy notice",
    home: "Home",
    faqHeading: "Questions",
    faq: [
      { q: "Do I install an app?", a: "No. Drivers, maintenance and admins use the browser on a phone or a computer." },
      { q: "How does sign-in work?", a: "An admin sends an email invite. After that, sign-in is fingerprint or face, with a 6-digit email code as fallback. A shared vehicle phone can have an optional 4-digit PIN, which the admin can view. A phone number is only an optional contact field." },
      { q: "What does a driver see?", a: "Only their own units and units added by scanning, defect reports, km and hours, and the progress of their own defects. No costs or prices." },
      { q: "What does it cost?", a: "A base fee of 10 € per month and unit prices of 1.50 / 1.30 / 1.10 / 0.90 €. Unlimited users. Prices at VAT 0%, VAT added on the invoice. 30-day free trial. Card payment through Stripe, invoiced monthly in arrears." },
    ],
    backApps: "All apps",
  },
  sv: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync är underhåll av tung flotta i webbläsaren. Ingenting installeras. QR-dekalen identifierar enheten. 30 dagars provperiod.",
    kicker: "Underhåll av tung flotta i webbläsaren. Ingenting installeras.",
    lead: "iqFleetSync är en webbtjänst för lastbilar, släp, hjullastare, grävmaskiner och annan utrustning. Förare, underhåll och administratörer använder den i webbläsaren på telefon eller dator. Ingen installerar en app.",
    langs: "Gränssnittet är flerspråkigt.",
    hosting: "Tjänstens data lagras i EU. Databas och inloggning körs i en Supabase-region i EU. Appen körs på Vercel.",
    rolesHeading: "Roller",
    roles: [
      "En administratör ser allt, även kostnader, fakturering, personer och auditloggen.",
      "Underhåll hanterar enheter, QR-dekaler, rapporter, fel och arbetsordrar. Inga kostnader, ingen fakturering och inga personer.",
      "En förare ser bara enheter som tilldelats hen och enheter som lagts till genom att skanna en QR-dekal. Föraren gör felanmälningar och km- eller timavläsningar och ser bara hur de egna felanmälningarna går vidare. Kostnader och priser visas inte.",
    ],
    qrHeading: "QR-dekaler",
    qr: [
      "Varje enhet har en QR-dekal. Dekaler kan skrivas ut från appen.",
      "Telefonens vanliga kamera öppnar enheten. Skanning lägger till den bland förarens egna enheter.",
      "Dekalen identifierar enheten. Den loggar inte in någon.",
      "Administratören ser vem som använde vilken enhet och när.",
    ],
    signInHeading: "Inloggning",
    signIn: [
      "En administratör bjuder in en person med en länk i e-post.",
      "Därefter sker inloggning med fingeravtryck eller ansikte (passkey). En 6-siffrig e-postkod är reserven.",
      "En delad fordonstelefon kan ha en valfri PIN på 4 siffror. Administratören kan se PIN-koderna.",
      "Ett telefonnummer är bara ett valfritt kontaktfält.",
    ],
    workHeading: "Underhåll och rapporter",
    work: [
      "Förarens vecko- och periodrapporter: kilometer och timmar, underrapporter för släp och foton.",
      "En felanmälan kan markeras som inte trafiksäker.",
      "Underhåll kvitterar felet, markerar det som pågående och som åtgärdat. Föraren får besked i appen.",
      "Arbetsordrar.",
      "Underhållshistorik med kostnadsrader för administratören.",
      "Serviceplaner och deadlines i kilometer, timmar eller datum.",
      "Försenade och kommande påminnelser via e-post eller i appen.",
      "En enhet kan arkiveras. Historiken behålls.",
      "Personer kan redigeras och tas bort. Historiken behålls.",
    ],
    priceHeading: "Pris",
    prices: [
      "Obegränsat antal användare. Priset baseras på enheter.",
      "Grundavgift 10 € per månad.",
      "Enheter 1–15: 1,50 €. Enheter 16–50: 1,30 €. Enheter 51–100: 1,10 €. Över 100 enheter: 0,90 € per enhet och månad.",
    ],
    vatNote: "Priserna visas med moms 0 %. Moms läggs till på fakturan.",
    trial: "30 dagars gratis provperiod.",
    billing: "Kortbetalning via Stripe. Fakturan är månadsvis i efterskott.",
    audience: "För företag. Registrering kräver ett finskt FO-nummer (Y-tunnus).",
    cta: "Starta 30 dagars provperiod",
    login: "Logga in",
    pricing: "Priser",
    terms: "Villkor",
    privacy: "Integritetsmeddelande",
    home: "Startsida",
    faqHeading: "Frågor",
    faq: [
      { q: "Måste jag installera en app?", a: "Nej. Förare, underhåll och administratörer använder webbläsaren på telefon eller dator." },
      { q: "Hur loggar man in?", a: "En administratör skickar en inbjudan som e-postlänk. Därefter sker inloggning med fingeravtryck eller ansikte, med en 6-siffrig e-postkod som reserv. En delad fordonstelefon kan ha en valfri PIN på 4 siffror, som administratören kan se. Ett telefonnummer är bara ett valfritt kontaktfält." },
      { q: "Vad ser föraren?", a: "Bara egna enheter och enheter som lagts till genom skanning, felanmälningar, kilometer och timmar samt hur de egna felen går vidare. Inga kostnader eller priser." },
      { q: "Vad kostar tjänsten?", a: "Grundavgift 10 € per månad och enhetspriser 1,50 / 1,30 / 1,10 / 0,90 €. Obegränsat antal användare. Priser med moms 0 %, moms läggs till på fakturan. 30 dagars gratis provperiod. Kortbetalning via Stripe, faktura månadsvis i efterskott." },
    ],
    backApps: "Alla appar",
  },
  no: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync er vedlikehold av tung flåte i nettleseren. Ingenting installeres. QR-merket identifiserer enheten. 30 dagers prøve.",
    kicker: "Vedlikehold av tung flåte i nettleseren. Ingenting installeres.",
    lead: "iqFleetSync er en nettjeneste for lastebiler, tilhengere, hjullastere, gravemaskiner og annet utstyr. Sjåfører, vedlikehold og administratorer bruker den i nettleseren på telefon eller datamaskin. Ingen installerer en app.",
    langs: "Grensesnittet er flerspråklig.",
    hosting: "Tjenestens data ligger i EU. Database og innlogging kjører i en Supabase-region i EU. Appen kjører på Vercel.",
    rolesHeading: "Roller",
    roles: [
      "En administrator ser alt, også kostnader, fakturering, personer og revisjonsloggen.",
      "Vedlikehold håndterer enheter, QR-merker, rapporter, feil og arbeidsordrer. Ingen kostnader, fakturering eller personer.",
      "En sjåfør ser bare enheter som er tildelt hen, og enheter som er lagt til ved å skanne et QR-merke. Sjåføren melder feil og km- eller timeavlesninger, og ser bare fremdriften på egne feilmeldinger. Kostnader og priser vises ikke.",
    ],
    qrHeading: "QR-merker",
    qr: [
      "Hver enhet har et QR-merke. Merkene kan skrives ut fra appen.",
      "Telefonens vanlige kamera åpner enheten. Skanning legger den til blant sjåførens egne enheter.",
      "Merket identifiserer enheten. Det logger ikke inn noen.",
      "Administratoren ser hvem som brukte hvilken enhet, og når.",
    ],
    signInHeading: "Innlogging",
    signIn: [
      "En administrator inviterer en person med en lenke på e-post.",
      "Deretter er innlogging fingeravtrykk eller ansikt (passkey). En 6-sifret e-postkode er reserven.",
      "En delt kjøretøytelefon kan ha en valgfri PIN på 4 sifre. Administratoren kan se PIN-kodene.",
      "Et telefonnummer er bare et valgfritt kontaktfelt.",
    ],
    workHeading: "Vedlikehold og rapporter",
    work: [
      "Sjåførens uke- og perioderapporter: kilometer og timer, underrapporter for tilhenger og bilder.",
      "En feilmelding kan merkes som ikke kjørbar.",
      "Vedlikehold kvitterer feilen, merker den som pågående og som rettet. Sjåføren får beskjed i appen.",
      "Arbeidsordrer.",
      "Vedlikeholdshistorikk med kostnadslinjer for administratoren.",
      "Serviceplaner og frister i kilometer, timer eller dato.",
      "Forfalte og kommende påminnelser på e-post eller i appen.",
      "En enhet kan arkiveres. Historikken beholdes.",
      "Personer kan redigeres og fjernes. Historikken beholdes.",
    ],
    priceHeading: "Pris",
    prices: [
      "Ubegrenset antall brukere. Prisen følger enheter.",
      "Grunngebyr 10 € per måned.",
      "Enheter 1–15: 1,50 €. Enheter 16–50: 1,30 €. Enheter 51–100: 1,10 €. Over 100 enheter: 0,90 € per enhet per måned.",
    ],
    vatNote: "Prisene vises med mva. 0 %. Merverdiavgift legges til på fakturaen.",
    trial: "30 dagers gratis prøveperiode.",
    billing: "Kortbetaling via Stripe. Fakturaen er månedlig og etterskuddsvis.",
    audience: "For bedrifter. Registrering krever et finsk organisasjonsnummer (Y-tunnus).",
    cta: "Start 30 dagers prøve",
    login: "Logg inn",
    pricing: "Priser",
    terms: "Vilkår",
    privacy: "Personvernerklæring",
    home: "Hjem",
    faqHeading: "Spørsmål",
    faq: [
      { q: "Må jeg installere en app?", a: "Nei. Sjåfører, vedlikehold og administratorer bruker nettleseren på telefon eller datamaskin." },
      { q: "Hvordan logger man inn?", a: "En administrator sender en invitasjon som e-postlenke. Deretter er innlogging fingeravtrykk eller ansikt, med en 6-sifret e-postkode som reserve. En delt kjøretøytelefon kan ha en valgfri PIN på 4 sifre, som administratoren kan se. Et telefonnummer er bare et valgfritt kontaktfelt." },
      { q: "Hva ser sjåføren?", a: "Bare egne enheter og enheter lagt til ved skanning, feilmeldinger, kilometer og timer, og fremdriften på egne feil. Ingen kostnader eller priser." },
      { q: "Hva koster tjenesten?", a: "Grunngebyr 10 € per måned og enhetspriser 1,50 / 1,30 / 1,10 / 0,90 €. Ubegrenset antall brukere. Priser med mva. 0 %, merverdiavgift legges til på fakturaen. 30 dagers gratis prøve. Kortbetaling via Stripe, faktura månedlig etterskuddsvis." },
    ],
    backApps: "Alle apper",
  },
  da: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync er vedligehold af tung vognpark i browseren. Intet installeres. QR-mærket identificerer enheden. 30 dages prøve.",
    kicker: "Vedligehold af tung vognpark i browseren. Intet installeres.",
    lead: "iqFleetSync er en webtjeneste til lastbiler, anhængere, gummihjulslæssere, gravemaskiner og andet udstyr. Chauffører, vedligehold og administratorer bruger den i browseren på telefon eller computer. Ingen installerer en app.",
    langs: "Brugerfladen er flersproget.",
    hosting: "Tjenestens data ligger i EU. Database og login kører i en Supabase-region i EU. Appen kører på Vercel.",
    rolesHeading: "Roller",
    roles: [
      "En administrator ser alt, også omkostninger, fakturering, personer og revisionsloggen.",
      "Vedligehold håndterer enheder, QR-mærker, rapporter, fejl og arbejdsordrer. Ingen omkostninger, fakturering eller personer.",
      "En chauffør ser kun enheder, der er tildelt vedkommende, og enheder tilføjet ved at scanne et QR-mærke. Chaufføren laver fejlmeldinger og km- eller timeaflæsninger og ser kun fremdriften på egne fejlmeldinger. Omkostninger og priser vises ikke.",
    ],
    qrHeading: "QR-mærker",
    qr: [
      "Hver enhed har et QR-mærke. Mærker kan udskrives fra appen.",
      "Telefonens almindelige kamera åbner enheden. Scanning tilføjer den til chaufførens egne enheder.",
      "Mærket identificerer enheden. Det logger ikke nogen ind.",
      "Administratoren ser, hvem der brugte hvilken enhed, og hvornår.",
    ],
    signInHeading: "Login",
    signIn: [
      "En administrator inviterer en person med et link i e-mail.",
      "Derefter er login fingeraftryk eller ansigt (passkey). En 6-cifret e-mailkode er reserven.",
      "En delt køretøjstelefon kan have en valgfri PIN på 4 cifre. Administratoren kan se PIN-koderne.",
      "Et telefonnummer er kun et valgfrit kontaktfelt.",
    ],
    workHeading: "Vedligehold og rapporter",
    work: [
      "Chaufførens uge- og perioderapporter: kilometer og timer, underrapporter for anhænger og fotos.",
      "En fejlmeddelelse kan markeres som ikke køreklar.",
      "Vedligehold kvitterer fejlen, markerer den som i gang og som udbedret. Chaufføren får besked i appen.",
      "Arbejdsordrer.",
      "Vedligeholdelseshistorik med omkostningslinjer for administratoren.",
      "Serviceplaner og frister i kilometer, timer eller dato.",
      "Overskredne og kommende påmindelser via e-mail eller i appen.",
      "En enhed kan arkiveres. Historikken beholdes.",
      "Personer kan redigeres og fjernes. Historikken beholdes.",
    ],
    priceHeading: "Pris",
    prices: [
      "Ubegrænset antal brugere. Prisen følger enheder.",
      "Grundgebyr 10 € om måneden.",
      "Enheder 1–15: 1,50 €. Enheder 16–50: 1,30 €. Enheder 51–100: 1,10 €. Over 100 enheder: 0,90 € pr. enhed pr. måned.",
    ],
    vatNote: "Priserne vises med moms 0 %. Moms lægges til på fakturaen.",
    trial: "30 dages gratis prøve.",
    billing: "Kortbetaling via Stripe. Fakturaen er månedlig og bagud.",
    audience: "Til virksomheder. Registrering kræver et finsk virksomhedsnummer (Y-tunnus).",
    cta: "Start 30 dages prøve",
    login: "Log ind",
    pricing: "Priser",
    terms: "Vilkår",
    privacy: "Privatlivserklæring",
    home: "Forside",
    faqHeading: "Spørgsmål",
    faq: [
      { q: "Skal jeg installere en app?", a: "Nej. Chauffører, vedligehold og administratorer bruger browseren på telefon eller computer." },
      { q: "Hvordan logger man ind?", a: "En administrator sender en invitation som e-maillink. Derefter er login fingeraftryk eller ansigt, med en 6-cifret e-mailkode som reserve. En delt køretøjstelefon kan have en valgfri PIN på 4 cifre, som administratoren kan se. Et telefonnummer er kun et valgfrit kontaktfelt." },
      { q: "Hvad ser chaufføren?", a: "Kun egne enheder og enheder tilføjet ved scanning, fejlmeldinger, kilometer og timer samt fremdriften på egne fejl. Ingen omkostninger eller priser." },
      { q: "Hvad koster tjenesten?", a: "Grundgebyr 10 € om måneden og enhedspriser 1,50 / 1,30 / 1,10 / 0,90 €. Ubegrænset antal brugere. Priser med moms 0 %, moms lægges til på fakturaen. 30 dages gratis prøve. Kortbetaling via Stripe, faktura månedlig bagud." },
    ],
    backApps: "Alle apps",
  },
  de: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync ist Wartung schwerer Flotten im Browser. Nichts wird installiert. Der QR-Aufkleber erkennt die Einheit. 30 Tage testen.",
    kicker: "Wartung schwerer Flotten im Browser. Nichts wird installiert.",
    lead: "iqFleetSync ist ein Webdienst für Lkw, Anhänger, Radlader, Bagger und anderes Gerät. Fahrerinnen und Fahrer, die Werkstatt und die Administration nutzen ihn im Browser auf dem Telefon oder Computer. Niemand installiert eine App.",
    langs: "Die Oberfläche ist mehrsprachig.",
    hosting: "Die Daten des Dienstes liegen in der EU. Datenbank und Anmeldung laufen in einer Supabase-Region in der EU. Die Anwendung läuft auf Vercel.",
    rolesHeading: "Rollen",
    roles: [
      "Die Administration sieht alles, auch Kosten, Abrechnung, Personen und das Audit-Protokoll.",
      "Die Werkstatt bearbeitet Einheiten, QR-Aufkleber, Berichte, Mängel und Arbeitsaufträge. Keine Kosten, keine Abrechnung und keine Personen.",
      "Die fahrende Person sieht nur zugewiesene Einheiten und Einheiten, die durch Scannen eines QR-Aufklebers hinzugekommen sind. Sie meldet Mängel sowie Kilometer oder Stunden und sieht nur den Fortschritt der eigenen Mängelmeldungen. Kosten und Preise sind nicht sichtbar.",
    ],
    qrHeading: "QR-Aufkleber",
    qr: [
      "Jede Einheit hat einen QR-Aufkleber. Aufkleber lassen sich in der App drucken.",
      "Die normale Kamera des Telefons öffnet die Einheit. Das Scannen fügt sie den eigenen Einheiten der fahrenden Person hinzu.",
      "Der Aufkleber erkennt die Einheit. Er meldet niemanden an.",
      "Die Administration sieht, wer welche Einheit wann genutzt hat.",
    ],
    signInHeading: "Anmeldung",
    signIn: [
      "Die Administration lädt eine Person mit einem Link per E-Mail ein.",
      "Danach erfolgt die Anmeldung mit Fingerabdruck oder Gesicht (Passkey). Ein 6-stelliger E-Mail-Code ist die Alternative.",
      "Ein gemeinsames Fahrzeugtelefon kann eine optionale PIN mit 4 Ziffern haben. Die Administration kann die PINs einsehen.",
      "Eine Telefonnummer ist nur ein optionales Kontaktfeld.",
    ],
    workHeading: "Wartung und Berichte",
    work: [
      "Wochen- und Periodenberichte der fahrenden Person: Kilometer und Stunden, Unterberichte zum Anhänger und Fotos.",
      "Eine Mängelmeldung kann als nicht fahrbereit markiert werden.",
      "Die Werkstatt bestätigt den Mangel, markiert ihn als in Arbeit und als behoben. Die fahrende Person wird in der App benachrichtigt.",
      "Arbeitsaufträge.",
      "Wartungshistorie mit Kostenzeilen für die Administration.",
      "Wartungspläne und Fristen nach Kilometern, Stunden oder Datum.",
      "Überfällige und anstehende Erinnerungen per E-Mail oder in der App.",
      "Eine Einheit kann archiviert werden. Die Historie bleibt.",
      "Personen können bearbeitet und entfernt werden. Die Historie bleibt.",
    ],
    priceHeading: "Preis",
    prices: [
      "Unbegrenzt viele Benutzer. Der Preis richtet sich nach Einheiten.",
      "Grundgebühr 10 € im Monat.",
      "Einheiten 1–15: 1,50 €. Einheiten 16–50: 1,30 €. Einheiten 51–100: 1,10 €. Über 100 Einheiten: 0,90 € je Einheit und Monat.",
    ],
    vatNote: "Preise werden mit MwSt. 0 % angezeigt. Die Umsatzsteuer wird auf der Rechnung hinzugerechnet.",
    trial: "30 Tage kostenlos testen.",
    billing: "Kartenzahlung über Stripe. Die Rechnung ist monatlich und im Nachhinein.",
    audience: "Für Unternehmen. Die Registrierung erfordert eine finnische Geschäftskennnummer (Y-tunnus).",
    cta: "30 Tage testen",
    login: "Anmelden",
    pricing: "Preise",
    terms: "Bedingungen",
    privacy: "Datenschutzhinweis",
    home: "Startseite",
    faqHeading: "Fragen",
    faq: [
      { q: "Muss ich eine App installieren?", a: "Nein. Fahrende Personen, die Werkstatt und die Administration nutzen den Browser auf Telefon oder Computer." },
      { q: "Wie meldet man sich an?", a: "Die Administration sendet eine Einladung als E-Mail-Link. Danach erfolgt die Anmeldung mit Fingerabdruck oder Gesicht, ersatzweise mit einem 6-stelligen E-Mail-Code. Ein gemeinsames Fahrzeugtelefon kann eine optionale PIN mit 4 Ziffern haben, die die Administration einsehen kann. Eine Telefonnummer ist nur ein optionales Kontaktfeld." },
      { q: "Was sieht die fahrende Person?", a: "Nur eigene und durch Scannen hinzugefügte Einheiten, Mängelmeldungen, Kilometer und Stunden sowie den Fortschritt der eigenen Mängel. Keine Kosten und keine Preise." },
      { q: "Was kostet der Dienst?", a: "Grundgebühr 10 € im Monat und Einheitspreise 1,50 / 1,30 / 1,10 / 0,90 €. Unbegrenzt viele Benutzer. Preise mit MwSt. 0 %, Umsatzsteuer auf der Rechnung. 30 Tage kostenlos testen. Kartenzahlung über Stripe, Rechnung monatlich im Nachhinein." },
    ],
    backApps: "Alle Apps",
  },
  nl: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync is onderhoud van een zwaar wagenpark in de browser. Niets te installeren. De QR-sticker herkent de eenheid. 30 dagen proberen.",
    kicker: "Onderhoud van een zwaar wagenpark in de browser. Niets te installeren.",
    lead: "iqFleetSync is een webdienst voor vrachtwagens, aanhangers, wielladers, graafmachines en ander materieel. Bestuurders, onderhoud en beheerders gebruiken hem in de browser op een telefoon of computer. Niemand installeert een app.",
    langs: "De interface is meertalig.",
    hosting: "De gegevens van de dienst staan in de EU. Database en aanmelden draaien in een Supabase-regio in de EU. De applicatie draait op Vercel.",
    rolesHeading: "Rollen",
    roles: [
      "Een beheerder ziet alles, ook kosten, facturatie, personen en het auditlogboek.",
      "Onderhoud behandelt eenheden, QR-stickers, rapporten, gebreken en werkorders. Geen kosten, facturatie of personen.",
      "Een bestuurder ziet alleen toegewezen eenheden en eenheden die door een QR-scan zijn toegevoegd. Hij of zij meldt gebreken en km- of urenstanden en ziet alleen de voortgang van de eigen gebrekmeldingen. Kosten en prijzen zijn niet zichtbaar.",
    ],
    qrHeading: "QR-stickers",
    qr: [
      "Elke eenheid heeft een QR-sticker. Stickers kunnen vanuit de app worden afgedrukt.",
      "De gewone camera van de telefoon opent de eenheid. Scannen voegt hem toe aan de eigen eenheden van de bestuurder.",
      "De sticker herkent de eenheid. Hij meldt niemand aan.",
      "De beheerder ziet wie welke eenheid wanneer gebruikte.",
    ],
    signInHeading: "Aanmelden",
    signIn: [
      "Een beheerder nodigt een persoon uit met een link per e-mail.",
      "Daarna is aanmelden een vingerafdruk of gezicht (passkey). Een e-mailcode van 6 cijfers is de reserve.",
      "Een gedeelde voertuigtelefoon kan een optionele pincode van 4 cijfers hebben. De beheerder kan de pincodes bekijken.",
      "Een telefoonnummer is alleen een optioneel contactveld.",
    ],
    workHeading: "Onderhoud en rapporten",
    work: [
      "Week- en perioderapporten van de bestuurder: kilometers en uren, deelrapporten van de aanhanger en foto’s.",
      "Een gebrekmelding kan als niet rijwaardig worden gemarkeerd.",
      "Onderhoud bevestigt het gebrek, markeert het als bezig en als hersteld. De bestuurder krijgt bericht in de app.",
      "Werkorders.",
      "Onderhoudshistorie met kostenregels voor de beheerder.",
      "Onderhoudsplannen en termijnen in kilometers, uren of datum.",
      "Verlopen en komende herinneringen per e-mail of in de app.",
      "Een eenheid kan worden gearchiveerd. De geschiedenis blijft.",
      "Personen kunnen worden bewerkt en verwijderd. De geschiedenis blijft.",
    ],
    priceHeading: "Prijs",
    prices: [
      "Onbeperkt aantal gebruikers. De prijs volgt eenheden.",
      "Basisbedrag 10 € per maand.",
      "Eenheden 1–15: 1,50 €. Eenheden 16–50: 1,30 €. Eenheden 51–100: 1,10 €. Meer dan 100 eenheden: 0,90 € per eenheid per maand.",
    ],
    vatNote: "Prijzen worden getoond met btw 0%. Btw wordt op de factuur bijgeteld.",
    trial: "30 dagen gratis proberen.",
    billing: "Kaartbetaling via Stripe. De factuur is maandelijks en achteraf.",
    audience: "Voor bedrijven. Registratie vereist een Fins ondernemingsnummer (Y-tunnus).",
    cta: "Start 30 dagen proberen",
    login: "Aanmelden",
    pricing: "Prijzen",
    terms: "Voorwaarden",
    privacy: "Privacyverklaring",
    home: "Home",
    faqHeading: "Vragen",
    faq: [
      { q: "Moet ik een app installeren?", a: "Nee. Bestuurders, onderhoud en beheerders gebruiken de browser op een telefoon of computer." },
      { q: "Hoe meld je je aan?", a: "Een beheerder stuurt een uitnodiging als e-maillink. Daarna is aanmelden een vingerafdruk of gezicht, met een e-mailcode van 6 cijfers als reserve. Een gedeelde voertuigtelefoon kan een optionele pincode van 4 cijfers hebben, die de beheerder kan bekijken. Een telefoonnummer is alleen een optioneel contactveld." },
      { q: "Wat ziet de bestuurder?", a: "Alleen eigen eenheden en eenheden die door scannen zijn toegevoegd, gebrekmeldingen, kilometers en uren, en de voortgang van de eigen gebreken. Geen kosten of prijzen." },
      { q: "Wat kost de dienst?", a: "Basisbedrag 10 € per maand en eenheidsprijzen 1,50 / 1,30 / 1,10 / 0,90 €. Onbeperkt aantal gebruikers. Prijzen met btw 0%, btw op de factuur. 30 dagen gratis proberen. Kaartbetaling via Stripe, factuur maandelijks achteraf." },
    ],
    backApps: "Alle apps",
  },
  fr: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync est l’entretien d’un parc lourd dans le navigateur. Rien à installer. L’autocollant QR identifie l’unité. Essai de 30 jours.",
    kicker: "Entretien d’un parc lourd dans le navigateur. Rien à installer.",
    lead: "iqFleetSync est un service web pour camions, remorques, chargeuses, pelles et autre matériel. Conducteurs, entretien et administrateurs l’utilisent dans le navigateur, sur téléphone ou ordinateur. Personne n’installe d’application.",
    langs: "L’interface est multilingue.",
    hosting: "Les données du service sont hébergées dans l’Union européenne. La base et la connexion sont dans une région UE de Supabase. L’application est hébergée sur Vercel.",
    rolesHeading: "Rôles",
    roles: [
      "Un administrateur voit tout, y compris les coûts, la facturation, les personnes et le journal d’audit.",
      "L’entretien gère les unités, les autocollants QR, les rapports, les défauts et les ordres de travail. Pas de coûts, de facturation ni de personnes.",
      "Un conducteur ne voit que les unités qui lui sont assignées et celles ajoutées en scannant un QR. Il signale des défauts et des relevés de km ou d’heures, et il voit seulement l’avancement de ses propres signalements. Les coûts et les prix sont cachés.",
    ],
    qrHeading: "Autocollants QR",
    qr: [
      "Chaque unité a un autocollant QR. Les autocollants s’impriment depuis l’application.",
      "L’appareil photo habituel du téléphone ouvre l’unité. Le scan l’ajoute aux unités du conducteur.",
      "L’autocollant identifie l’unité. Il ne connecte personne.",
      "L’administrateur voit qui a utilisé quelle unité, et quand.",
    ],
    signInHeading: "Connexion",
    signIn: [
      "Un administrateur invite une personne par un lien envoyé par e-mail.",
      "Ensuite, la connexion se fait par empreinte ou visage (passkey). Un code e-mail à 6 chiffres sert de recours.",
      "Un téléphone partagé du véhicule peut avoir un code PIN facultatif de 4 chiffres. L’administrateur peut voir les PIN.",
      "Un numéro de téléphone n’est qu’un champ de contact facultatif.",
    ],
    workHeading: "Entretien et rapports",
    work: [
      "Rapports hebdomadaires ou périodiques du conducteur : kilomètres et heures, sous-rapports de remorque et photos.",
      "Un signalement de défaut peut être marqué non apte à circuler.",
      "L’entretien accuse réception, marque le défaut en cours, puis réparé. Le conducteur est prévenu dans l’application.",
      "Ordres de travail.",
      "Historique d’entretien avec lignes de coût pour l’administrateur.",
      "Plans d’entretien et échéances en kilomètres, heures ou date.",
      "Rappels en retard et à venir par e-mail ou dans l’application.",
      "Une unité peut être archivée. L’historique est conservé.",
      "Les personnes peuvent être modifiées ou retirées. L’historique est conservé.",
    ],
    priceHeading: "Prix",
    prices: [
      "Utilisateurs illimités. Le prix dépend des unités.",
      "Forfait de base 10 € par mois.",
      "Unités 1–15 : 1,50 €. Unités 16–50 : 1,30 €. Unités 51–100 : 1,10 €. Au-delà de 100 unités : 0,90 € par unité et par mois.",
    ],
    vatNote: "Les prix sont affichés TVA 0 %. La TVA est ajoutée sur la facture.",
    trial: "Essai gratuit de 30 jours.",
    billing: "Paiement par carte via Stripe. La facture est mensuelle et à terme échu.",
    audience: "Pour les entreprises. L’inscription exige un numéro d’entreprise finlandais (Y-tunnus).",
    cta: "Commencer l’essai de 30 jours",
    login: "Se connecter",
    pricing: "Tarifs",
    terms: "Conditions",
    privacy: "Notice de confidentialité",
    home: "Accueil",
    faqHeading: "Questions",
    faq: [
      { q: "Faut-il installer une application ?", a: "Non. Conducteurs, entretien et administrateurs utilisent le navigateur sur téléphone ou ordinateur." },
      { q: "Comment se connecte-t-on ?", a: "Un administrateur envoie une invitation par lien e-mail. Ensuite, la connexion se fait par empreinte ou visage, avec un code e-mail à 6 chiffres en recours. Un téléphone partagé peut avoir un PIN facultatif de 4 chiffres, que l’administrateur peut voir. Un numéro de téléphone n’est qu’un champ de contact facultatif." },
      { q: "Que voit le conducteur ?", a: "Seulement ses unités et celles ajoutées par scan, les signalements, les km et les heures, et l’avancement de ses propres défauts. Pas de coûts ni de prix." },
      { q: "Quel est le prix ?", a: "Forfait de base 10 € par mois et prix unitaires 1,50 / 1,30 / 1,10 / 0,90 €. Utilisateurs illimités. Prix TVA 0 %, TVA ajoutée sur la facture. Essai gratuit de 30 jours. Paiement par carte via Stripe, facture mensuelle à terme échu." },
    ],
    backApps: "Toutes les applications",
  },
  es: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync es el mantenimiento de flota pesada en el navegador. Nada que instalar. La pegatina QR identifica la unidad. Prueba de 30 días.",
    kicker: "Mantenimiento de flota pesada en el navegador. Nada que instalar.",
    lead: "iqFleetSync es un servicio web para camiones, remolques, palas cargadoras, excavadoras y otro equipo. Conductores, mantenimiento y administradores lo usan en el navegador, en el teléfono o el ordenador. Nadie instala una aplicación.",
    langs: "La interfaz es multilingüe.",
    hosting: "Los datos del servicio se alojan en la Unión Europea. La base de datos y el acceso están en una región de la UE de Supabase. La aplicación se aloja en Vercel.",
    rolesHeading: "Roles",
    roles: [
      "Un administrador lo ve todo, incluidos costes, facturación, personas y el registro de auditoría.",
      "Mantenimiento gestiona unidades, pegatinas QR, informes, defectos y órdenes de trabajo. Sin costes, facturación ni personas.",
      "Un conductor solo ve las unidades asignadas y las añadidas al escanear un QR. Registra defectos y lecturas de km u horas, y solo ve el avance de sus propios defectos. Los costes y los precios no se muestran.",
    ],
    qrHeading: "Pegatinas QR",
    qr: [
      "Cada unidad tiene una pegatina QR. Las pegatinas se imprimen desde la aplicación.",
      "La cámara normal del teléfono abre la unidad. El escaneo la añade a las unidades del conductor.",
      "La pegatina identifica la unidad. No inicia la sesión de nadie.",
      "El administrador ve quién usó cada unidad y cuándo.",
    ],
    signInHeading: "Acceso",
    signIn: [
      "Un administrador invita a una persona con un enlace por correo.",
      "Después, el acceso es con huella o cara (passkey). Un código de correo de 6 dígitos es el recurso.",
      "Un teléfono compartido del vehículo puede tener un PIN opcional de 4 dígitos. El administrador puede ver los PIN.",
      "Un número de teléfono es solo un dato de contacto opcional.",
    ],
    workHeading: "Mantenimiento e informes",
    work: [
      "Informes semanales o periódicos del conductor: kilómetros y horas, subinformes del remolque y fotos.",
      "Un defecto se puede marcar como no apto para circular.",
      "Mantenimiento acusa el defecto, lo marca en curso y lo marca reparado. El conductor recibe el aviso en la aplicación.",
      "Órdenes de trabajo.",
      "Historial de mantenimiento con líneas de coste para el administrador.",
      "Planes de servicio y plazos por kilómetros, horas o fecha.",
      "Avisos vencidos y próximos por correo o en la aplicación.",
      "Una unidad se puede archivar. El historial se conserva.",
      "Las personas se pueden editar o quitar. El historial se conserva.",
    ],
    priceHeading: "Precio",
    prices: [
      "Usuarios ilimitados. El precio depende de las unidades.",
      "Cuota base de 10 € al mes.",
      "Unidades 1–15: 1,50 €. Unidades 16–50: 1,30 €. Unidades 51–100: 1,10 €. Más de 100 unidades: 0,90 € por unidad y mes.",
    ],
    vatNote: "Los precios se muestran con IVA 0 %. El IVA se añade en la factura.",
    trial: "Prueba gratis de 30 días.",
    billing: "Pago con tarjeta a través de Stripe. La factura es mensual y a mes vencido.",
    audience: "Para empresas. El registro exige un número de empresa finlandés (Y-tunnus).",
    cta: "Empezar la prueba de 30 días",
    login: "Entrar",
    pricing: "Precios",
    terms: "Condiciones",
    privacy: "Aviso de privacidad",
    home: "Inicio",
    faqHeading: "Preguntas",
    faq: [
      { q: "¿Hay que instalar una aplicación?", a: "No. Conductores, mantenimiento y administradores usan el navegador en el teléfono o el ordenador." },
      { q: "¿Cómo se entra?", a: "Un administrador envía una invitación por enlace de correo. Después, el acceso es con huella o cara, con un código de correo de 6 dígitos de reserva. Un teléfono compartido puede tener un PIN opcional de 4 dígitos, que el administrador puede ver. Un número de teléfono es solo un dato de contacto opcional." },
      { q: "¿Qué ve el conductor?", a: "Solo sus unidades y las añadidas al escanear, defectos, kilómetros y horas, y el avance de sus propios defectos. Sin costes ni precios." },
      { q: "¿Cuánto cuesta?", a: "Cuota base de 10 € al mes y precios por unidad de 1,50 / 1,30 / 1,10 / 0,90 €. Usuarios ilimitados. Precios con IVA 0 %, IVA en la factura. Prueba gratis de 30 días. Pago con tarjeta a través de Stripe, factura mensual a mes vencido." },
    ],
    backApps: "Todas las aplicaciones",
  },
  pt: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync é a manutenção de frota pesada no navegador. Nada a instalar. O autocolante QR identifica a unidade. Teste de 30 dias.",
    kicker: "Manutenção de frota pesada no navegador. Nada a instalar.",
    lead: "O iqFleetSync é um serviço web para camiões, reboques, pás carregadoras, escavadoras e outro equipamento. Motoristas, manutenção e administradores usam-no no navegador, no telemóvel ou no computador. Ninguém instala uma aplicação.",
    langs: "A interface é multilingue.",
    hosting: "Os dados do serviço estão alojados na União Europeia. A base de dados e o acesso correm numa região da UE da Supabase. A aplicação está alojada na Vercel.",
    rolesHeading: "Papéis",
    roles: [
      "Um administrador vê tudo, incluindo custos, faturação, pessoas e o registo de auditoria.",
      "A manutenção trata de unidades, autocolantes QR, relatórios, defeitos e ordens de trabalho. Sem custos, faturação ou pessoas.",
      "Um motorista só vê as unidades que lhe foram atribuídas e as adicionadas ao ler um QR. Regista defeitos e leituras de km ou horas e só vê o andamento dos próprios defeitos. Custos e preços ficam ocultos.",
    ],
    qrHeading: "Autocolantes QR",
    qr: [
      "Cada unidade tem um autocolante QR. Os autocolantes imprimem-se na aplicação.",
      "A câmara normal do telemóvel abre a unidade. A leitura adiciona-a às unidades do motorista.",
      "O autocolante identifica a unidade. Não inicia a sessão de ninguém.",
      "O administrador vê quem usou cada unidade e quando.",
    ],
    signInHeading: "Acesso",
    signIn: [
      "Um administrador convida uma pessoa com uma ligação por e-mail.",
      "Depois, o acesso é por impressão digital ou rosto (passkey). Um código de e-mail de 6 dígitos é a alternativa.",
      "Um telemóvel partilhado do veículo pode ter um PIN opcional de 4 dígitos. O administrador pode ver os PIN.",
      "Um número de telefone é apenas um contacto opcional.",
    ],
    workHeading: "Manutenção e relatórios",
    work: [
      "Relatórios semanais ou periódicos do motorista: quilómetros e horas, sub-relatórios do reboque e fotografias.",
      "Um defeito pode ser marcado como não apto a circular.",
      "A manutenção confirma o defeito, marca-o em curso e marca-o reparado. O motorista é avisado na aplicação.",
      "Ordens de trabalho.",
      "Histórico de manutenção com linhas de custo para o administrador.",
      "Planos de serviço e prazos em quilómetros, horas ou data.",
      "Lembretes em atraso e a chegar por e-mail ou na aplicação.",
      "Uma unidade pode ser arquivada. O histórico fica guardado.",
      "As pessoas podem ser editadas ou removidas. O histórico fica guardado.",
    ],
    priceHeading: "Preço",
    prices: [
      "Utilizadores ilimitados. O preço depende das unidades.",
      "Taxa base de 10 € por mês.",
      "Unidades 1–15: 1,50 €. Unidades 16–50: 1,30 €. Unidades 51–100: 1,10 €. Acima de 100 unidades: 0,90 € por unidade e por mês.",
    ],
    vatNote: "Os preços são mostrados com IVA 0%. O IVA é acrescentado na fatura.",
    trial: "Teste grátis de 30 dias.",
    billing: "Pagamento com cartão através da Stripe. A fatura é mensal e a prazo.",
    audience: "Para empresas. O registo exige um número de empresa finlandês (Y-tunnus).",
    cta: "Começar o teste de 30 dias",
    login: "Entrar",
    pricing: "Preços",
    terms: "Condições",
    privacy: "Aviso de privacidade",
    home: "Início",
    faqHeading: "Perguntas",
    faq: [
      { q: "É preciso instalar uma aplicação?", a: "Não. Motoristas, manutenção e administradores usam o navegador no telemóvel ou no computador." },
      { q: "Como se entra?", a: "Um administrador envia um convite por ligação de e-mail. Depois, o acesso é por impressão digital ou rosto, com um código de e-mail de 6 dígitos em alternativa. Um telemóvel partilhado pode ter um PIN opcional de 4 dígitos, que o administrador pode ver. Um número de telefone é apenas um contacto opcional." },
      { q: "O que vê o motorista?", a: "Só as próprias unidades e as adicionadas por leitura, defeitos, quilómetros e horas, e o andamento dos próprios defeitos. Sem custos nem preços." },
      { q: "Quanto custa?", a: "Taxa base de 10 € por mês e preços por unidade de 1,50 / 1,30 / 1,10 / 0,90 €. Utilizadores ilimitados. Preços com IVA 0%, IVA na fatura. Teste grátis de 30 dias. Pagamento com cartão através da Stripe, fatura mensal a prazo." },
    ],
    backApps: "Todas as aplicações",
  },
  it: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync è la manutenzione di flotte pesanti nel browser. Niente da installare. L’adesivo QR identifica l’unità. Prova di 30 giorni.",
    kicker: "Manutenzione di flotte pesanti nel browser. Niente da installare.",
    lead: "iqFleetSync è un servizio web per camion, rimorchi, pale gommate, escavatori e altre attrezzature. Conducenti, officina e amministratori lo usano nel browser, sul telefono o sul computer. Nessuno installa un’app.",
    langs: "L’interfaccia è multilingue.",
    hosting: "I dati del servizio sono ospitati nell’Unione europea. Database e accesso sono in una regione UE di Supabase. L’applicazione è ospitata su Vercel.",
    rolesHeading: "Ruoli",
    roles: [
      "Un amministratore vede tutto, compresi costi, fatturazione, persone e il registro di audit.",
      "L’officina gestisce unità, adesivi QR, rapporti, difetti e ordini di lavoro. Niente costi, fatturazione o persone.",
      "Un conducente vede solo le unità assegnate e quelle aggiunte scansionando un QR. Segnala difetti e letture di km o ore e vede solo l’avanzamento delle proprie segnalazioni. Costi e prezzi sono nascosti.",
    ],
    qrHeading: "Adesivi QR",
    qr: [
      "Ogni unità ha un adesivo QR. Gli adesivi si stampano dall’applicazione.",
      "La fotocamera normale del telefono apre l’unità. La scansione la aggiunge alle unità del conducente.",
      "L’adesivo identifica l’unità. Non fa accedere nessuno.",
      "L’amministratore vede chi ha usato quale unità e quando.",
    ],
    signInHeading: "Accesso",
    signIn: [
      "Un amministratore invita una persona con un link via e-mail.",
      "Poi l’accesso è con impronta o volto (passkey). Un codice e-mail di 6 cifre è l’alternativa.",
      "Un telefono condiviso del veicolo può avere un PIN facoltativo di 4 cifre. L’amministratore può vedere i PIN.",
      "Un numero di telefono è solo un contatto facoltativo.",
    ],
    workHeading: "Manutenzione e rapporti",
    work: [
      "Rapporti settimanali o periodici del conducente: chilometri e ore, sotto-rapporti del rimorchio e foto.",
      "Un difetto si può segnare come non idoneo alla circolazione.",
      "L’officina conferma il difetto, lo segna in corso e lo segna riparato. Il conducente riceve l’avviso nell’app.",
      "Ordini di lavoro.",
      "Storico di manutenzione con righe di costo per l’amministratore.",
      "Piani di servizio e scadenze in chilometri, ore o data.",
      "Promemoria scaduti e in arrivo per e-mail o nell’app.",
      "Un’unità si può archiviare. Lo storico resta.",
      "Le persone si possono modificare o rimuovere. Lo storico resta.",
    ],
    priceHeading: "Prezzo",
    prices: [
      "Utenti illimitati. Il prezzo dipende dalle unità.",
      "Quota base di 10 € al mese.",
      "Unità 1–15: 1,50 €. Unità 16–50: 1,30 €. Unità 51–100: 1,10 €. Oltre 100 unità: 0,90 € per unità al mese.",
    ],
    vatNote: "I prezzi sono mostrati con IVA 0%. L’IVA si aggiunge in fattura.",
    trial: "Prova gratuita di 30 giorni.",
    billing: "Pagamento con carta tramite Stripe. La fattura è mensile e posticipata.",
    audience: "Per imprese. La registrazione richiede un codice impresa finlandese (Y-tunnus).",
    cta: "Inizia la prova di 30 giorni",
    login: "Accedi",
    pricing: "Prezzi",
    terms: "Condizioni",
    privacy: "Informativa privacy",
    home: "Home",
    faqHeading: "Domande",
    faq: [
      { q: "Devo installare un’app?", a: "No. Conducenti, officina e amministratori usano il browser sul telefono o sul computer." },
      { q: "Come si accede?", a: "Un amministratore invia un invito con un link e-mail. Poi l’accesso è con impronta o volto, con un codice e-mail di 6 cifre di riserva. Un telefono condiviso può avere un PIN facoltativo di 4 cifre, che l’amministratore può vedere. Un numero di telefono è solo un contatto facoltativo." },
      { q: "Cosa vede il conducente?", a: "Solo le proprie unità e quelle aggiunte con la scansione, i difetti, i km e le ore, e l’avanzamento dei propri difetti. Niente costi né prezzi." },
      { q: "Quanto costa?", a: "Quota base di 10 € al mese e prezzi per unità 1,50 / 1,30 / 1,10 / 0,90 €. Utenti illimitati. Prezzi con IVA 0%, IVA in fattura. Prova gratuita di 30 giorni. Pagamento con carta tramite Stripe, fattura mensile posticipata." },
    ],
    backApps: "Tutte le app",
  },
  pl: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync to utrzymanie ciężkiej floty w przeglądarce. Nic do instalacji. Naklejka QR identyfikuje jednostkę. 30 dni próbnie.",
    kicker: "Utrzymanie ciężkiej floty w przeglądarce. Nic do instalacji.",
    lead: "iqFleetSync to usługa internetowa dla ciężarówek, naczep, ładowarek, koparek i innego sprzętu. Kierowcy, serwis i administratorzy używają jej w przeglądarce, na telefonie lub komputerze. Nikt nie instaluje aplikacji.",
    langs: "Interfejs jest wielojęzyczny.",
    hosting: "Dane usługi są przechowywane w Unii Europejskiej. Baza i logowanie działają w regionie UE Supabase. Aplikacja jest hostowana na Vercel.",
    rolesHeading: "Role",
    roles: [
      "Administrator widzi wszystko, także koszty, rozliczenia, osoby i dziennik audytu.",
      "Serwis obsługuje jednostki, naklejki QR, raporty, usterki i zlecenia. Bez kosztów, rozliczeń i osób.",
      "Kierowca widzi tylko przypisane jednostki i jednostki dodane skanem QR. Zgłasza usterki oraz kilometry lub motogodziny i widzi tylko postęp własnych zgłoszeń. Koszty i ceny są ukryte.",
    ],
    qrHeading: "Naklejki QR",
    qr: [
      "Każda jednostka ma naklejkę QR. Naklejki można drukować z aplikacji.",
      "Zwykły aparat telefonu otwiera jednostkę. Skan dodaje ją do jednostek kierowcy.",
      "Naklejka identyfikuje jednostkę. Nikogo nie loguje.",
      "Administrator widzi, kto używał danej jednostki i kiedy.",
    ],
    signInHeading: "Logowanie",
    signIn: [
      "Administrator zaprasza osobę linkiem w e-mailu.",
      "Potem logowanie jest odciskiem palca lub twarzą (passkey). Kod e-mail z 6 cyfr jest zapasowy.",
      "Wspólny telefon pojazdu może mieć opcjonalny PIN z 4 cyfr. Administrator może zobaczyć PIN-y.",
      "Numer telefonu to tylko opcjonalne pole kontaktowe.",
    ],
    workHeading: "Serwis i raporty",
    work: [
      "Tygodniowe i okresowe raporty kierowcy: kilometry i motogodziny, podraporty naczepy i zdjęcia.",
      "Usterkę można oznaczyć jako niezdatną do ruchu.",
      "Serwis potwierdza usterkę, oznacza ją jako w toku i jako naprawioną. Kierowca dostaje informację w aplikacji.",
      "Zlecenia pracy.",
      "Historia serwisu z wierszami kosztów dla administratora.",
      "Plany serwisowe i terminy w kilometrach, motogodzinach lub dacie.",
      "Zaległe i nadchodzące przypomnienia e-mailem lub w aplikacji.",
      "Jednostkę można zarchiwizować. Historia zostaje.",
      "Osoby można edytować i usuwać. Historia zostaje.",
    ],
    priceHeading: "Cena",
    prices: [
      "Nieograniczona liczba użytkowników. Cena zależy od jednostek.",
      "Opłata podstawowa 10 € miesięcznie.",
      "Jednostki 1–15: 1,50 €. Jednostki 16–50: 1,30 €. Jednostki 51–100: 1,10 €. Powyżej 100 jednostek: 0,90 € za jednostkę miesięcznie.",
    ],
    vatNote: "Ceny są pokazane z VAT 0%. VAT dolicza się na fakturze.",
    trial: "30 dni bezpłatnie.",
    billing: "Płatność kartą przez Stripe. Faktura jest miesięczna i z dołu.",
    audience: "Dla firm. Rejestracja wymaga fińskiego numeru firmy (Y-tunnus).",
    cta: "Zacznij 30 dni próbnie",
    login: "Zaloguj się",
    pricing: "Cennik",
    terms: "Warunki",
    privacy: "Informacja o prywatności",
    home: "Strona główna",
    faqHeading: "Pytania",
    faq: [
      { q: "Czy trzeba zainstalować aplikację?", a: "Nie. Kierowcy, serwis i administratorzy używają przeglądarki na telefonie lub komputerze." },
      { q: "Jak się logować?", a: "Administrator wysyła zaproszenie linkiem e-mail. Potem logowanie jest odciskiem palca lub twarzą, a w razie potrzeby kodem e-mail z 6 cyfr. Wspólny telefon może mieć opcjonalny PIN z 4 cyfr, który administrator może zobaczyć. Numer telefonu to tylko opcjonalne pole kontaktowe." },
      { q: "Co widzi kierowca?", a: "Tylko własne jednostki i dodane skanem, usterki, kilometry i motogodziny oraz postęp własnych usterek. Bez kosztów i cen." },
      { q: "Ile to kosztuje?", a: "Opłata podstawowa 10 € miesięcznie i ceny jednostek 1,50 / 1,30 / 1,10 / 0,90 €. Nieograniczona liczba użytkowników. Ceny z VAT 0%, VAT na fakturze. 30 dni bezpłatnie. Płatność kartą przez Stripe, faktura miesięczna z dołu." },
    ],
    backApps: "Wszystkie aplikacje",
  },
  cs: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync je údržba těžké flotily v prohlížeči. Nic se neinstaluje. QR štítek identifikuje jednotku. 30 dní na zkoušku.",
    kicker: "Údržba těžké flotily v prohlížeči. Nic se neinstaluje.",
    lead: "iqFleetSync je webová služba pro nákladní vozy, návěsy, kolové nakladače, bagry a další techniku. Řidiči, údržba a správci ji používají v prohlížeči na telefonu nebo počítači. Nikdo neinstaluje aplikaci.",
    langs: "Rozhraní je vícejazyčné.",
    hosting: "Data služby jsou uložena v Evropské unii. Databáze a přihlášení běží v regionu EU služby Supabase. Aplikace běží na Vercelu.",
    rolesHeading: "Role",
    roles: [
      "Správce vidí vše, včetně nákladů, fakturace, osob a auditního záznamu.",
      "Údržba spravuje jednotky, QR štítky, hlášení, závady a pracovní příkazy. Bez nákladů, fakturace a osob.",
      "Řidič vidí jen přidělené jednotky a jednotky přidané naskenováním QR. Hláší závady a km nebo motohodiny a vidí jen postup vlastních hlášení. Náklady a ceny se nezobrazují.",
    ],
    qrHeading: "QR štítky",
    qr: [
      "Každá jednotka má QR štítek. Štítky se tisknou z aplikace.",
      "Běžný fotoaparát telefonu otevře jednotku. Sken ji přidá k jednotkám řidiče.",
      "Štítek identifikuje jednotku. Nikoho nepřihlásí.",
      "Správce vidí, kdo kterou jednotku použil a kdy.",
    ],
    signInHeading: "Přihlášení",
    signIn: [
      "Správce pozve osobu odkazem v e-mailu.",
      "Potom je přihlášení otiskem prstu nebo obličejem (passkey). Šestimístný e-mailový kód je záloha.",
      "Sdílený telefon vozidla může mít volitelný PIN o 4 číslicích. Správce může PIN zobrazit.",
      "Telefonní číslo je jen volitelný kontakt.",
    ],
    workHeading: "Údržba a hlášení",
    work: [
      "Týdenní a pravidelná hlášení řidiče: kilometry a motohodiny, dílčí hlášení návěsu a fotografie.",
      "Závadu lze označit jako nezpůsobilou k provozu.",
      "Údržba závadu potvrdí, označí jako rozpracovanou a jako opravenou. Řidič dostane zprávu v aplikaci.",
      "Pracovní příkazy.",
      "Historie údržby s řádky nákladů pro správce.",
      "Servisní plány a termíny v kilometrech, motohodinách nebo datu.",
      "Zpožděné a nadcházející připomínky e-mailem nebo v aplikaci.",
      "Jednotku lze archivovat. Historie zůstane.",
      "Osoby lze upravit a odebrat. Historie zůstane.",
    ],
    priceHeading: "Cena",
    prices: [
      "Neomezený počet uživatelů. Cena se odvíjí od jednotek.",
      "Základní poplatek 10 € měsíčně.",
      "Jednotky 1–15: 1,50 €. Jednotky 16–50: 1,30 €. Jednotky 51–100: 1,10 €. Nad 100 jednotek: 0,90 € za jednotku měsíčně.",
    ],
    vatNote: "Ceny se zobrazují s DPH 0 %. DPH se připočte na faktuře.",
    trial: "30 dní zdarma.",
    billing: "Platba kartou přes Stripe. Faktura je měsíční a zpětně.",
    audience: "Pro firmy. Registrace vyžaduje finské IČ (Y-tunnus).",
    cta: "Začít 30 dní zdarma",
    login: "Přihlásit se",
    pricing: "Ceník",
    terms: "Podmínky",
    privacy: "Informace o ochraně soukromí",
    home: "Domů",
    faqHeading: "Otázky",
    faq: [
      { q: "Musím instalovat aplikaci?", a: "Ne. Řidiči, údržba a správci používají prohlížeč na telefonu nebo počítači." },
      { q: "Jak se přihlásit?", a: "Správce pošle pozvánku odkazem v e-mailu. Potom je přihlášení otiskem prstu nebo obličejem, zálohou je šestimístný e-mailový kód. Sdílený telefon může mít volitelný PIN o 4 číslicích, který správce vidí. Telefonní číslo je jen volitelný kontakt." },
      { q: "Co vidí řidič?", a: "Jen vlastní jednotky a jednotky přidané skenem, závady, kilometry a motohodiny a postup vlastních závad. Bez nákladů a cen." },
      { q: "Kolik to stojí?", a: "Základní poplatek 10 € měsíčně a ceny jednotek 1,50 / 1,30 / 1,10 / 0,90 €. Neomezený počet uživatelů. Ceny s DPH 0 %, DPH na faktuře. 30 dní zdarma. Platba kartou přes Stripe, měsíční faktura zpětně." },
    ],
    backApps: "Všechny aplikace",
  },
  ja: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSyncは大型車両の整備をブラウザで行います。インストールはありません。QRシールがユニットを識別します。30日間の試用。",
    kicker: "大型車両の整備をブラウザで。インストールはありません。",
    lead: "iqFleetSyncは、トラック、トレーラー、ホイールローダー、ショベル、その他の機材向けのウェブサービスです。運転者、整備、管理者は、電話またはパソコンのブラウザで使います。誰もアプリをインストールしません。",
    langs: "画面は多言語です。",
    hosting: "サービスのデータはEU内にあります。データベースとログインはSupabaseのEUリージョンです。アプリはVercelで動きます。",
    rolesHeading: "役割",
    roles: [
      "管理者は、費用、請求、担当者、監査ログを含め、すべてを見ます。",
      "整備は、ユニット、QRシール、報告、不具合、作業指示を扱います。費用、請求、担当者は扱いません。",
      "運転者は、割り当てられたユニットと、QRを読み取って追加したユニットだけを見ます。不具合報告と、キロまたはアワーの記録を行い、自分の不具合報告の進み具合だけを見ます。費用と価格は表示しません。",
    ],
    qrHeading: "QRシール",
    qr: [
      "各ユニットにQRシールがあります。シールはアプリから印刷できます。",
      "電話の通常のカメラでユニットを開きます。読み取ると、運転者の自分のユニットに追加されます。",
      "シールはユニットを識別します。誰もログインさせません。",
      "管理者は、誰がどのユニットをいつ使ったかを見ます。",
    ],
    signInHeading: "ログイン",
    signIn: [
      "管理者がメールのリンクで人を招待します。",
      "その後のログインは指紋または顔（パスキー）です。代わりにメールの6桁コードがあります。",
      "共用の車両電話には、任意の4桁PINを付けられます。管理者はPINを見られます。",
      "電話番号は任意の連絡先項目だけです。",
    ],
    workHeading: "整備と報告",
    work: [
      "運転者の週次または定期の報告：キロとアワー、トレーラーの子報告、写真。",
      "不具合報告に、走行不可の印を付けられます。",
      "整備が不具合を確認し、作業中にし、完了にします。運転者にはアプリ内で知らせます。",
      "作業指示。",
      "管理者向けの、費用行がある整備履歴。",
      "キロ、アワー、または日付の整備計画と期限。",
      "期限超過と今後の通知を、メールまたはアプリ内で送ります。",
      "ユニットはアーカイブできます。履歴は残ります。",
      "担当者は編集と削除ができます。履歴は残ります。",
    ],
    priceHeading: "料金",
    prices: [
      "ユーザー数は無制限です。料金はユニット数によります。",
      "基本料金は月10ユーロ。",
      "1〜15台は1台1.50ユーロ。16〜50台は1.30ユーロ。51〜100台は1.10ユーロ。100台を超える分は1台月0.90ユーロ。",
    ],
    vatNote: "価格は消費税0%で表示します。消費税は請求書に加算します。",
    trial: "30日間の無料試用。",
    billing: "支払いはStripeのカードです。請求は毎月、後払いです。",
    audience: "事業者向けです。登録にはフィンランドの事業者番号（Y-tunnus）が必要です。",
    cta: "30日の試用を始める",
    login: "ログイン",
    pricing: "料金表",
    terms: "利用条件",
    privacy: "プライバシー通知",
    home: "ホーム",
    faqHeading: "質問",
    faq: [
      { q: "アプリのインストールは必要ですか？", a: "不要です。運転者、整備、管理者は、電話またはパソコンのブラウザを使います。" },
      { q: "ログインはどうしますか？", a: "管理者がメールのリンクで招待します。その後は指紋または顔で、代わりにメールの6桁コードがあります。共用の車両電話には任意の4桁PINを付けられ、管理者はそれを見られます。電話番号は任意の連絡先項目だけです。" },
      { q: "運転者には何が見えますか？", a: "自分のユニットと、読み取りで追加したユニット、不具合、キロとアワー、自分の不具合の進み具合だけです。費用と価格は見えません。" },
      { q: "料金はいくらですか？", a: "基本料金は月10ユーロ、ユニットは1.50 / 1.30 / 1.10 / 0.90ユーロです。ユーザーは無制限です。価格は消費税0%で、消費税は請求書に加算します。30日間の無料試用。支払いはStripeのカードで、毎月後払いです。" },
    ],
    backApps: "すべてのアプリ",
  },
  ko: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync는 브라우저에서 쓰는 대형 장비 정비입니다. 설치가 없습니다. QR 스티커가 장비를 식별합니다. 30일 체험.",
    kicker: "브라우저에서 쓰는 대형 장비 정비. 설치가 없습니다.",
    lead: "iqFleetSync는 트럭, 트레일러, 휠 로더, 굴착기와 다른 장비를 위한 웹 서비스입니다. 운전자, 정비, 관리자는 전화나 컴퓨터의 브라우저에서 씁니다. 아무도 앱을 설치하지 않습니다.",
    langs: "화면은 여러 언어입니다.",
    hosting: "서비스 데이터는 EU에 있습니다. 데이터베이스와 로그인은 Supabase의 EU 리전입니다. 앱은 Vercel에서 돌아갑니다.",
    rolesHeading: "역할",
    roles: [
      "관리자는 비용, 청구, 사람, 감사 기록을 포함해 모두를 봅니다.",
      "정비는 장비, QR 스티커, 보고, 고장, 작업 지시를 다룹니다. 비용, 청구, 사람은 다루지 않습니다.",
      "운전자는 배정된 장비와 QR을 읽어 추가한 장비만 봅니다. 고장 보고와 킬로미터 또는 시간 기록을 하고, 자기 고장 보고의 진행만 봅니다. 비용과 가격은 보이지 않습니다.",
    ],
    qrHeading: "QR 스티커",
    qr: [
      "장비마다 QR 스티커가 있습니다. 스티커는 앱에서 인쇄합니다.",
      "전화의 일반 카메라가 장비를 엽니다. 읽으면 운전자의 자기 장비에 추가됩니다.",
      "스티커는 장비를 식별합니다. 아무도 로그인시키지 않습니다.",
      "관리자는 누가 어떤 장비를 언제 썼는지 봅니다.",
    ],
    signInHeading: "로그인",
    signIn: [
      "관리자가 이메일 링크로 사람을 초대합니다.",
      "그다음 로그인은 지문 또는 얼굴(패스키)입니다. 이메일 6자리 코드가 대안입니다.",
      "공용 차량 전화에는 선택 4자리 PIN을 둘 수 있습니다. 관리자는 PIN을 볼 수 있습니다.",
      "전화번호는 선택 연락처 항목일 뿐입니다.",
    ],
    workHeading: "정비와 보고",
    work: [
      "운전자의 주간 또는 정기 보고: 킬로미터와 시간, 트레일러 하위 보고, 사진.",
      "고장 보고에 운행 불가를 표시할 수 있습니다.",
      "정비가 고장을 확인하고, 진행 중으로, 완료로 표시합니다. 운전자는 앱 안에서 알림을 받습니다.",
      "작업 지시.",
      "관리자용 비용 줄이 있는 정비 이력.",
      "킬로미터, 시간 또는 날짜의 정비 계획과 기한.",
      "지난 알림과 다가오는 알림을 이메일 또는 앱 안으로 보냅니다.",
      "장비는 보관할 수 있습니다. 이력은 남습니다.",
      "사람은 수정하고 제거할 수 있습니다. 이력은 남습니다.",
    ],
    priceHeading: "요금",
    prices: [
      "사용자는 무제한입니다. 요금은 장비 수에 따릅니다.",
      "기본 요금은 월 10유로.",
      "1–15대는 대당 1.50유로. 16–50대는 1.30유로. 51–100대는 1.10유로. 100대를 넘으면 대당 월 0.90유로.",
    ],
    vatNote: "가격은 부가세 0%로 표시합니다. 부가가치세는 청구서에 더합니다.",
    trial: "30일 무료 체험.",
    billing: "결제는 Stripe 카드입니다. 청구는 매월 후불입니다.",
    audience: "사업자용입니다. 등록에는 핀란드 사업자번호(Y-tunnus)가 필요합니다.",
    cta: "30일 체험 시작",
    login: "로그인",
    pricing: "요금표",
    terms: "이용 조건",
    privacy: "개인정보 안내",
    home: "홈",
    faqHeading: "질문",
    faq: [
      { q: "앱을 설치해야 하나요?", a: "아닙니다. 운전자, 정비, 관리자는 전화나 컴퓨터의 브라우저를 씁니다." },
      { q: "로그인은 어떻게 하나요?", a: "관리자가 이메일 링크로 초대합니다. 그다음은 지문 또는 얼굴이고, 대안은 이메일 6자리 코드입니다. 공용 차량 전화에는 선택 4자리 PIN을 둘 수 있고, 관리자가 볼 수 있습니다. 전화번호는 선택 연락처 항목일 뿐입니다." },
      { q: "운전자는 무엇을 보나요?", a: "자기 장비와 읽어서 추가한 장비, 고장, 킬로미터와 시간, 자기 고장의 진행만 봅니다. 비용과 가격은 없습니다." },
      { q: "요금은 얼마인가요?", a: "기본 요금 월 10유로와 장비 요금 1.50 / 1.30 / 1.10 / 0.90유로입니다. 사용자는 무제한입니다. 가격은 부가세 0%이고 부가가치세는 청구서에 더합니다. 30일 무료 체험. Stripe 카드 결제, 매월 후불 청구." },
    ],
    backApps: "모든 앱",
  },
  zh: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync 是在浏览器里做的重型车队维护。无需安装。二维码贴识别设备。30 天试用。",
    kicker: "在浏览器里做重型车队维护。无需安装。",
    lead: "iqFleetSync 是面向卡车、挂车、轮式装载机、挖掘机和其他设备的网页服务。驾驶员、维修和管理员在手机或电脑的浏览器里使用。没有人安装应用。",
    langs: "界面是多语言的。",
    hosting: "服务数据存放在欧盟。数据库和登录位于 Supabase 的欧盟区域。应用托管在 Vercel。",
    rolesHeading: "角色",
    roles: [
      "管理员看到全部内容，包括费用、账单、人员和审计日志。",
      "维修处理设备、二维码贴、报告、缺陷和工单。没有费用、账单和人员。",
      "驾驶员只看到分配给自己的设备，以及扫描二维码后加入的设备。可以提交缺陷和公里或小时读数，并且只看到自己缺陷报告的进展。费用和价格不显示。",
    ],
    qrHeading: "二维码贴",
    qr: [
      "每台设备有一张二维码贴。贴纸可以在应用里打印。",
      "手机自带相机打开设备。扫描会把它加入驾驶员自己的设备。",
      "贴纸识别设备。它不会让任何人登录。",
      "管理员可以看到谁在何时使用了哪台设备。",
    ],
    signInHeading: "登录",
    signIn: [
      "管理员用电子邮件链接邀请人员。",
      "之后用指纹或人脸登录（通行密钥）。备用方式是电子邮件里的 6 位数字。",
      "共用的车辆电话可以使用可选的 4 位 PIN。管理员可以查看 PIN。",
      "电话号码只是可选的联系方式。",
    ],
    workHeading: "维护和报告",
    work: [
      "驾驶员的每周或定期报告：公里和小时、挂车子报告和照片。",
      "缺陷报告可以标为不能上路。",
      "维修确认缺陷，标为进行中，再标为已修复。驾驶员在应用内收到通知。",
      "工单。",
      "带费用行的维护历史，供管理员查看。",
      "按公里、小时或日期的保养计划和期限。",
      "逾期和即将到来的提醒通过电子邮件或应用内发送。",
      "设备可以归档。历史会保留。",
      "人员可以编辑或移除。历史会保留。",
    ],
    priceHeading: "价格",
    prices: [
      "用户数量不限。价格按设备数量计算。",
      "基础费每月 10 欧元。",
      "1–15 台：每台 1.50 欧元。16–50 台：1.30 欧元。51–100 台：1.10 欧元。超过 100 台：每台每月 0.90 欧元。",
    ],
    vatNote: "价格按增值税 0% 显示。增值税加在账单上。",
    trial: "30 天免费试用。",
    billing: "通过 Stripe 用卡支付。账单按月开具，事后结算。",
    audience: "面向企业。注册需要芬兰营业编号（Y-tunnus）。",
    cta: "开始 30 天试用",
    login: "登录",
    pricing: "价格",
    terms: "条款",
    privacy: "隐私说明",
    home: "首页",
    faqHeading: "问题",
    faq: [
      { q: "需要安装应用吗？", a: "不需要。驾驶员、维修和管理员在手机或电脑的浏览器里使用。" },
      { q: "如何登录？", a: "管理员通过电子邮件链接发出邀请。之后用指纹或人脸登录，备用是电子邮件里的 6 位数字。共用的车辆电话可以有可选的 4 位 PIN，管理员可以查看。电话号码只是可选的联系方式。" },
      { q: "驾驶员能看到什么？", a: "只看到自己的设备和扫描加入的设备、缺陷、公里和小时，以及自己缺陷的进展。没有费用和价格。" },
      { q: "费用是多少？", a: "基础费每月 10 欧元，设备单价为 1.50 / 1.30 / 1.10 / 0.90 欧元。用户不限。价格为增值税 0%，增值税加在账单上。30 天免费试用。通过 Stripe 用卡支付，按月事后结算。" },
    ],
    backApps: "全部应用",
  },
};

function escapeFleetHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderFleetSyncPage(lang) {
  const root = document.getElementById("fleetsync-root");
  if (!root) return;
  const page = FLEETSYNC_PAGE[lang] || FLEETSYNC_PAGE.en;

  const titleEl = document.querySelector("title");
  if (titleEl) titleEl.textContent = page.metaTitle;
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc) metaDesc.setAttribute("content", page.metaDescription);

  const list = (items) => `<ul>${items.map((item) => `<li>${escapeFleetHtml(item)}</li>`).join("")}</ul>`;
  const faq = (page.faq || [])
    .map((item) => `<h3>${escapeFleetHtml(item.q)}</h3><p>${escapeFleetHtml(item.a)}</p>`)
    .join("");

  root.innerHTML = `<h1>iqFleetSync</h1>
    <p class="app-short">${escapeFleetHtml(page.kicker)}</p>
    <p>${escapeFleetHtml(page.lead)}</p>
    <p>${escapeFleetHtml(page.langs)}</p>
    <p>${escapeFleetHtml(page.hosting)}</p>
    <p><a href="https://fleetsync.iqsoftcore.fi">fleetsync.iqsoftcore.fi</a></p>
    <h2>${escapeFleetHtml(page.rolesHeading)}</h2>
    ${list(page.roles)}
    <h2>${escapeFleetHtml(page.qrHeading)}</h2>
    ${list(page.qr)}
    <h2>${escapeFleetHtml(page.signInHeading)}</h2>
    ${list(page.signIn)}
    <h2>${escapeFleetHtml(page.workHeading)}</h2>
    ${list(page.work)}
    <h2>${escapeFleetHtml(page.priceHeading)}</h2>
    ${list(page.prices)}
    <p>${escapeFleetHtml(page.vatNote)}</p>
    <p>${escapeFleetHtml(page.trial)}</p>
    <p>${escapeFleetHtml(page.billing)}</p>
    <p>${escapeFleetHtml(page.audience)}</p>
    <div class="app-actions">
      <a class="btn btn-primary" href="https://fleetsync.iqsoftcore.fi/rekisteroidy">${escapeFleetHtml(page.cta)}</a>
      <a class="btn btn-ghost" href="https://fleetsync.iqsoftcore.fi/login">${escapeFleetHtml(page.login)}</a>
    </div>
    <h2>${escapeFleetHtml(page.faqHeading)}</h2>
    ${faq}
    <p class="policy-nav">
      <a class="btn btn-ghost" href="hinnasto.html">${escapeFleetHtml(page.pricing)}</a>
      <a class="btn btn-ghost" href="kayttoehdot.html">${escapeFleetHtml(page.terms)}</a>
      <a class="btn btn-ghost" href="privacy-iqfleetsync.html">${escapeFleetHtml(page.privacy)}</a>
      <a class="btn btn-ghost" href="apps.html">${escapeFleetHtml(page.backApps)}</a>
      <a class="btn btn-ghost" href="index.html">${escapeFleetHtml(page.home)}</a>
    </p>`;
}
