/**
 * iqFleetSync product page.
 * Copy follows the current service at fleetsync.iqsoftcore.fi.
 * The marketing site keeps every site language. The service UI languages
 * are listed in `langs` and are a shorter set.
 */
const FLEETSYNC_PAGE = {
  fi: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync on raskaan kaluston huollon verkkosovellus. QR-tarra tunnistaa yksikön. 30 päivän ilmainen kokeilu, ilman korttia.",
    kicker: "Usean yrityksen verkkosovellus raskaan kaluston huoltoon.",
    lead: "iqFleetSync on huoltokirja kuorma-autoille, perävaunuille, pyöräkuormaajille, kaivinkoneille ja muulle raskaalle kalustolle. Yritys rekisteröityy itse. Oletuskieli on suomi.",
    langs: "Palvelun käyttöliittymän kielet: suomi, ruotsi, norja, tanska, saksa, englanti, espanja, italia ja ranska.",
    signInHeading: "Kirjautuminen",
    signIn: [
      "Ei salasanaa. Kirjautuminen pysyy samassa selainvälilehdessä.",
      "Sähköpostiin tuleva 6-numeroinen koodi kirjoitetaan samaan välilehteen.",
      "Ylläpitäjän kutsulinkki.",
      "Sormenjälki tai kasvojentunnistus (passkey).",
      "Jaettu ajoneuvopuhelin: valitse nimesi ja halutessasi 4–6 numeron PIN. Istunto kestää 30 minuuttia. Ylläpitäjä voi luoda PIN-koodin Henkilöt-sivulla. Kuljettaja voi vaihtaa sen omakseen kuljettajasivulla.",
      "Puhelinnumero on vain valinnainen yhteystieto.",
    ],
    driverHeading: "Kuljettaja",
    driver: [
      "Tavallinen mobiilisivu. Sovellusta ei asenneta.",
      "Koneen QR-tarra tunnistaa yksikön. Lyhytosoite on r.iqsoftcore.fi. Tarra ei kirjaa ketään sisään.",
      "Arkistoidun yksikön tarra näyttää tekstin Yksikkö poistettu.",
      "Omat yksiköt (nimetyt ja luetut), muu kalusto, viat, kilometrit ja käyttötunnit sekä kytketyn perävaunun lukemat.",
      "Selaimen ilmoitukset. Kuljettajan istunto kestää 90 päivää.",
      "Tunnit ja hinnat eivät näy kuljettajalle.",
    ],
    adminHeading: "Yritys",
    admin: [
      "Henkilöt: kutsu, muokkaus ja poisto. Viimeistä ylläpitäjää ei voi poistaa. Kutsun voi lähettää uudelleen tai perua.",
      "Kalusto: lisäys, tuonti, vienti (Excel tai CSV), muokkaus ja arkistointi. Historia ja laskut säilyvät. Arkistoitua yksikköä ei laskuteta.",
      "Määräajat, työmääräykset ja korjaamot. Korjaamolle voi antaa määräaikaisen linkin.",
      "Kustannukset näkyvät vain kustannusoikeudella.",
      "Kuljettajan ilmoitukset tulevat reaaliajassa, ja ilmoituksen voi kuitata.",
      "Vian tila: vastaanotettu, aloitettu tai tehty. Lisäksi kirjataan liikennekelpoisuus.",
      "Ilmoitukset sähköpostilla tai sovelluksessa. Audit-loki. Tietojen vienti ja anonymisointi.",
      "Asetukset: ilmoitusviikonpäivä, väli, lähetysaika, kieli ja huoltopohjat. Sisäänrakennettu ohjekeskus.",
    ],
    audience: "Yritysasiakkaille. Rekisteröitymiseen tarvitaan suomalainen Y-tunnus.",
    vatNote: "Hinnat alv 0 %. Arvonlisävero lisätään laskulle voimassa olevan verokannan mukaan.",
    trial: "30 päivän ilmainen kokeilu. Maksukorttia ei tarvita.",
    billing: "Laskutus on kuukausilasku tilisiirtona, kalenterikuukauden suurimman yksikkömäärän mukaan. Perusmaksu on 10 € kuukaudessa. Ajoneuvo ja työkone ovat yksi yksikkö, perävaunu on puoli yksikköä ja laite on 0 €. Käyttäjiä ei laskuteta. Arkistoitua yksikköä ei laskuteta. Jos kokeilu päättyy eikä maksua ole tehty, tai jos lasku on maksamatta 7 päivää eräpäivän jälkeen, tili on vain luku -tilassa. Palvelun voi irtisanoa milloin tahansa. Portaat ovat hinnastossa.",
    cta: "Kokeile ilmaiseksi 30 päivää",
    login: "Kirjaudu",
    pricing: "Hinnasto",
    terms: "Käyttöehdot",
    privacy: "Tietosuoja",
    home: "Etusivu",
    faqHeading: "Kysymyksiä",
    faq: [
      {
        q: "Kirjaako QR-tarra kuljettajan sisään?",
        a: "Ei. Tarra avaa yksikön ja kertoo, mikä kone on kyseessä. Lyhytosoite on r.iqsoftcore.fi. Arkistoidun yksikön tarra näyttää tekstin Yksikkö poistettu.",
      },
      {
        q: "Miten palveluun kirjaudutaan?",
        a: "Ilman salasanaa, samassa välilehdessä: 6-numeroinen sähköpostikoodi, ylläpitäjän kutsulinkki tai sormenjälki tai kasvojentunnistus (passkey). Jaetulla ajoneuvopuhelimella valitaan nimi ja halutessa 4–6 numeron PIN. Se istunto kestää 30 minuuttia. Puhelinnumero on vain valinnainen yhteystieto.",
      },
      {
        q: "Mitä kuljettaja näkee?",
        a: "Omat yksiköt, muun kaluston, viat, kilometrit ja käyttötunnit, kytketyn perävaunun lukemat ja selaimen ilmoitukset. Istunto kestää 90 päivää. Tunnit ja hinnat eivät näy kuljettajalle. Kustannukset näkyvät vain kustannusoikeudella.",
      },
      {
        q: "Miten palvelu laskutetaan?",
        a: "Kuukausilaskulla tilisiirtona, kuukauden huippuyksiköiden mukaan. Perusmaksu on 10 €/kk. Ajoneuvo ja työkone ovat 1 yksikkö, perävaunu 0,5 ja laite 0 €. Käyttäjiä ei laskuteta. Arkistoitua yksikköä ei laskuteta. Kokeilu on 30 päivää, eikä korttia tarvita. Kokeilun päätyttyä ilman maksua, tai 7 päivää maksamattoman laskun eräpäivän jälkeen, tili on vain luku -tilassa. Palvelun voi irtisanoa milloin tahansa. Hinnat ovat alv 0 %, ja arvonlisävero lisätään laskulle. Portaat ovat hinnastossa.",
      },
    ],
    backApps: "Kaikki sovellukset",
  },
  en: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync is a web app for heavy-fleet maintenance. The QR sticker identifies the unit. 30-day free trial, no card needed.",
    kicker: "A multi-company web app for heavy-fleet maintenance.",
    lead: "iqFleetSync is a maintenance record for trucks, trailers, wheel loaders, excavators, and other heavy equipment. A company registers itself. The default language is Finnish.",
    langs: "The service interface is available in Finnish, Swedish, Norwegian, Danish, German, English, Spanish, Italian, and French.",
    signInHeading: "Sign-in",
    signIn: [
      "No password. Sign-in stays in the same browser tab.",
      "A 6-digit code arrives by email and is typed in that same tab.",
      "An invite link from the admin.",
      "Fingerprint or face (passkey).",
      "Shared vehicle phone: pick your name and an optional 4–6 digit PIN. The session lasts 30 minutes. An admin can generate a PIN on the People page. The driver can change it to their own on the driver page.",
      "A phone number is only an optional contact field.",
    ],
    driverHeading: "Driver",
    driver: [
      "A plain mobile website. There is nothing to install.",
      "The QR sticker on the machine identifies the unit. The short address is r.iqsoftcore.fi. The sticker does not log anyone in.",
      "An archived unit’s sticker says the unit has been removed (Yksikkö poistettu).",
      "Own units (assigned and scanned), the rest of the fleet, defects, kilometre and hour reports, and readings for a coupled trailer.",
      "Browser push notifications. A driver session lasts 90 days.",
      "Hours and prices are hidden from drivers.",
    ],
    adminHeading: "Company",
    admin: [
      "People: invite, edit, and remove. The last admin cannot be removed. An invitation can be resent or cancelled.",
      "Fleet: add, import, export (Excel or CSV), edit, and archive. History and invoices are kept. An archived unit is not billed.",
      "Deadlines, work orders, and repair shops. A workshop can be given a time-limited link.",
      "Costs are visible only with cost permission.",
      "Driver reports arrive in real time and can be acknowledged.",
      "A defect moves through received, started, and done, with a roadworthiness status.",
      "Notifications by email or in the app. An audit log. Export and anonymisation of personal data.",
      "Settings: reporting weekday, interval, send time, language, and maintenance templates. A built-in help center.",
    ],
    audience: "For business customers. Signup requires a Finnish business ID (Y-tunnus).",
    vatNote: "Prices are VAT 0%. Value added tax is added on the invoice at the rate in force.",
    trial: "30-day free trial. No card needed.",
    billing: "Billing is a monthly invoice paid by bank transfer, based on the highest unit count in the calendar month. The base fee is 10 € per month. A vehicle or a work machine is one unit, a trailer is half a unit, and an attachment is 0 €. Users are not billed. An archived unit is not billed. If the trial ends with no payment, or if an invoice is unpaid 7 days after the due date, the account is read-only. You can cancel at any time. The price tiers are on the pricing page.",
    cta: "Try free for 30 days",
    login: "Log in",
    pricing: "Pricing",
    terms: "Terms of use",
    privacy: "Privacy",
    home: "Home",
    faqHeading: "Questions",
    faq: [
      {
        q: "Does the QR sticker log the driver in?",
        a: "No. It opens the unit and shows which machine it is. The short address is r.iqsoftcore.fi. An archived unit’s sticker says the unit has been removed (Yksikkö poistettu).",
      },
      {
        q: "How do people sign in?",
        a: "Without a password, in the same tab: a 6-digit email code, an invite link from the admin, or fingerprint or face (passkey). On a shared vehicle phone, pick your name and an optional 4–6 digit PIN. That session lasts 30 minutes. A phone number is only an optional contact field.",
      },
      {
        q: "What does the driver see?",
        a: "Own units, the rest of the fleet, defects, kilometres and hours, readings for a coupled trailer, and browser notifications. The session lasts 90 days. Hours and prices are hidden from drivers. Costs are visible only with cost permission.",
      },
      {
        q: "How is the service billed?",
        a: "By a monthly invoice, paid by bank transfer, from the peak number of units. The base fee is 10 € per month. A vehicle or work machine is 1 unit, a trailer is 0.5, and an attachment is 0 €. Users are not billed. An archived unit is not billed. The trial is 30 days, and no card is required to start. After the trial with no payment, or 7 days after an unpaid invoice’s due date, the account is read-only. You can cancel at any time. Prices are VAT 0%, and VAT is added on the invoice. The tiers are on the pricing page.",
      },
    ],
    backApps: "All apps",
  },
  sv: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync är en webbapp för underhåll av tung maskin- och fordonsflotta. QR-dekalen identifierar enheten. 30 dagars gratis provperiod, inget kort behövs.",
    kicker: "Webbapp för flera företag, för underhåll av tung flotta.",
    lead: "iqFleetSync är en underhållsbok för lastbilar, släp, hjullastare, grävmaskiner och annan tung utrustning. Företaget registrerar sig själv. Standardspråket är finska.",
    langs: "Tjänstens gränssnitt finns på finska, svenska, norska, danska, tyska, engelska, spanska, italienska och franska.",
    signInHeading: "Inloggning",
    signIn: [
      "Inget lösenord. Inloggningen stannar i samma webbläsarflik.",
      "En 6-siffrig kod kommer med e-post och skrivs in i samma flik.",
      "En inbjudningslänk från administratören.",
      "Fingeravtryck eller ansikte (passkey).",
      "Delad fordonstelefon: välj ditt namn och en valfri PIN på 4–6 siffror. Sessionen varar 30 minuter. En administratör kan skapa en PIN på sidan Personer. Föraren kan byta den till sin egen på förarsidan.",
      "Ett telefonnummer är bara ett valfritt kontaktfält.",
    ],
    driverHeading: "Förare",
    driver: [
      "En vanlig mobilsida. Inget behöver installeras.",
      "QR-dekalen på maskinen identifierar enheten. Kortadressen är r.iqsoftcore.fi. Dekalen loggar inte in någon.",
      "En arkiverad enhets dekal visar att enheten har tagits bort (Yksikkö poistettu).",
      "Egna enheter (tilldelade och skannade), övriga flottan, fel, kilometer och timmar samt värden för ett kopplat släp.",
      "Push-aviseringar i webbläsaren. En förares session varar 90 dagar.",
      "Timmar och priser är dolda för förare.",
    ],
    adminHeading: "Företag",
    admin: [
      "Personer: bjud in, redigera och ta bort. Den sista administratören kan inte tas bort. En inbjudan kan skickas igen eller avbrytas.",
      "Flotta: lägg till, importera, exportera (Excel eller CSV), redigera och arkivera. Historik och fakturor behålls. En arkiverad enhet faktureras inte.",
      "Deadlines, arbetsordrar och verkstäder. En verkstad kan få en tidsbegränsad länk.",
      "Kostnader syns bara med kostnadsbehörighet.",
      "Förarens rapporter kommer i realtid och kan kvitteras.",
      "Ett fel går genom mottaget, påbörjat och klart, med status för trafiksäkerhet.",
      "Aviseringar via e-post eller i appen. En auditlogg. Export och anonymisering av personuppgifter.",
      "Inställningar: veckodag för rapport, intervall, sändningstid, språk och underhållsmallar. Inbyggd hjälpcentral.",
    ],
    audience: "För företagskunder. Registrering kräver ett finskt FO-nummer (Y-tunnus).",
    vatNote: "Priserna är moms 0 %. Mervärdesskatt läggs till på fakturan enligt den gällande skattesatsen.",
    trial: "30 dagars gratis provperiod. Inget kort behövs.",
    billing: "Faktureringen är en månadsfaktura som betalas med banköverföring, utifrån det högsta enhetsantalet under kalendermånaden. Grundavgiften är 10 € per månad. Ett fordon eller en arbetsmaskin är en enhet, ett släp är en halv enhet och ett redskap är 0 €. Användare faktureras inte. En arkiverad enhet faktureras inte. Om provperioden tar slut utan betalning, eller om en faktura är obetald 7 dagar efter förfallodagen, är kontot skrivskyddat. Tjänsten kan sägas upp när som helst. Prisstegen finns på prissidan.",
    cta: "Prova gratis i 30 dagar",
    login: "Logga in",
    pricing: "Priser",
    terms: "Användarvillkor",
    privacy: "Integritet",
    home: "Startsida",
    faqHeading: "Frågor",
    faq: [
      {
        q: "Loggar QR-dekalen in föraren?",
        a: "Nej. Den öppnar enheten och visar vilken maskin det är. Kortadressen är r.iqsoftcore.fi. En arkiverad enhets dekal visar att enheten har tagits bort (Yksikkö poistettu).",
      },
      {
        q: "Hur loggar man in?",
        a: "Utan lösenord, i samma flik: en 6-siffrig e-postkod, en inbjudningslänk från administratören eller fingeravtryck eller ansikte (passkey). På en delad fordonstelefon väljer man sitt namn och en valfri PIN på 4–6 siffror. Den sessionen varar 30 minuter. Ett telefonnummer är bara ett valfritt kontaktfält.",
      },
      {
        q: "Vad ser föraren?",
        a: "Egna enheter, övriga flottan, fel, kilometer och timmar, värden för ett kopplat släp och aviseringar i webbläsaren. Sessionen varar 90 dagar. Timmar och priser är dolda för förare. Kostnader syns bara med kostnadsbehörighet.",
      },
      {
        q: "Hur faktureras tjänsten?",
        a: "Med månadsfaktura som betalas med banköverföring, utifrån månadens högsta enhetsantal. Grundavgiften är 10 €/mån. Ett fordon eller en arbetsmaskin är 1 enhet, ett släp 0,5 och ett redskap 0 €. Användare faktureras inte. En arkiverad enhet faktureras inte. Provperioden är 30 dagar och inget kort behövs. När provperioden tar slut utan betalning, eller 7 dagar efter förfallodagen för en obetald faktura, är kontot skrivskyddat. Tjänsten kan sägas upp när som helst. Priserna är moms 0 % och moms läggs till på fakturan. Stegen finns på prissidan.",
      },
    ],
    backApps: "Alla appar",
  },
  no: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync er en nettapp for vedlikehold av tung flåte. QR-merket identifiserer enheten. 30 dagers gratis prøve, ingen kort nødvendig.",
    kicker: "Nettapp for flere bedrifter, til vedlikehold av tung flåte.",
    lead: "iqFleetSync er en vedlikeholdsbok for lastebiler, tilhengere, hjullastere, gravemaskiner og annet tungt utstyr. Bedriften registrerer seg selv. Standardspråket er finsk.",
    langs: "Tjenestens grensesnitt finnes på finsk, svensk, norsk, dansk, tysk, engelsk, spansk, italiensk og fransk.",
    signInHeading: "Innlogging",
    signIn: [
      "Ingen passord. Innloggingen blir i samme nettleserfane.",
      "En 6-sifret kode kommer på e-post og skrives inn i samme fane.",
      "En invitasjonslenke fra administratoren.",
      "Fingeravtrykk eller ansikt (passkey).",
      "Delt kjøretøytelefon: velg navnet ditt og en valgfri PIN på 4–6 sifre. Økten varer i 30 minutter. En administrator kan lage en PIN på siden Personer. Sjåføren kan bytte den til sin egen på sjåførsiden.",
      "Et telefonnummer er bare et valgfritt kontaktfelt.",
    ],
    driverHeading: "Sjåfør",
    driver: [
      "En vanlig side i mobilnettleseren. Ingenting skal installeres.",
      "QR-merket på maskinen identifiserer enheten. Kortadressen er r.iqsoftcore.fi. Merket logger ikke inn noen.",
      "Et arkivert enhets merke viser at enheten er fjernet (Yksikkö poistettu).",
      "Egne enheter (tildelte og skannede), resten av flåten, feil, kilometer og timer, og verdier for en tilkoblet tilhenger.",
      "Push-varsler i nettleseren. En sjåførøkt varer i 90 dager.",
      "Timer og priser er skjult for sjåfører.",
    ],
    adminHeading: "Bedrift",
    admin: [
      "Personer: inviter, rediger og fjern. Den siste administratoren kan ikke fjernes. En invitasjon kan sendes på nytt eller avbrytes.",
      "Flåte: legg til, importer, eksporter (Excel eller CSV), rediger og arkiver. Historikk og fakturaer beholdes. En arkivert enhet faktureres ikke.",
      "Frister, arbeidsordrer og verksteder. Et verksted kan få en tidsbegrenset lenke.",
      "Kostnader vises bare med kostnadsrettighet.",
      "Sjåførens meldinger kommer i sanntid og kan kvitteres.",
      "En feil går gjennom mottatt, startet og ferdig, med status for om enheten er kjørbar.",
      "Varsler på e-post eller i appen. En revisjonslogg. Eksport og anonymisering av personopplysninger.",
      "Innstillinger: ukedag for rapport, intervall, sendetid, språk og vedlikeholdsmaler. Innebygd hjelpesenter.",
    ],
    audience: "For bedriftskunder. Registrering krever et finsk organisasjonsnummer (Y-tunnus).",
    vatNote: "Prisene er mva. 0 %. Merverdiavgift legges til på fakturaen etter gjeldende sats.",
    trial: "30 dagers gratis prøveperiode. Ingen kort nødvendig.",
    billing: "Faktureringen er en månedsfaktura som betales med bankoverføring, ut fra det høyeste enhetsantallet i kalendermåneden. Grunnavgiften er 10 € per måned. Et kjøretøy eller en arbeidsmaskin er én enhet, en tilhenger er en halv enhet og et utstyr er 0 €. Brukere faktureres ikke. En arkivert enhet faktureres ikke. Hvis prøven slutter uten betaling, eller hvis en faktura er ubetalt 7 dager etter forfall, er kontoen skrivebeskyttet. Tjenesten kan sies opp når som helst. Prisnivåene står på prissiden.",
    cta: "Prøv gratis i 30 dager",
    login: "Logg inn",
    pricing: "Priser",
    terms: "Vilkår",
    privacy: "Personvern",
    home: "Forside",
    faqHeading: "Spørsmål",
    faq: [
      {
        q: "Logger QR-merket inn sjåføren?",
        a: "Nei. Det åpner enheten og viser hvilken maskin det er. Kortadressen er r.iqsoftcore.fi. Et arkivert enhets merke viser at enheten er fjernet (Yksikkö poistettu).",
      },
      {
        q: "Hvordan logger man inn?",
        a: "Uten passord, i samme fane: en 6-sifret e-postkode, en invitasjonslenke fra administratoren, eller fingeravtrykk eller ansikt (passkey). På en delt kjøretøytelefon velger man navnet sitt og en valgfri PIN på 4–6 sifre. Den økten varer i 30 minutter. Et telefonnummer er bare et valgfritt kontaktfelt.",
      },
      {
        q: "Hva ser sjåføren?",
        a: "Egne enheter, resten av flåten, feil, kilometer og timer, verdier for en tilkoblet tilhenger og varsler i nettleseren. Økten varer i 90 dager. Timer og priser er skjult for sjåfører. Kostnader vises bare med kostnadsrettighet.",
      },
      {
        q: "Hvordan faktureres tjenesten?",
        a: "Med månedsfaktura som betales med bankoverføring, ut fra månedens høyeste enhetsantall. Grunnavgiften er 10 €/mnd. Et kjøretøy eller en arbeidsmaskin er 1 enhet, en tilhenger 0,5 og et utstyr 0 €. Brukere faktureres ikke. En arkivert enhet faktureres ikke. Prøven er 30 dager, og ingen kort trengs. Når prøven slutter uten betaling, eller 7 dager etter forfall for en ubetalt faktura, er kontoen skrivebeskyttet. Tjenesten kan sies opp når som helst. Prisene er mva. 0 %, og merverdiavgift legges til på fakturaen. Nivåene står på prissiden.",
      },
    ],
    backApps: "Alle apper",
  },
  da: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync er en webapp til vedligehold af tung vognpark. QR-mærket identificerer enheden. 30 dages gratis prøve, intet kort nødvendigt.",
    kicker: "Webapp til flere virksomheder, til vedligehold af tung vognpark.",
    lead: "iqFleetSync er en vedligeholdelsesbog til lastbiler, anhængere, gummigeder, gravemaskiner og andet tungt udstyr. Virksomheden registrerer sig selv. Standardsproget er finsk.",
    langs: "Tjenestens grænseflade findes på finsk, svensk, norsk, dansk, tysk, engelsk, spansk, italiensk og fransk.",
    signInHeading: "Login",
    signIn: [
      "Ingen adgangskode. Login bliver i samme browserfane.",
      "En 6-cifret kode kommer på e-mail og skrives ind i samme fane.",
      "Et invitationslink fra administratoren.",
      "Fingeraftryk eller ansigt (passkey).",
      "Delt køretøjstelefon: vælg dit navn og en valgfri PIN på 4–6 cifre. Sessionen varer 30 minutter. En administrator kan oprette en PIN på siden Personer. Chaufføren kan skifte den til sin egen på chaufførsiden.",
      "Et telefonnummer er kun et valgfrit kontaktfelt.",
    ],
    driverHeading: "Chauffør",
    driver: [
      "En almindelig mobilside. Der er intet at installere.",
      "QR-mærket på maskinen identificerer enheden. Den korte adresse er r.iqsoftcore.fi. Mærket logger ikke nogen ind.",
      "Et arkiveret enheds mærke viser, at enheden er fjernet (Yksikkö poistettu).",
      "Egne enheder (tildelte og scannede), resten af vognparken, fejl, kilometer og timer samt værdier for en tilkoblet anhænger.",
      "Push-beskeder i browseren. En chaufførsession varer 90 dage.",
      "Timer og priser er skjult for chauffører.",
    ],
    adminHeading: "Virksomhed",
    admin: [
      "Personer: inviter, rediger og fjern. Den sidste administrator kan ikke fjernes. En invitation kan sendes igen eller annulleres.",
      "Vognpark: tilføj, importér, eksportér (Excel eller CSV), rediger og arkivér. Historik og fakturaer beholdes. En arkiveret enhed faktureres ikke.",
      "Frister, arbejdsordrer og værksteder. Et værksted kan få et tidsbegrænset link.",
      "Omkostninger vises kun med omkostningsrettighed.",
      "Chaufførens meldinger kommer i realtid og kan kvitteres.",
      "En fejl går gennem modtaget, startet og færdig, med status for om enheden er køreklar.",
      "Beskeder via e-mail eller i appen. En revisionslog. Eksport og anonymisering af personoplysninger.",
      "Indstillinger: ugedag for rapport, interval, sendetid, sprog og vedligeholdelsesskabeloner. Indbygget hjælpecenter.",
    ],
    audience: "Til erhvervskunder. Registrering kræver et finsk virksomhedsnummer (Y-tunnus).",
    vatNote: "Priserne er moms 0 %. Moms lægges til på fakturaen efter den gældende sats.",
    trial: "30 dages gratis prøve. Intet kort nødvendigt.",
    billing: "Faktureringen er en månedsfaktura, der betales med bankoverførsel, ud fra det højeste antal enheder i kalendermåneden. Grundgebyret er 10 € om måneden. Et køretøj eller en arbejdsmaskine er én enhed, en anhænger er en halv enhed, og udstyr er 0 €. Brugere faktureres ikke. En arkiveret enhed faktureres ikke. Hvis prøven slutter uden betaling, eller hvis en faktura er ubetalt 7 dage efter forfald, er kontoen skrivebeskyttet. Tjenesten kan opsiges når som helst. Pristrinnene står på prissiden.",
    cta: "Prøv gratis i 30 dage",
    login: "Log ind",
    pricing: "Priser",
    terms: "Vilkår",
    privacy: "Privatliv",
    home: "Forside",
    faqHeading: "Spørgsmål",
    faq: [
      {
        q: "Logger QR-mærket chaufføren ind?",
        a: "Nej. Det åbner enheden og viser, hvilken maskine det er. Den korte adresse er r.iqsoftcore.fi. Et arkiveret enheds mærke viser, at enheden er fjernet (Yksikkö poistettu).",
      },
      {
        q: "Hvordan logger man ind?",
        a: "Uden adgangskode, i samme fane: en 6-cifret e-mailkode, et invitationslink fra administratoren eller fingeraftryk eller ansigt (passkey). På en delt køretøjstelefon vælger man sit navn og en valgfri PIN på 4–6 cifre. Den session varer 30 minutter. Et telefonnummer er kun et valgfrit kontaktfelt.",
      },
      {
        q: "Hvad ser chaufføren?",
        a: "Egne enheder, resten af vognparken, fejl, kilometer og timer, værdier for en tilkoblet anhænger og beskeder i browseren. Sessionen varer 90 dage. Timer og priser er skjult for chauffører. Omkostninger vises kun med omkostningsrettighed.",
      },
      {
        q: "Hvordan faktureres tjenesten?",
        a: "Med månedsfaktura, der betales med bankoverførsel, ud fra månedens højeste antal enheder. Grundgebyret er 10 €/md. Et køretøj eller en arbejdsmaskine er 1 enhed, en anhænger 0,5 og udstyr 0 €. Brugere faktureres ikke. En arkiveret enhed faktureres ikke. Prøven er 30 dage, og intet kort er nødvendigt. Når prøven slutter uden betaling, eller 7 dage efter forfald for en ubetalt faktura, er kontoen skrivebeskyttet. Tjenesten kan opsiges når som helst. Priserne er moms 0 %, og moms lægges til på fakturaen. Trinnene står på prissiden.",
      },
    ],
    backApps: "Alle apps",
  },
  de: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync ist eine Web-App für die Wartung schwerer Flotten. Der QR-Aufkleber erkennt die Einheit. 30 Tage kostenlos, keine Karte nötig.",
    kicker: "Web-App für mehrere Unternehmen zur Wartung schwerer Flotten.",
    lead: "iqFleetSync ist ein Wartungsbuch für Lkw, Anhänger, Radlader, Bagger und andere schwere Maschinen. Das Unternehmen registriert sich selbst. Die Standardsprache ist Finnisch.",
    langs: "Die Oberfläche des Dienstes gibt es auf Finnisch, Schwedisch, Norwegisch, Dänisch, Deutsch, Englisch, Spanisch, Italienisch und Französisch.",
    signInHeading: "Anmeldung",
    signIn: [
      "Kein Passwort. Die Anmeldung bleibt im selben Browser-Tab.",
      "Ein 6-stelliger Code kommt per E-Mail und wird im selben Tab eingegeben.",
      "Ein Einladungslink von der Administration.",
      "Fingerabdruck oder Gesicht (Passkey).",
      "Gemeinsames Fahrzeugtelefon: Namen wählen und optional eine PIN mit 4–6 Ziffern. Die Sitzung dauert 30 Minuten. Eine Administration kann auf der Seite Personen eine PIN erzeugen. Die Fahrerin oder der Fahrer kann sie auf der Fahrerseite in eine eigene ändern.",
      "Eine Telefonnummer ist nur ein optionales Kontaktfeld.",
    ],
    driverHeading: "Fahrer",
    driver: [
      "Eine gewöhnliche Mobilseite. Es wird nichts installiert.",
      "Der QR-Aufkleber an der Maschine erkennt die Einheit. Die Kurzadresse ist r.iqsoftcore.fi. Der Aufkleber meldet niemanden an.",
      "Der Aufkleber einer archivierten Einheit sagt, dass die Einheit entfernt wurde (Yksikkö poistettu).",
      "Eigene Einheiten (zugewiesen und gescannt), der übrige Fuhrpark, Mängel, Kilometer und Stunden sowie Werte eines gekoppelten Anhängers.",
      "Browser-Benachrichtigungen. Eine Fahrersitzung dauert 90 Tage.",
      "Stunden und Preise sind für Fahrerinnen und Fahrer ausgeblendet.",
    ],
    adminHeading: "Unternehmen",
    admin: [
      "Personen: einladen, bearbeiten und entfernen. Die letzte Administration kann nicht entfernt werden. Eine Einladung kann erneut gesendet oder abgebrochen werden.",
      "Fuhrpark: hinzufügen, importieren, exportieren (Excel oder CSV), bearbeiten und archivieren. Historie und Rechnungen bleiben. Eine archivierte Einheit wird nicht berechnet.",
      "Fristen, Arbeitsaufträge und Werkstätten. Eine Werkstatt kann einen zeitlich begrenzten Link erhalten.",
      "Kosten sind nur mit Kostenrecht sichtbar.",
      "Meldungen der Fahrer kommen in Echtzeit und können quittiert werden.",
      "Ein Mangel durchläuft eingegangen, begonnen und erledigt, mit einem Status zur Fahrbereitschaft.",
      "Benachrichtigungen per E-Mail oder in der App. Ein Audit-Protokoll. Export und Anonymisierung personenbezogener Daten.",
      "Einstellungen: Wochentag der Meldung, Intervall, Sendezeit, Sprache und Wartungsvorlagen. Eingebautes Hilfe-Center.",
    ],
    audience: "Für Geschäftskunden. Die Registrierung erfordert eine finnische Geschäftskennnummer (Y-tunnus).",
    vatNote: "Preise sind MwSt. 0 %. Die Umsatzsteuer wird auf der Rechnung nach dem geltenden Steuersatz hinzugerechnet.",
    trial: "30 Tage kostenlos testen. Keine Karte nötig.",
    billing: "Die Abrechnung ist eine Monatsrechnung per Banküberweisung, nach der höchsten Einheitenzahl im Kalendermonat. Die Grundgebühr beträgt 10 € im Monat. Ein Fahrzeug oder eine Arbeitsmaschine ist eine Einheit, ein Anhänger eine halbe Einheit und ein Anbaugerät 0 €. Benutzer werden nicht berechnet. Eine archivierte Einheit wird nicht berechnet. Endet die Testphase ohne Zahlung, oder ist eine Rechnung 7 Tage nach dem Fälligkeitsdatum unbezahlt, ist das Konto nur lesbar. Der Dienst kann jederzeit gekündigt werden. Die Preisstufen stehen auf der Preisseite.",
    cta: "30 Tage kostenlos testen",
    login: "Anmelden",
    pricing: "Preise",
    terms: "Nutzungsbedingungen",
    privacy: "Datenschutz",
    home: "Startseite",
    faqHeading: "Fragen",
    faq: [
      {
        q: "Meldet der QR-Aufkleber die Fahrerin oder den Fahrer an?",
        a: "Nein. Er öffnet die Einheit und zeigt, welche Maschine es ist. Die Kurzadresse ist r.iqsoftcore.fi. Der Aufkleber einer archivierten Einheit sagt, dass die Einheit entfernt wurde (Yksikkö poistettu).",
      },
      {
        q: "Wie meldet man sich an?",
        a: "Ohne Passwort, im selben Tab: ein 6-stelliger E-Mail-Code, ein Einladungslink der Administration oder Fingerabdruck oder Gesicht (Passkey). Am gemeinsamen Fahrzeugtelefon wählt man den Namen und optional eine PIN mit 4–6 Ziffern. Diese Sitzung dauert 30 Minuten. Eine Telefonnummer ist nur ein optionales Kontaktfeld.",
      },
      {
        q: "Was sieht die Fahrerin oder der Fahrer?",
        a: "Eigene Einheiten, den übrigen Fuhrpark, Mängel, Kilometer und Stunden, Werte eines gekoppelten Anhängers und Browser-Benachrichtigungen. Die Sitzung dauert 90 Tage. Stunden und Preise sind ausgeblendet. Kosten sind nur mit Kostenrecht sichtbar.",
      },
      {
        q: "Wie wird der Dienst berechnet?",
        a: "Mit einer Monatsrechnung per Banküberweisung, nach der höchsten Einheitenzahl des Monats. Die Grundgebühr beträgt 10 €/Monat. Ein Fahrzeug oder eine Arbeitsmaschine ist 1 Einheit, ein Anhänger 0,5 und ein Anbaugerät 0 €. Benutzer werden nicht berechnet. Eine archivierte Einheit wird nicht berechnet. Die Testphase dauert 30 Tage, und zum Start ist keine Karte nötig. Nach der Testphase ohne Zahlung, oder 7 Tage nach Fälligkeit einer unbezahlten Rechnung, ist das Konto nur lesbar. Der Dienst kann jederzeit gekündigt werden. Die Preise sind MwSt. 0 %, die Umsatzsteuer wird auf der Rechnung hinzugerechnet. Die Stufen stehen auf der Preisseite.",
      },
    ],
    backApps: "Alle Apps",
  },
  nl: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync is een webapp voor onderhoud van een zwaar wagenpark. De QR-sticker herkent de eenheid. 30 dagen gratis, geen kaart nodig.",
    kicker: "Webapp voor meerdere bedrijven, voor onderhoud van een zwaar wagenpark.",
    lead: "iqFleetSync is een onderhoudsboek voor vrachtwagens, aanhangers, wielladers, graafmachines en andere zware machines. Het bedrijf registreert zichzelf. De standaardtaal is Fins.",
    langs: "De interface van de dienst is beschikbaar in het Fins, Zweeds, Noors, Deens, Duits, Engels, Spaans, Italiaans en Frans.",
    signInHeading: "Inloggen",
    signIn: [
      "Geen wachtwoord. Inloggen blijft in hetzelfde browsertabblad.",
      "Een code van 6 cijfers komt per e-mail en wordt in hetzelfde tabblad ingetypt.",
      "Een uitnodigingslink van de beheerder.",
      "Vingerafdruk of gezicht (passkey).",
      "Gedeelde voertuigtelefoon: kies je naam en een optionele pincode van 4–6 cijfers. De sessie duurt 30 minuten. Een beheerder kan op de pagina Personen een pincode maken. De bestuurder kan die op de bestuurderspagina in een eigen code wijzigen.",
      "Een telefoonnummer is alleen een optioneel contactveld.",
    ],
    driverHeading: "Bestuurder",
    driver: [
      "Een gewone mobiele pagina. Er is niets te installeren.",
      "De QR-sticker op de machine herkent de eenheid. Het korte adres is r.iqsoftcore.fi. De sticker logt niemand in.",
      "De sticker van een gearchiveerde eenheid zegt dat de eenheid is verwijderd (Yksikkö poistettu).",
      "Eigen eenheden (toegewezen en gescand), de rest van het wagenpark, gebreken, kilometers en uren, en waarden van een gekoppelde aanhanger.",
      "Pushmeldingen in de browser. Een bestuurderssessie duurt 90 dagen.",
      "Uren en prijzen zijn verborgen voor bestuurders.",
    ],
    adminHeading: "Bedrijf",
    admin: [
      "Personen: uitnodigen, bewerken en verwijderen. De laatste beheerder kan niet worden verwijderd. Een uitnodiging kan opnieuw worden verstuurd of worden geannuleerd.",
      "Wagenpark: toevoegen, importeren, exporteren (Excel of CSV), bewerken en archiveren. Geschiedenis en facturen blijven bewaard. Een gearchiveerde eenheid wordt niet gefactureerd.",
      "Termijnen, werkorders en werkplaatsen. Een werkplaats kan een tijdelijke link krijgen.",
      "Kosten zijn alleen zichtbaar met kostenrecht.",
      "Meldingen van de bestuurder komen realtime binnen en kunnen worden bevestigd.",
      "Een gebrek doorloopt ontvangen, gestart en klaar, met een status voor de rijwaardigheid.",
      "Meldingen per e-mail of in de app. Een auditlog. Export en anonimisering van persoonsgegevens.",
      "Instellingen: weekdag van de melding, interval, verzendtijd, taal en onderhoudssjablonen. Ingebouwd helpcentrum.",
    ],
    audience: "Voor zakelijke klanten. Registratie vereist een Fins ondernemingsnummer (Y-tunnus).",
    vatNote: "Prijzen zijn btw 0%. Btw wordt op de factuur bijgeteld volgens het geldende tarief.",
    trial: "30 dagen gratis proberen. Geen kaart nodig.",
    billing: "De facturatie is een maandfactuur via bankoverschrijving, op basis van het hoogste aantal eenheden in de kalendermaand. Het basisbedrag is 10 € per maand. Een voertuig of een werkmachine is één eenheid, een aanhanger een halve eenheid en een werktuig 0 €. Gebruikers worden niet gefactureerd. Een gearchiveerde eenheid wordt niet gefactureerd. Eindigt de proef zonder betaling, of is een factuur 7 dagen na de vervaldatum onbetaald, dan is het account alleen-lezen. De dienst kan op elk moment worden opgezegd. De prijstrappen staan op de prijspagina.",
    cta: "30 dagen gratis proberen",
    login: "Inloggen",
    pricing: "Prijzen",
    terms: "Voorwaarden",
    privacy: "Privacy",
    home: "Home",
    faqHeading: "Vragen",
    faq: [
      {
        q: "Logt de QR-sticker de bestuurder in?",
        a: "Nee. Hij opent de eenheid en laat zien welke machine het is. Het korte adres is r.iqsoftcore.fi. De sticker van een gearchiveerde eenheid zegt dat de eenheid is verwijderd (Yksikkö poistettu).",
      },
      {
        q: "Hoe log je in?",
        a: "Zonder wachtwoord, in hetzelfde tabblad: een e-mailcode van 6 cijfers, een uitnodigingslink van de beheerder, of vingerafdruk of gezicht (passkey). Op een gedeelde voertuigtelefoon kies je je naam en een optionele pincode van 4–6 cijfers. Die sessie duurt 30 minuten. Een telefoonnummer is alleen een optioneel contactveld.",
      },
      {
        q: "Wat ziet de bestuurder?",
        a: "Eigen eenheden, de rest van het wagenpark, gebreken, kilometers en uren, waarden van een gekoppelde aanhanger en browsermeldingen. De sessie duurt 90 dagen. Uren en prijzen zijn verborgen. Kosten zijn alleen zichtbaar met kostenrecht.",
      },
      {
        q: "Hoe wordt de dienst gefactureerd?",
        a: "Met een maandfactuur via bankoverschrijving, op het hoogste aantal eenheden van de maand. Het basisbedrag is 10 €/maand. Een voertuig of werkmachine is 1 eenheid, een aanhanger 0,5 en een werktuig 0 €. Gebruikers worden niet gefactureerd. Een gearchiveerde eenheid wordt niet gefactureerd. De proef duurt 30 dagen en er is geen kaart nodig. Na de proef zonder betaling, of 7 dagen na de vervaldatum van een onbetaalde factuur, is het account alleen-lezen. De dienst kan op elk moment worden opgezegd. Prijzen zijn btw 0% en btw wordt op de factuur bijgeteld. De trappen staan op de prijspagina.",
      },
    ],
    backApps: "Alle apps",
  },
  fr: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync est une application web d’entretien de parc lourd. L’autocollant QR identifie l’unité. Essai gratuit de 30 jours, sans carte.",
    kicker: "Application web multi-entreprises pour l’entretien d’un parc lourd.",
    lead: "iqFleetSync est un carnet d’entretien pour camions, remorques, chargeuses, pelles et autres engins lourds. L’entreprise s’inscrit elle-même. La langue par défaut est le finnois.",
    langs: "L’interface du service est disponible en finnois, suédois, norvégien, danois, allemand, anglais, espagnol, italien et français.",
    signInHeading: "Connexion",
    signIn: [
      "Pas de mot de passe. La connexion reste dans le même onglet du navigateur.",
      "Un code à 6 chiffres arrive par e-mail et se saisit dans ce même onglet.",
      "Un lien d’invitation de l’administrateur.",
      "Empreinte ou visage (passkey).",
      "Téléphone partagé du véhicule : choisir son nom et un code PIN facultatif de 4 à 6 chiffres. La session dure 30 minutes. Un administrateur peut créer un PIN sur la page Personnes. Le conducteur peut le remplacer par le sien sur la page conducteur.",
      "Un numéro de téléphone n’est qu’un champ de contact facultatif.",
    ],
    driverHeading: "Conducteur",
    driver: [
      "Une page mobile ordinaire. Rien à installer.",
      "L’autocollant QR sur la machine identifie l’unité. L’adresse courte est r.iqsoftcore.fi. L’autocollant ne connecte personne.",
      "L’autocollant d’une unité archivée indique que l’unité a été retirée (Yksikkö poistettu).",
      "Ses unités (attribuées et lues), le reste du parc, les défauts, les kilomètres et les heures, et les relevés d’une remorque attelée.",
      "Notifications du navigateur. Une session conducteur dure 90 jours.",
      "Les heures et les prix sont cachés aux conducteurs.",
    ],
    adminHeading: "Entreprise",
    admin: [
      "Personnes : inviter, modifier et retirer. Le dernier administrateur ne peut pas être retiré. Une invitation peut être renvoyée ou annulée.",
      "Parc : ajouter, importer, exporter (Excel ou CSV), modifier et archiver. L’historique et les factures sont conservés. Une unité archivée n’est pas facturée.",
      "Échéances, ordres de travail et ateliers. Un atelier peut recevoir un lien à durée limitée.",
      "Les coûts ne sont visibles qu’avec le droit de voir les coûts.",
      "Les signalements du conducteur arrivent en temps réel et peuvent être accusés.",
      "Un défaut passe par reçu, commencé et terminé, avec un état d’aptitude à circuler.",
      "Notifications par e-mail ou dans l’application. Un journal d’audit. Export et anonymisation des données personnelles.",
      "Réglages : jour de signalement, intervalle, heure d’envoi, langue et modèles d’entretien. Centre d’aide intégré.",
    ],
    audience: "Pour les clients professionnels. L’inscription exige un numéro d’entreprise finlandais (Y-tunnus).",
    vatNote: "Les prix sont TVA 0 %. La taxe sur la valeur ajoutée est ajoutée sur la facture au taux en vigueur.",
    trial: "Essai gratuit de 30 jours. Aucune carte demandée.",
    billing: "La facturation est une facture mensuelle payée par virement, selon le nombre d’unités le plus élevé du mois calendaire. Le forfait de base est de 10 € par mois. Un véhicule ou un engin compte pour une unité, une remorque pour une demi-unité et un équipement pour 0 €. Les utilisateurs ne sont pas facturés. Une unité archivée n’est pas facturée. Si l’essai se termine sans paiement, ou si une facture est impayée 7 jours après l’échéance, le compte passe en lecture seule. Le service peut être résilié à tout moment. Les paliers sont sur la page des tarifs.",
    cta: "Essayer gratuitement 30 jours",
    login: "Connexion",
    pricing: "Tarifs",
    terms: "Conditions",
    privacy: "Confidentialité",
    home: "Accueil",
    faqHeading: "Questions",
    faq: [
      {
        q: "L’autocollant QR connecte-t-il le conducteur ?",
        a: "Non. Il ouvre l’unité et indique de quelle machine il s’agit. L’adresse courte est r.iqsoftcore.fi. L’autocollant d’une unité archivée indique que l’unité a été retirée (Yksikkö poistettu).",
      },
      {
        q: "Comment se connecte-t-on ?",
        a: "Sans mot de passe, dans le même onglet : un code e-mail à 6 chiffres, un lien d’invitation de l’administrateur, ou empreinte ou visage (passkey). Sur un téléphone partagé, on choisit son nom et un PIN facultatif de 4 à 6 chiffres. Cette session dure 30 minutes. Un numéro de téléphone n’est qu’un champ de contact facultatif.",
      },
      {
        q: "Que voit le conducteur ?",
        a: "Ses unités, le reste du parc, les défauts, les kilomètres et les heures, les relevés d’une remorque attelée et les notifications du navigateur. La session dure 90 jours. Les heures et les prix sont cachés. Les coûts ne sont visibles qu’avec le droit de voir les coûts.",
      },
      {
        q: "Comment le service est-il facturé ?",
        a: "Par facture mensuelle payée par virement, selon le nombre d’unités le plus élevé du mois. Le forfait de base est de 10 €/mois. Un véhicule ou un engin compte pour 1 unité, une remorque pour 0,5 et un équipement pour 0 €. Les utilisateurs ne sont pas facturés. Une unité archivée n’est pas facturée. L’essai dure 30 jours et aucune carte n’est demandée. Après l’essai sans paiement, ou 7 jours après l’échéance d’une facture impayée, le compte passe en lecture seule. Le service peut être résilié à tout moment. Les prix sont TVA 0 % et la TVA est ajoutée sur la facture. Les paliers sont sur la page des tarifs.",
      },
    ],
    backApps: "Toutes les applications",
  },
  es: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync es una aplicación web de mantenimiento de flota pesada. La pegatina QR identifica la unidad. Prueba gratis de 30 días, sin tarjeta.",
    kicker: "Aplicación web para varias empresas, para el mantenimiento de flota pesada.",
    lead: "iqFleetSync es un libro de mantenimiento para camiones, remolques, palas cargadoras, excavadoras y otra maquinaria pesada. La empresa se registra sola. El idioma predeterminado es el finés.",
    langs: "La interfaz del servicio está en finés, sueco, noruego, danés, alemán, inglés, español, italiano y francés.",
    signInHeading: "Acceso",
    signIn: [
      "Sin contraseña. El acceso se queda en la misma pestaña del navegador.",
      "Un código de 6 dígitos llega por correo y se escribe en esa misma pestaña.",
      "Un enlace de invitación del administrador.",
      "Huella o cara (passkey).",
      "Teléfono compartido del vehículo: elige tu nombre y un PIN opcional de 4–6 dígitos. La sesión dura 30 minutos. Un administrador puede crear un PIN en la página Personas. El conductor puede cambiarlo por el suyo en la página del conductor.",
      "Un número de teléfono es solo un dato de contacto opcional.",
    ],
    driverHeading: "Conductor",
    driver: [
      "Una página móvil normal. No hay nada que instalar.",
      "La pegatina QR de la máquina identifica la unidad. La dirección corta es r.iqsoftcore.fi. La pegatina no inicia la sesión de nadie.",
      "La pegatina de una unidad archivada dice que la unidad se ha retirado (Yksikkö poistettu).",
      "Unidades propias (asignadas y leídas), el resto de la flota, defectos, kilómetros y horas, y lecturas de un remolque acoplado.",
      "Avisos del navegador. La sesión del conductor dura 90 días.",
      "Las horas y los precios no se muestran al conductor.",
    ],
    adminHeading: "Empresa",
    admin: [
      "Personas: invitar, editar y quitar. El último administrador no se puede quitar. Una invitación se puede reenviar o cancelar.",
      "Flota: añadir, importar, exportar (Excel o CSV), editar y archivar. El historial y las facturas se conservan. Una unidad archivada no se factura.",
      "Plazos, órdenes de trabajo y talleres. A un taller se le puede dar un enlace con caducidad.",
      "Los costes solo se ven con permiso de costes.",
      "Los avisos del conductor llegan en tiempo real y se pueden acusar.",
      "Un defecto pasa por recibido, empezado y hecho, con un estado de aptitud para circular.",
      "Avisos por correo o dentro de la aplicación. Un registro de auditoría. Exportación y anonimización de datos personales.",
      "Ajustes: día de la semana del aviso, intervalo, hora de envío, idioma y plantillas de mantenimiento. Centro de ayuda integrado.",
    ],
    audience: "Para clientes de empresa. El registro exige un número de empresa finlandés (Y-tunnus).",
    vatNote: "Los precios son IVA 0 %. El impuesto sobre el valor añadido se añade en la factura según el tipo vigente.",
    trial: "Prueba gratis de 30 días. No hace falta tarjeta.",
    billing: "La facturación es una factura mensual por transferencia, según el número más alto de unidades del mes natural. La cuota base es de 10 € al mes. Un vehículo o una máquina de trabajo es una unidad, un remolque es media unidad y un implemento es 0 €. Los usuarios no se facturan. Una unidad archivada no se factura. Si la prueba termina sin pago, o si una factura sigue impagada 7 días después del vencimiento, la cuenta queda en solo lectura. El servicio se puede cancelar en cualquier momento. Los tramos están en la página de precios.",
    cta: "Probar gratis 30 días",
    login: "Entrar",
    pricing: "Precios",
    terms: "Condiciones",
    privacy: "Privacidad",
    home: "Inicio",
    faqHeading: "Preguntas",
    faq: [
      {
        q: "¿La pegatina QR inicia la sesión del conductor?",
        a: "No. Abre la unidad e indica de qué máquina se trata. La dirección corta es r.iqsoftcore.fi. La pegatina de una unidad archivada dice que la unidad se ha retirado (Yksikkö poistettu).",
      },
      {
        q: "¿Cómo se entra?",
        a: "Sin contraseña, en la misma pestaña: un código de 6 dígitos por correo, un enlace de invitación del administrador, o huella o cara (passkey). En un teléfono compartido se elige el nombre y un PIN opcional de 4–6 dígitos. Esa sesión dura 30 minutos. Un número de teléfono es solo un dato de contacto opcional.",
      },
      {
        q: "¿Qué ve el conductor?",
        a: "Sus unidades, el resto de la flota, defectos, kilómetros y horas, lecturas de un remolque acoplado y avisos del navegador. La sesión dura 90 días. Las horas y los precios no se muestran. Los costes solo se ven con permiso de costes.",
      },
      {
        q: "¿Cómo se factura el servicio?",
        a: "Con una factura mensual por transferencia, según el pico de unidades del mes. La cuota base es de 10 €/mes. Un vehículo o una máquina es 1 unidad, un remolque 0,5 y un implemento 0 €. Los usuarios no se facturan. Una unidad archivada no se factura. La prueba dura 30 días y no hace falta tarjeta. Tras la prueba sin pago, o 7 días después del vencimiento de una factura impagada, la cuenta queda en solo lectura. El servicio se puede cancelar en cualquier momento. Los precios son IVA 0 % y el IVA se añade en la factura. Los tramos están en la página de precios.",
      },
    ],
    backApps: "Todas las aplicaciones",
  },
  pt: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "O iqFleetSync é um aplicativo web de manutenção de frota pesada. O adesivo QR identifica a unidade. Teste grátis de 30 dias, sem cartão.",
    kicker: "Aplicativo web para várias empresas, para manutenção de frota pesada.",
    lead: "O iqFleetSync é um livro de manutenção para camiões, reboques, pás carregadoras, escavadoras e outras máquinas pesadas. A empresa regista-se sozinha. O idioma predefinido é o finlandês.",
    langs: "A interface do serviço está em finlandês, sueco, norueguês, dinamarquês, alemão, inglês, espanhol, italiano e francês.",
    signInHeading: "Acesso",
    signIn: [
      "Sem palavra-passe. O acesso fica no mesmo separador do navegador.",
      "Um código de 6 dígitos chega por e-mail e é escrito nesse mesmo separador.",
      "Um link de convite do administrador.",
      "Impressão digital ou rosto (passkey).",
      "Telefone partilhado do veículo: escolha o seu nome e um PIN opcional de 4–6 dígitos. A sessão dura 30 minutos. Um administrador pode criar um PIN na página Pessoas. O motorista pode trocá-lo pelo seu na página do motorista.",
      "Um número de telefone é apenas um contacto opcional.",
    ],
    driverHeading: "Motorista",
    driver: [
      "Uma página móvel normal. Não há nada para instalar.",
      "O adesivo QR na máquina identifica a unidade. O endereço curto é r.iqsoftcore.fi. O adesivo não inicia a sessão de ninguém.",
      "O adesivo de uma unidade arquivada diz que a unidade foi retirada (Yksikkö poistettu).",
      "Unidades próprias (atribuídas e lidas), o resto da frota, defeitos, quilómetros e horas, e leituras de um reboque engatado.",
      "Notificações do navegador. A sessão do motorista dura 90 dias.",
      "Horas e preços ficam ocultos para o motorista.",
    ],
    adminHeading: "Empresa",
    admin: [
      "Pessoas: convidar, editar e remover. O último administrador não pode ser removido. Um convite pode ser reenviado ou cancelado.",
      "Frota: adicionar, importar, exportar (Excel ou CSV), editar e arquivar. O histórico e as faturas ficam guardados. Uma unidade arquivada não é faturada.",
      "Prazos, ordens de trabalho e oficinas. Uma oficina pode receber um link com prazo.",
      "Os custos só aparecem com permissão de custos.",
      "Os avisos do motorista chegam em tempo real e podem ser confirmados.",
      "Um defeito passa por recebido, iniciado e concluído, com um estado de aptidão para circular.",
      "Avisos por e-mail ou na aplicação. Um registo de auditoria. Exportação e anonimização de dados pessoais.",
      "Definições: dia da semana do aviso, intervalo, hora de envio, idioma e modelos de manutenção. Centro de ajuda integrado.",
    ],
    audience: "Para clientes empresariais. O registo exige um número de empresa finlandês (Y-tunnus).",
    vatNote: "Os preços são IVA 0%. O imposto sobre o valor acrescentado é acrescentado na fatura à taxa em vigor.",
    trial: "Teste grátis de 30 dias. Não é preciso cartão.",
    billing: "A faturação é uma fatura mensal paga por transferência, pelo maior número de unidades do mês. A taxa base é de 10 € por mês. Um veículo ou uma máquina de trabalho é uma unidade, um reboque é meia unidade e um equipamento é 0 €. Os utilizadores não são faturados. Uma unidade arquivada não é faturada. Se o teste terminar sem pagamento, ou se uma fatura continuar por pagar 7 dias após o vencimento, a conta fica só de leitura. O serviço pode ser cancelado a qualquer momento. Os escalões estão na página de preços.",
    cta: "Experimentar grátis 30 dias",
    login: "Entrar",
    pricing: "Preços",
    terms: "Condições",
    privacy: "Privacidade",
    home: "Início",
    faqHeading: "Perguntas",
    faq: [
      {
        q: "O adesivo QR inicia a sessão do motorista?",
        a: "Não. Abre a unidade e mostra qual é a máquina. O endereço curto é r.iqsoftcore.fi. O adesivo de uma unidade arquivada diz que a unidade foi retirada (Yksikkö poistettu).",
      },
      {
        q: "Como se entra?",
        a: "Sem palavra-passe, no mesmo separador: um código de 6 dígitos por e-mail, um link de convite do administrador, ou impressão digital ou rosto (passkey). Num telefone partilhado escolhe-se o nome e um PIN opcional de 4–6 dígitos. Essa sessão dura 30 minutos. Um número de telefone é apenas um contacto opcional.",
      },
      {
        q: "O que vê o motorista?",
        a: "As suas unidades, o resto da frota, defeitos, quilómetros e horas, leituras de um reboque engatado e notificações do navegador. A sessão dura 90 dias. Horas e preços ficam ocultos. Os custos só aparecem com permissão de custos.",
      },
      {
        q: "Como é faturado o serviço?",
        a: "Com uma fatura mensal paga por transferência, pelo pico de unidades do mês. A taxa base é de 10 €/mês. Um veículo ou uma máquina é 1 unidade, um reboque 0,5 e um equipamento 0 €. Os utilizadores não são faturados. Uma unidade arquivada não é faturada. O teste dura 30 dias e não é preciso cartão. Depois do teste sem pagamento, ou 7 dias após o vencimento de uma fatura por pagar, a conta fica só de leitura. O serviço pode ser cancelado a qualquer momento. Os preços são IVA 0% e o IVA é acrescentado na fatura. Os escalões estão na página de preços.",
      },
    ],
    backApps: "Todas as aplicações",
  },
  it: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync è una web app per la manutenzione di flotte pesanti. L’adesivo QR identifica l’unità. Prova gratuita di 30 giorni, senza carta.",
    kicker: "Web app per più aziende, per la manutenzione di una flotta pesante.",
    lead: "iqFleetSync è un libretto di manutenzione per camion, rimorchi, pale gommate, escavatori e altre macchine pesanti. L’azienda si registra da sola. La lingua predefinita è il finlandese.",
    langs: "L’interfaccia del servizio è in finlandese, svedese, norvegese, danese, tedesco, inglese, spagnolo, italiano e francese.",
    signInHeading: "Accesso",
    signIn: [
      "Nessuna password. L’accesso resta nella stessa scheda del browser.",
      "Un codice di 6 cifre arriva per e-mail e si digita in quella stessa scheda.",
      "Un link di invito dall’amministratore.",
      "Impronta o volto (passkey).",
      "Telefono condiviso del veicolo: scegli il tuo nome e un PIN facoltativo di 4–6 cifre. La sessione dura 30 minuti. Un amministratore può creare un PIN nella pagina Persone. Il conducente può cambiarlo con il proprio nella pagina conducente.",
      "Un numero di telefono è solo un contatto facoltativo.",
    ],
    driverHeading: "Conducente",
    driver: [
      "Una normale pagina mobile. Non c’è nulla da installare.",
      "L’adesivo QR sulla macchina identifica l’unità. L’indirizzo breve è r.iqsoftcore.fi. L’adesivo non fa accedere nessuno.",
      "L’adesivo di un’unità archiviata dice che l’unità è stata rimossa (Yksikkö poistettu).",
      "Unità proprie (assegnate e lette), il resto della flotta, difetti, chilometri e ore, e letture di un rimorchio agganciato.",
      "Notifiche del browser. La sessione del conducente dura 90 giorni.",
      "Ore e prezzi sono nascosti al conducente.",
    ],
    adminHeading: "Azienda",
    admin: [
      "Persone: invita, modifica e rimuovi. L’ultimo amministratore non si può rimuovere. Un invito si può reinviare o annullare.",
      "Flotta: aggiungi, importa, esporta (Excel o CSV), modifica e archivia. Storico e fatture restano. Un’unità archiviata non viene fatturata.",
      "Scadenze, ordini di lavoro e officine. A un’officina si può dare un link a tempo.",
      "I costi si vedono solo con il permesso sui costi.",
      "Le segnalazioni del conducente arrivano in tempo reale e si possono confermare.",
      "Un difetto passa per ricevuto, iniziato e fatto, con uno stato di idoneità alla circolazione.",
      "Notifiche per e-mail o nell’app. Un registro di audit. Esportazione e anonimizzazione dei dati personali.",
      "Impostazioni: giorno della segnalazione, intervallo, ora di invio, lingua e modelli di manutenzione. Centro di aiuto integrato.",
    ],
    audience: "Per clienti imprese. La registrazione richiede un codice impresa finlandese (Y-tunnus).",
    vatNote: "I prezzi sono IVA 0%. L’imposta sul valore aggiunto si aggiunge in fattura all’aliquota in vigore.",
    trial: "Prova gratuita di 30 giorni. Nessuna carta richiesta.",
    billing: "La fatturazione è una fattura mensile pagata con bonifico, in base al numero più alto di unità del mese. La quota base è di 10 € al mese. Un veicolo o una macchina operatrice è un’unità, un rimorchio è mezza unità e un’attrezzatura è 0 €. Gli utenti non si fatturano. Un’unità archiviata non viene fatturata. Se la prova finisce senza pagamento, o se una fattura resta non pagata 7 giorni dopo la scadenza, l’account è in sola lettura. Il servizio si può disdire in qualsiasi momento. Gli scaglioni sono nella pagina dei prezzi.",
    cta: "Prova gratis per 30 giorni",
    login: "Accedi",
    pricing: "Prezzi",
    terms: "Condizioni",
    privacy: "Privacy",
    home: "Home",
    faqHeading: "Domande",
    faq: [
      {
        q: "L’adesivo QR fa accedere il conducente?",
        a: "No. Apre l’unità e indica di quale macchina si tratta. L’indirizzo breve è r.iqsoftcore.fi. L’adesivo di un’unità archiviata dice che l’unità è stata rimossa (Yksikkö poistettu).",
      },
      {
        q: "Come si accede?",
        a: "Senza password, nella stessa scheda: un codice e-mail di 6 cifre, un link di invito dell’amministratore, oppure impronta o volto (passkey). Sul telefono condiviso si sceglie il nome e un PIN facoltativo di 4–6 cifre. Quella sessione dura 30 minuti. Un numero di telefono è solo un contatto facoltativo.",
      },
      {
        q: "Cosa vede il conducente?",
        a: "Le proprie unità, il resto della flotta, i difetti, chilometri e ore, le letture di un rimorchio agganciato e le notifiche del browser. La sessione dura 90 giorni. Ore e prezzi sono nascosti. I costi si vedono solo con il permesso sui costi.",
      },
      {
        q: "Come si fattura il servizio?",
        a: "Con una fattura mensile pagata con bonifico, sul picco di unità del mese. La quota base è di 10 €/mese. Un veicolo o una macchina è 1 unità, un rimorchio 0,5 e un’attrezzatura 0 €. Gli utenti non si fatturano. Un’unità archiviata non viene fatturata. La prova dura 30 giorni e non serve una carta. Dopo la prova senza pagamento, o 7 giorni dopo la scadenza di una fattura non pagata, l’account è in sola lettura. Il servizio si può disdire in qualsiasi momento. I prezzi sono IVA 0% e l’IVA si aggiunge in fattura. Gli scaglioni sono nella pagina dei prezzi.",
      },
    ],
    backApps: "Tutte le app",
  },
  pl: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync to aplikacja webowa do utrzymania ciężkiej floty. Naklejka QR identyfikuje jednostkę. 30 dni bezpłatnie, bez karty.",
    kicker: "Aplikacja webowa dla wielu firm, do utrzymania ciężkiej floty.",
    lead: "iqFleetSync to książka serwisowa dla ciężarówek, przyczep, ładowarek kołowych, koparek i innych maszyn ciężkich. Firma rejestruje się sama. Domyślny język to fiński.",
    langs: "Interfejs usługi jest po fińsku, szwedzku, norwesku, duńsku, niemiecku, angielsku, hiszpańsku, włosku i francusku.",
    signInHeading: "Logowanie",
    signIn: [
      "Bez hasła. Logowanie zostaje w tej samej karcie przeglądarki.",
      "6-cyfrowy kod przychodzi e-mailem i wpisuje się go w tej samej karcie.",
      "Link zaproszenia od administratora.",
      "Odcisk palca lub twarz (passkey).",
      "Wspólny telefon pojazdu: wybierz swoje imię i opcjonalny PIN z 4–6 cyfr. Sesja trwa 30 minut. Administrator może utworzyć PIN na stronie Osoby. Kierowca może zmienić go na własny na stronie kierowcy.",
      "Numer telefonu to tylko opcjonalne pole kontaktowe.",
    ],
    driverHeading: "Kierowca",
    driver: [
      "Zwykła strona mobilna. Nic nie trzeba instalować.",
      "Naklejka QR na maszynie identyfikuje jednostkę. Krótki adres to r.iqsoftcore.fi. Naklejka nikogo nie loguje.",
      "Naklejka zarchiwizowanej jednostki informuje, że jednostka została usunięta (Yksikkö poistettu).",
      "Własne jednostki (przypisane i odczytane), reszta floty, usterki, kilometry i motogodziny oraz odczyty podpiętej przyczepy.",
      "Powiadomienia przeglądarki. Sesja kierowcy trwa 90 dni.",
      "Godziny i ceny są ukryte przed kierowcą.",
    ],
    adminHeading: "Firma",
    admin: [
      "Osoby: zaproś, edytuj i usuń. Ostatniego administratora nie można usunąć. Zaproszenie można wysłać ponownie albo anulować.",
      "Flota: dodawanie, import, eksport (Excel lub CSV), edycja i archiwizacja. Historia i faktury zostają. Zarchiwizowanej jednostki się nie rozlicza.",
      "Terminy, zlecenia pracy i warsztaty. Warsztat może dostać link na czas określony.",
      "Koszty widać tylko z uprawnieniem do kosztów.",
      "Zgłoszenia kierowcy przychodzą na bieżąco i można je potwierdzić.",
      "Usterka przechodzi przez przyjęta, rozpoczęta i gotowa, ze stanem zdatności do ruchu.",
      "Powiadomienia e-mailem albo w aplikacji. Dziennik audytu. Eksport i anonimizacja danych osobowych.",
      "Ustawienia: dzień tygodnia zgłoszenia, odstęp, godzina wysyłki, język i szablony utrzymania. Wbudowane centrum pomocy.",
    ],
    audience: "Dla klientów firmowych. Rejestracja wymaga fińskiego numeru firmy (Y-tunnus).",
    vatNote: "Ceny wynoszą VAT 0%. Podatek VAT dolicza się na fakturze według obowiązującej stawki.",
    trial: "30 dni bezpłatnie. Karta nie jest potrzebna.",
    billing: "Rozliczenie to faktura miesięczna płacona przelewem, według najwyższej liczby jednostek w miesiącu kalendarzowym. Opłata podstawowa to 10 € miesięcznie. Pojazd albo maszyna robocza to jedna jednostka, przyczepa to pół jednostki, a osprzęt to 0 €. Użytkowników się nie rozlicza. Zarchiwizowanej jednostki się nie rozlicza. Jeśli okres próbny kończy się bez płatności albo faktura jest niezapłacona 7 dni po terminie, konto jest tylko do odczytu. Usługę można wypowiedzieć w dowolnej chwili. Progi są na stronie cennika.",
    cta: "Wypróbuj bezpłatnie przez 30 dni",
    login: "Zaloguj się",
    pricing: "Cennik",
    terms: "Warunki",
    privacy: "Prywatność",
    home: "Strona główna",
    faqHeading: "Pytania",
    faq: [
      {
        q: "Czy naklejka QR loguje kierowcę?",
        a: "Nie. Otwiera jednostkę i pokazuje, jaka to maszyna. Krótki adres to r.iqsoftcore.fi. Naklejka zarchiwizowanej jednostki informuje, że jednostka została usunięta (Yksikkö poistettu).",
      },
      {
        q: "Jak się logować?",
        a: "Bez hasła, w tej samej karcie: 6-cyfrowy kod e-mail, link zaproszenia od administratora albo odcisk palca lub twarz (passkey). Na wspólnym telefonie pojazdu wybiera się imię i opcjonalny PIN z 4–6 cyfr. Ta sesja trwa 30 minut. Numer telefonu to tylko opcjonalne pole kontaktowe.",
      },
      {
        q: "Co widzi kierowca?",
        a: "Własne jednostki, resztę floty, usterki, kilometry i motogodziny, odczyty podpiętej przyczepy i powiadomienia przeglądarki. Sesja trwa 90 dni. Godziny i ceny są ukryte. Koszty widać tylko z uprawnieniem do kosztów.",
      },
      {
        q: "Jak rozliczana jest usługa?",
        a: "Fakturą miesięczną płaconą przelewem, według szczytowej liczby jednostek. Opłata podstawowa to 10 €/mies. Pojazd albo maszyna to 1 jednostka, przyczepa 0,5, a osprzęt 0 €. Użytkowników się nie rozlicza. Zarchiwizowanej jednostki się nie rozlicza. Okres próbny trwa 30 dni i karta nie jest potrzebna. Po okresie próbnym bez płatności albo 7 dni po terminie niezapłaconej faktury konto jest tylko do odczytu. Usługę można wypowiedzieć w dowolnej chwili. Ceny wynoszą VAT 0%, a VAT dolicza się na fakturze. Progi są na stronie cennika.",
      },
    ],
    backApps: "Wszystkie aplikacje",
  },
  cs: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync je webová aplikace pro údržbu těžké flotily. QR štítek identifikuje jednotku. 30 dní zdarma, bez karty.",
    kicker: "Webová aplikace pro více firem, pro údržbu těžké flotily.",
    lead: "iqFleetSync je kniha údržby pro nákladní auta, přívěsy, kolové nakladače, rypadla a další těžkou techniku. Firma se registruje sama. Výchozí jazyk je finština.",
    langs: "Rozhraní služby je ve finštině, švédštině, norštině, dánštině, němčině, angličtině, španělštině, italštině a francouzštině.",
    signInHeading: "Přihlášení",
    signIn: [
      "Bez hesla. Přihlášení zůstane ve stejné kartě prohlížeče.",
      "Šestimístný kód přijde e-mailem a zadá se ve stejné kartě.",
      "Odkaz na pozvánku od správce.",
      "Otisk prstu nebo obličej (passkey).",
      "Sdílený telefon vozidla: vyberte své jméno a volitelný PIN o 4–6 číslicích. Relace trvá 30 minut. Správce může PIN vytvořit na stránce Osoby. Řidič si ho může na stránce řidiče změnit na vlastní.",
      "Telefonní číslo je jen volitelný kontakt.",
    ],
    driverHeading: "Řidič",
    driver: [
      "Běžná mobilní stránka. Nic se neinstaluje.",
      "QR štítek na stroji identifikuje jednotku. Krátká adresa je r.iqsoftcore.fi. Štítek nikoho nepřihlásí.",
      "Štítek archivované jednotky říká, že jednotka byla odebrána (Yksikkö poistettu).",
      "Vlastní jednotky (přidělené a načtené), zbytek flotily, závady, kilometry a motohodiny a údaje připojeného přívěsu.",
      "Oznámení prohlížeče. Relace řidiče trvá 90 dní.",
      "Hodiny a ceny řidič nevidí.",
    ],
    adminHeading: "Firma",
    admin: [
      "Osoby: pozvat, upravit a odebrat. Posledního správce nelze odebrat. Pozvánku lze poslat znovu nebo zrušit.",
      "Flotila: přidání, import, export (Excel nebo CSV), úprava a archivace. Historie a faktury zůstanou. Archivovaná jednotka se neúčtuje.",
      "Termíny, pracovní příkazy a dílny. Dílna může dostat odkaz na omezenou dobu.",
      "Náklady jsou vidět jen s oprávněním k nákladům.",
      "Hlášení řidiče přicházejí v reálném čase a lze je potvrdit.",
      "Závada prochází stavy přijato, zahájeno a hotovo, se stavem způsobilosti k provozu.",
      "Oznámení e-mailem nebo v aplikaci. Auditní záznam. Export a anonymizace osobních údajů.",
      "Nastavení: den hlášení, interval, čas odeslání, jazyk a šablony údržby. Vestavěné centrum nápovědy.",
    ],
    audience: "Pro firemní zákazníky. Registrace vyžaduje finské IČ (Y-tunnus).",
    vatNote: "Ceny jsou DPH 0 %. Daň z přidané hodnoty se připočte na faktuře podle platné sazby.",
    trial: "30 dní zdarma. Karta není potřeba.",
    billing: "Fakturace je měsíční faktura placená převodem, podle nejvyššího počtu jednotek v kalendářním měsíci. Základní poplatek je 10 € měsíčně. Vozidlo nebo pracovní stroj je jedna jednotka, přívěs je půl jednotky a nástavba je 0 €. Uživatelé se neúčtují. Archivovaná jednotka se neúčtuje. Když zkušební doba skončí bez platby, nebo je faktura nezaplacená 7 dní po splatnosti, účet je jen ke čtení. Službu lze kdykoli zrušit. Pásma jsou na stránce ceníku.",
    cta: "Vyzkoušet zdarma na 30 dní",
    login: "Přihlásit se",
    pricing: "Ceník",
    terms: "Podmínky",
    privacy: "Ochrana soukromí",
    home: "Domů",
    faqHeading: "Otázky",
    faq: [
      {
        q: "Přihlásí QR štítek řidiče?",
        a: "Ne. Otevře jednotku a ukáže, o jaký stroj jde. Krátká adresa je r.iqsoftcore.fi. Štítek archivované jednotky říká, že jednotka byla odebrána (Yksikkö poistettu).",
      },
      {
        q: "Jak se přihlásit?",
        a: "Bez hesla, ve stejné kartě: šestimístný e-mailový kód, odkaz na pozvánku od správce, nebo otisk prstu či obličej (passkey). Na sdíleném telefonu vozidla se vybere jméno a volitelný PIN o 4–6 číslicích. Tato relace trvá 30 minut. Telefonní číslo je jen volitelný kontakt.",
      },
      {
        q: "Co vidí řidič?",
        a: "Vlastní jednotky, zbytek flotily, závady, kilometry a motohodiny, údaje připojeného přívěsu a oznámení prohlížeče. Relace trvá 90 dní. Hodiny a ceny jsou skryté. Náklady jsou vidět jen s oprávněním k nákladům.",
      },
      {
        q: "Jak se služba účtuje?",
        a: "Měsíční fakturou placenou převodem, podle nejvyššího počtu jednotek v měsíci. Základní poplatek je 10 €/měsíc. Vozidlo nebo stroj je 1 jednotka, přívěs 0,5 a nástavba 0 €. Uživatelé se neúčtují. Archivovaná jednotka se neúčtuje. Zkušební doba je 30 dní a karta není potřeba. Po zkušební době bez platby, nebo 7 dní po splatnosti nezaplacené faktury, je účet jen ke čtení. Službu lze kdykoli zrušit. Ceny jsou DPH 0 % a DPH se připočte na faktuře. Pásma jsou na stránce ceníku.",
      },
    ],
    backApps: "Všechny aplikace",
  },
  ja: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSyncは重機・大型車両の整備向けウェブアプリです。QRシールはユニットを識別します。30日間の無料試用。カードは不要です。",
    kicker: "複数の会社で使う、重機・大型車両の整備向けウェブアプリ。",
    lead: "iqFleetSyncは、トラック、トレーラー、ホイールローダー、ショベルなどの重量機械向けの整備記録です。会社が自分で登録します。初期言語はフィンランド語です。",
    langs: "サービスの画面は、フィンランド語、スウェーデン語、ノルウェー語、デンマーク語、ドイツ語、英語、スペイン語、イタリア語、フランス語です。",
    signInHeading: "ログイン",
    signIn: [
      "パスワードはありません。ログインは同じブラウザのタブのままです。",
      "メールに届く6桁のコードを、その同じタブに入力します。",
      "管理者からの招待リンク。",
      "指紋または顔（パスキー）。",
      "共用の車両電話：自分の名前を選び、必要なら4〜6桁のPINを入れます。セッションは30分です。管理者は「担当者」の画面でPINを作れます。運転者は運転者ページで自分のPINに変えられます。",
      "電話番号は、任意の連絡先項目だけです。",
    ],
    driverHeading: "運転者",
    driver: [
      "普通のモバイルページです。インストールはありません。",
      "機械のQRシールはユニットを識別します。短いアドレスは r.iqsoftcore.fi です。シールは誰もログインさせません。",
      "アーカイブしたユニットのシールは、ユニットが削除されたことを示します（Yksikkö poistettu）。",
      "自分のユニット（割り当てと読み取り）、ほかの車両、不具合、走行距離と稼働時間、連結したトレーラーの数値。",
      "ブラウザの通知。運転者のセッションは90日です。",
      "時間と価格は運転者には表示しません。",
    ],
    adminHeading: "会社",
    admin: [
      "担当者：招待、編集、削除。最後の管理者は削除できません。招待は再送または取消ができます。",
      "車両：追加、取り込み、書き出し（ExcelまたはCSV）、編集、アーカイブ。履歴と請求書は残ります。アーカイブした単位は請求しません。",
      "期限、作業指示、整備工場。工場には期限付きのリンクを渡せます。",
      "費用は、費用の権限がある人だけに表示します。",
      "運転者の報告はリアルタイムで届き、確認できます。",
      "不具合は受付、着手、完了と進み、走行可否も記録します。",
      "通知はメールまたはアプリ内です。監査ログ。個人データの書き出しと匿名化。",
      "設定：報告する曜日、間隔、送信時刻、言語、整備テンプレート。組み込みのヘルプセンター。",
    ],
    audience: "事業者向けです。登録にはフィンランドの事業者番号（Y-tunnus）が必要です。",
    vatNote: "価格は消費税0%です。消費税は適用される税率で請求書に加算します。",
    trial: "30日間の無料試用。カードは不要です。",
    billing: "請求は、暦月の最大単位数による月次の請求書で、銀行振込です。基本料金は月10€です。車両と作業機械は1単位、トレーラーは0.5単位、アタッチメントは0€です。ユーザー数は請求しません。アーカイブした単位は請求しません。試用が終わって支払いがない場合、または請求書の期限から7日過ぎても未払いの場合、アカウントは閲覧のみになります。いつでも解約できます。段階は料金ページにあります。",
    cta: "30日間無料で試す",
    login: "ログイン",
    pricing: "料金",
    terms: "利用条件",
    privacy: "プライバシー",
    home: "ホーム",
    faqHeading: "質問",
    faq: [
      {
        q: "QRシールは運転者をログインさせますか？",
        a: "しません。ユニットを開き、どの機械かを示します。短いアドレスは r.iqsoftcore.fi です。アーカイブしたユニットのシールは、ユニットが削除されたことを示します（Yksikkö poistettu）。",
      },
      {
        q: "どうやってログインしますか？",
        a: "パスワードなしで、同じタブです。メールの6桁コード、管理者の招待リンク、または指紋か顔（パスキー）です。共用の車両電話では名前を選び、必要なら4〜6桁のPINを入れます。そのセッションは30分です。電話番号は任意の連絡先項目だけです。",
      },
      {
        q: "運転者には何が見えますか？",
        a: "自分のユニット、ほかの車両、不具合、走行距離と稼働時間、連結したトレーラーの数値、ブラウザの通知です。セッションは90日です。時間と価格は表示しません。費用は費用の権限がある人だけに表示します。",
      },
      {
        q: "料金はどう請求されますか？",
        a: "月の最大単位数に基づく月次の請求書で、銀行振込です。基本料金は月10€です。車両と作業機械は1単位、トレーラーは0.5、アタッチメントは0€です。ユーザー数は請求しません。アーカイブした単位は請求しません。試用は30日で、開始にカードは不要です。支払いのないまま試用が終わるか、未払い請求書の期限から7日たつと、アカウントは閲覧のみになります。いつでも解約できます。価格は消費税0%で、消費税は請求書に加算します。段階は料金ページにあります。",
      },
    ],
    backApps: "すべてのアプリ",
  },
  ko: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync는 대형 장비 정비용 웹 앱입니다. QR 스티커는 장비를 식별합니다. 30일 무료 체험, 카드 불필요.",
    kicker: "여러 회사를 위한 대형 장비 정비 웹 앱.",
    lead: "iqFleetSync는 트럭, 트레일러, 휠 로더, 굴착기 등 중장비의 정비 기록입니다. 회사가 직접 등록합니다. 기본 언어는 핀란드어입니다.",
    langs: "서비스 화면 언어는 핀란드어, 스웨덴어, 노르웨이어, 덴마크어, 독일어, 영어, 스페인어, 이탈리아어, 프랑스어입니다.",
    signInHeading: "로그인",
    signIn: [
      "비밀번호는 없습니다. 로그인은 같은 브라우저 탭에 머뭅니다.",
      "이메일로 온 6자리 코드를 그 탭에 입력합니다.",
      "관리자의 초대 링크.",
      "지문 또는 얼굴(패스키).",
      "공용 차량 전화: 이름을 고르고, 원하면 4–6자리 PIN을 넣습니다. 세션은 30분입니다. 관리자는 사람 화면에서 PIN을 만들 수 있습니다. 운전자는 운전자 화면에서 자기 PIN으로 바꿀 수 있습니다.",
      "전화번호는 선택 연락처 항목일 뿐입니다.",
    ],
    driverHeading: "운전자",
    driver: [
      "일반 모바일 웹 페이지입니다. 설치할 것이 없습니다.",
      "기계의 QR 스티커는 장비를 식별합니다. 짧은 주소는 r.iqsoftcore.fi 입니다. 스티커는 아무도 로그인시키지 않습니다.",
      "보관 처리한 장비의 스티커는 장비가 제거되었다고 보여 줍니다(Yksikkö poistettu).",
      "내 장비(배정된 것과 읽은 것), 나머지 차량, 고장, 주행거리와 가동시간, 연결된 트레일러 수치.",
      "브라우저 알림. 운전자 세션은 90일입니다.",
      "시간과 가격은 운전자에게 보이지 않습니다.",
    ],
    adminHeading: "회사",
    admin: [
      "사람: 초대, 수정, 삭제. 마지막 관리자는 삭제할 수 없습니다. 초대는 다시 보내거나 취소할 수 있습니다.",
      "차량: 추가, 가져오기, 내보내기(Excel 또는 CSV), 수정, 보관. 이력과 청구서는 남습니다. 보관 처리한 단위는 청구하지 않습니다.",
      "기한, 작업 지시, 정비소. 정비소에는 기간이 있는 링크를 줄 수 있습니다.",
      "비용은 비용 권한이 있는 사람에게만 보입니다.",
      "운전자 보고는 실시간으로 오고, 확인할 수 있습니다.",
      "고장은 접수, 시작, 완료로 진행하고, 운행 가능 여부도 기록합니다.",
      "알림은 이메일 또는 앱 안입니다. 감사 기록. 개인정보 내보내기와 익명화.",
      "설정: 보고 요일, 간격, 보내는 시각, 언어, 정비 서식. 내장 도움말.",
    ],
    audience: "사업자용입니다. 등록에는 핀란드 사업자번호(Y-tunnus)가 필요합니다.",
    vatNote: "가격은 부가세 0%입니다. 부가가치세는 적용 세율에 따라 청구서에 더합니다.",
    trial: "30일 무료 체험. 카드는 필요 없습니다.",
    billing: "청구는 그달의 최대 단위 수를 기준으로 한 월 청구서이며, 계좌이체입니다. 기본요금은 월 10€입니다. 차량과 작업기계는 1단위, 트레일러는 0.5단위, 어태치먼트는 0€입니다. 사용자 수는 청구하지 않습니다. 보관 처리한 단위는 청구하지 않습니다. 체험이 끝나고 결제가 없거나, 청구서 만기 후 7일이 지나도 미납이면 계정은 읽기 전용입니다. 언제든 해지할 수 있습니다. 구간은 요금 페이지에 있습니다.",
    cta: "30일 무료로 사용해 보기",
    login: "로그인",
    pricing: "요금",
    terms: "이용 약관",
    privacy: "개인정보",
    home: "홈",
    faqHeading: "질문",
    faq: [
      {
        q: "QR 스티커가 운전자를 로그인시키나요?",
        a: "아닙니다. 장비를 열고 어떤 기계인지 보여 줍니다. 짧은 주소는 r.iqsoftcore.fi 입니다. 보관 처리한 장비의 스티커는 장비가 제거되었다고 보여 줍니다(Yksikkö poistettu).",
      },
      {
        q: "어떻게 로그인하나요?",
        a: "비밀번호 없이, 같은 탭에서입니다. 이메일 6자리 코드, 관리자의 초대 링크, 또는 지문이나 얼굴(패스키)입니다. 공용 차량 전화에서는 이름을 고르고, 원하면 4–6자리 PIN을 넣습니다. 그 세션은 30분입니다. 전화번호는 선택 연락처 항목일 뿐입니다.",
      },
      {
        q: "운전자에게는 무엇이 보이나요?",
        a: "내 장비, 나머지 차량, 고장, 주행거리와 가동시간, 연결된 트레일러 수치, 브라우저 알림입니다. 세션은 90일입니다. 시간과 가격은 보이지 않습니다. 비용은 비용 권한이 있는 사람에게만 보입니다.",
      },
      {
        q: "요금은 어떻게 청구되나요?",
        a: "그달 최대 단위 수를 기준으로 한 월 청구서이며, 계좌이체입니다. 기본요금은 월 10€입니다. 차량과 작업기계는 1단위, 트레일러는 0.5, 어태치먼트는 0€입니다. 사용자 수는 청구하지 않습니다. 보관 처리한 단위는 청구하지 않습니다. 체험은 30일이고 시작하는 데 카드는 필요 없습니다. 결제 없이 체험이 끝나거나, 미납 청구서 만기 후 7일이 지나면 계정은 읽기 전용입니다. 언제든 해지할 수 있습니다. 가격은 부가세 0%이고 부가세는 청구서에 더합니다. 구간은 요금 페이지에 있습니다.",
      },
    ],
    backApps: "모든 앱",
  },
  zh: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync 是重型车队维护网页应用。二维码贴用来识别设备。30 天免费试用，不需要银行卡。",
    kicker: "供多家公司使用的重型车队维护网页应用。",
    lead: "iqFleetSync 是卡车、挂车、轮式装载机、挖掘机和其他重型机械的维护记录。公司自行注册。默认语言是芬兰语。",
    langs: "服务界面提供芬兰语、瑞典语、挪威语、丹麦语、德语、英语、西班牙语、意大利语和法语。",
    signInHeading: "登录",
    signIn: [
      "没有密码。登录留在同一个浏览器标签页。",
      "6 位数字通过电子邮件发来，并在同一个标签页里输入。",
      "管理员发出的邀请链接。",
      "指纹或人脸（通行密钥）。",
      "共用的车辆电话：选择自己的姓名，也可以填写 4–6 位 PIN。会话为 30 分钟。管理员可以在“人员”页生成 PIN。驾驶员可以在驾驶员页把它改成自己的。",
      "电话号码只是可选的联系方式。",
    ],
    driverHeading: "驾驶员",
    driver: [
      "普通的手机网页。无需安装。",
      "机器上的二维码贴用来识别设备。短地址是 r.iqsoftcore.fi。贴纸不会让任何人登录。",
      "已归档设备的贴纸会显示该设备已移除（Yksikkö poistettu）。",
      "自己的设备（已分配和已扫描）、车队里的其他设备、缺陷、公里数和小时数，以及已连接挂车的读数。",
      "浏览器推送通知。驾驶员会话为 90 天。",
      "小时数和价格对驾驶员隐藏。",
    ],
    adminHeading: "公司",
    admin: [
      "人员：邀请、编辑和移除。最后一位管理员不能移除。邀请可以重发或取消。",
      "车队：添加、导入、导出（Excel 或 CSV）、编辑和归档。历史和发票会保留。已归档的单位不计费。",
      "期限、工单和修理厂。可以给修理厂一个有时限的链接。",
      "费用只对有费用权限的人可见。",
      "驾驶员报告实时到达，并且可以确认。",
      "缺陷依次为已收到、已开始、已完成，并记录能否上路。",
      "通知通过电子邮件或应用内发送。审计日志。个人数据导出和匿名化。",
      "设置：报告的星期几、间隔、发送时间、语言和维护模板。内置帮助中心。",
    ],
    audience: "面向企业客户。注册需要芬兰营业编号（Y-tunnus）。",
    vatNote: "价格为增值税 0%。增值税按适用税率加在账单上。",
    trial: "30 天免费试用。不需要银行卡。",
    billing: "计费是按自然月最高单位数开具的月度发票，以银行转账支付。基础费为每月 10 €。车辆或工程机械为 1 个单位，挂车为 0.5 个单位，属具为 0 €。用户不计费。已归档的单位不计费。如果试用结束而没有付款，或者发票在到期日后 7 天仍未支付，账户变为只读。可以随时取消。档位在价格页。",
    cta: "免费试用 30 天",
    login: "登录",
    pricing: "价格",
    terms: "使用条款",
    privacy: "隐私",
    home: "首页",
    faqHeading: "问题",
    faq: [
      {
        q: "二维码贴会让驾驶员登录吗？",
        a: "不会。它打开该设备并说明是哪台机器。短地址是 r.iqsoftcore.fi。已归档设备的贴纸会显示该设备已移除（Yksikkö poistettu）。",
      },
      {
        q: "怎样登录？",
        a: "没有密码，并且留在同一个标签页：电子邮件里的 6 位数字、管理员的邀请链接，或指纹或人脸（通行密钥）。在共用的车辆电话上，选择姓名，也可以填写 4–6 位 PIN。该会话为 30 分钟。电话号码只是可选的联系方式。",
      },
      {
        q: "驾驶员能看到什么？",
        a: "自己的设备、车队里的其他设备、缺陷、公里数和小时数、已连接挂车的读数，以及浏览器通知。会话为 90 天。小时数和价格是隐藏的。费用只对有费用权限的人可见。",
      },
      {
        q: "服务如何计费？",
        a: "按该月最高单位数开具月度发票，以银行转账支付。基础费为每月 10 €。车辆或工程机械为 1 个单位，挂车为 0.5，属具为 0 €。用户不计费。已归档的单位不计费。试用为 30 天，开始时不需要银行卡。试用结束而没有付款，或者未付发票到期日后 7 天，账户变为只读。可以随时取消。价格为增值税 0%，增值税加在账单上。档位在价格页。",
      },
    ],
    backApps: "全部应用",
  },
};

function escapeFleetHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderFleetSyncPage(lang) {
  const root = document.getElementById("fleetsync-root");
  if (!root) return;
  const page = FLEETSYNC_PAGE[lang] || FLEETSYNC_PAGE.en;

  const titleEl = document.querySelector("title");
  if (titleEl) titleEl.textContent = page.metaTitle;
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc) metaDesc.setAttribute("content", page.metaDescription);

  const list = (items) => `<ul>${items.map((item) => `<li>${escapeFleetHtml(item)}</li>`).join("")}</ul>`;
  const faq = (page.faq || [])
    .map((item) => `<h3>${escapeFleetHtml(item.q)}</h3><p>${escapeFleetHtml(item.a)}</p>`)
    .join("");

  root.innerHTML = `<h1>iqFleetSync</h1>
    <p class="app-short">${escapeFleetHtml(page.kicker)}</p>
    <p>${escapeFleetHtml(page.lead)}</p>
    <p>${escapeFleetHtml(page.langs)}</p>
    <p><a href="https://fleetsync.iqsoftcore.fi">fleetsync.iqsoftcore.fi</a></p>
    <h2>${escapeFleetHtml(page.signInHeading)}</h2>
    ${list(page.signIn)}
    <h2>${escapeFleetHtml(page.driverHeading)}</h2>
    ${list(page.driver)}
    <h2>${escapeFleetHtml(page.adminHeading)}</h2>
    ${list(page.admin)}
    <p>${escapeFleetHtml(page.audience)}</p>
    <p>${escapeFleetHtml(page.vatNote)}</p>
    <p>${escapeFleetHtml(page.trial)}</p>
    <p>${escapeFleetHtml(page.billing)}</p>
    <div class="app-actions">
      <a class="btn btn-primary" href="https://fleetsync.iqsoftcore.fi/rekisteroidy">${escapeFleetHtml(page.cta)}</a>
      <a class="btn btn-ghost" href="https://fleetsync.iqsoftcore.fi/login">${escapeFleetHtml(page.login)}</a>
    </div>
    <h2>${escapeFleetHtml(page.faqHeading)}</h2>
    ${faq}
    <p class="policy-nav">
      <a class="btn btn-ghost" href="hinnasto.html">${escapeFleetHtml(page.pricing)}</a>
      <a class="btn btn-ghost" href="kayttoehdot.html">${escapeFleetHtml(page.terms)}</a>
      <a class="btn btn-ghost" href="privacy.html#iqfleetsync">${escapeFleetHtml(page.privacy)}</a>
      <a class="btn btn-ghost" href="apps.html">${escapeFleetHtml(page.backApps)}</a>
      <a class="btn btn-ghost" href="index.html">${escapeFleetHtml(page.home)}</a>
    </p>`;
}
