/**
 * iqFleetSync selling page.
 * Three views and what they make easier. No access-control or sign-in detail.
 */
const FLEETSYNC_PAGE = {
  fi: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync pitää yrityksen, huollon ja kuljettajat samalla kartalla. Huollot ja korjaukset pysyvät ajan tasalla. Selaimessa, ei asennusta. 30 päivän kokeilu.",
    kicker: "Yritys, huolto ja kuljettaja samassa paikassa.",
    lead: "iqFleetSync tekee yhteydenpidon helpoksi ja pitää huollot sekä korjaukset ajan tasalla. Laput ja WhatsApp-ketjut voivat jäädä hansikaslokeroon. Avaat sen selaimessa puhelimella tai tietokoneella. Mitään ei asenneta.",
    browser: "Sama palvelu käy yritykselle, huollolle ja kuljettajalle. Jokainen avaa oman näkymänsä selaimessa.",
    qr: "QR-tarrat kiinnitetään kuorma-autoihin, perävaunuihin, pyöräkuormaajiin, kaivinkoneisiin ja muuhun kalustoon. Puhelimen kamera avaa oikean yksikön.",
    viewsHeading: "Kolme näkymää",
    companyTitle: "Yritys",
    companyKicker: "Pääkäyttäjän näkymä",
    companyLead: "Tästä pidät kaluston tilanteen koossa ja huollot järjestyksessä.",
    company: [
      "Huoltosuunnitelmat ja määräajat kilometreinä, tunteina tai päivämääränä. Muistutukset tulevista ja myöhässä olevista tulevat sähköpostilla tai sovelluksessa.",
      "Huoltohistoria ja kustannukset pysyvät yksikön mukana, joten näet mitä on tehty.",
      "Työmääräykset kulkevat yrityksen ja huollon välillä, joten puhutte samasta työstä.",
      "Vähemmän soittoja: tilanne on jo näkymässä.",
    ],
    shopTitle: "Huolto",
    shopKicker: "Huollon näkymä",
    shopLead: "Viat, työt ja historia ovat yhdessä listassa, eivät pinossa papereita.",
    shop: [
      "Vikailmoitukset kuvineen tulevat tänne, eivät viestiketjuun.",
      "Kuittaa vika, merkitse se käyntiin ja valmiiksi. Kuljettaja saa tiedon sovelluksessa.",
      "Työmääräykset ja yksikön huoltohistoria kulkevat työn mukana.",
      "QR-tarrat voi tulostaa suoraan näkymästä.",
    ],
    driverTitle: "Kuljettaja",
    driverKicker: "Kuljettajan näkymä",
    driverLead: "Ilmoitus lähtee tien päältä, eikä sitä tarvitse kertoa uudestaan chatissa.",
    driver: [
      "Skannaa yksikön tarra puhelimen kameralla.",
      "Tee vikailmoitus kuvan kanssa. Voit merkitä, jos yksikkö ei ole liikennekelpoinen.",
      "Kirjaa kilometrit ja tunnit, myös perävaunun osalta.",
      "Näet, miten ilmoitus etenee.",
    ],
    instructions: "Jokaisessa näkymässä on omat ohjeet. Niistä näkee, mitä seuraavaksi tehdään.",
    priceHeading: "Hinta",
    priceLead: "Käyttäjiä on rajattomasti. Hinta tulee kaluston määrästä. Laskuri näyttää kuukauden hinnan.",
    trial: "30 päivän ilmainen kokeilu.",
    audience: "Yrityksille. Rekisteröitymiseen tarvitaan suomalainen Y-tunnus.",
    cta: "Aloita 30 päivän kokeilu",
    login: "Avaa palvelu",
    contact: "Ota yhteyttä",
    pricing: "Hinnasto",
    terms: "Käyttöehdot",
    privacy: "Tietosuojaseloste",
    home: "Etusivu",
    faqHeading: "Kysymyksiä",
    faq: [
      { q: "Pitääkö jotain asentaa?", a: "Ei. Yritys, huolto ja kuljettaja avaavat palvelun selaimessa puhelimella tai tietokoneella." },
      { q: "Mitä lapuille ja WhatsApp-ketjuille käy?", a: "Viat, kilometrit, työmääräykset ja huoltomuistutukset ovat samassa paikassa. Jokaisessa näkymässä on omat ohjeet." },
      { q: "Mitä se maksaa?", a: "Käyttäjiä on rajattomasti. Hinta tulee kaluston määrästä. Laskuri näyttää kuukauden hinnan, ja kokeilu on 30 päivää." },
    ],
    backApps: "Kaikki sovellukset",
  },
  en: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync keeps the company, maintenance and drivers on the same page. Services and repairs stay up to date. In the browser, nothing to install. 30-day trial.",
    kicker: "Company, maintenance and driver, in one place.",
    lead: "iqFleetSync makes the conversation easy and keeps services and repairs up to date. The paper notes and WhatsApp threads can stay in the glovebox. You open it in the browser on a phone or a computer. Nothing to install.",
    browser: "The same service works for the company, maintenance and drivers. Each person opens their own view in the browser.",
    qr: "QR stickers go on trucks, trailers, wheel loaders, excavators and other machines. The phone camera opens the right unit.",
    viewsHeading: "Three views",
    companyTitle: "Company",
    companyKicker: "Admin view",
    companyLead: "This is where you keep the fleet together and the services in order.",
    company: [
      "Service plans and deadlines by kilometres, hours or date. Reminders for what’s coming and what’s late arrive by email or in the app.",
      "Maintenance history and costs stay with the unit, so you can see what was done.",
      "Work orders travel between the company and the workshop, so you talk about the same job.",
      "Fewer phone calls: the situation is already in the view.",
    ],
    shopTitle: "Maintenance",
    shopKicker: "Workshop view",
    shopLead: "Defects, jobs and history sit in one list, not in a pile of paper.",
    shop: [
      "Defect reports, with photos, land here instead of in a message thread.",
      "Acknowledge a defect, mark it in progress and mark it fixed. The driver gets the update in the app.",
      "Work orders and the unit’s history travel with the job.",
      "QR stickers can be printed from the view.",
    ],
    driverTitle: "Driver",
    driverKicker: "Driver view",
    driverLead: "The report goes out from the roadside. No need to retell it in a chat.",
    driver: [
      "Scan the unit’s sticker with the phone camera.",
      "Send a defect report with a photo. You can mark the unit if it should stay off the road.",
      "Enter kilometres and hours, including the trailer.",
      "See how the report moves forward.",
    ],
    instructions: "Each view has its own instructions, so the next step is right there.",
    priceHeading: "Price",
    priceLead: "Users are unlimited. The price follows the size of the fleet. The calculator shows the monthly price.",
    trial: "30-day free trial.",
    audience: "For companies. Signup needs a Finnish business ID (Y-tunnus).",
    cta: "Start the 30-day trial",
    login: "Open the service",
    contact: "Contact us",
    pricing: "Price list",
    terms: "Terms",
    privacy: "Privacy notice",
    home: "Home",
    faqHeading: "Questions",
    faq: [
      { q: "Does anyone install an app?", a: "No. The company, maintenance and drivers open the service in the browser on a phone or a computer." },
      { q: "What happens to the notes and WhatsApp threads?", a: "Defects, kilometres, work orders and service reminders live in one place. Each view has its own instructions." },
      { q: "What does it cost?", a: "Users are unlimited. The price follows the fleet. The calculator shows the monthly price, and the trial is 30 days." },
    ],
    backApps: "All apps",
  },
  sv: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync håller företaget, underhållet och förarna på samma karta. Service och reparationer hålls aktuella. I webbläsaren, inget att installera. 30 dagars prov.",
    kicker: "Företag, underhåll och förare på samma ställe.",
    lead: "iqFleetSync gör kontakten enkel och håller service och reparationer aktuella. Lapparna och WhatsApp-trådarna kan stanna i handskfacket. Du öppnar det i webbläsaren på telefon eller dator. Inget att installera.",
    browser: "Samma tjänst fungerar för företaget, underhållet och förarna. Var och en öppnar sin egen vy i webbläsaren.",
    qr: "QR-dekaler sätts på lastbilar, släp, hjullastare, grävmaskiner och andra maskiner. Telefonens kamera öppnar rätt enhet.",
    viewsHeading: "Tre vyer",
    companyTitle: "Företag",
    companyKicker: "Administratörens vy",
    companyLead: "Här håller du ihop flottan och har servicen i ordning.",
    company: [
      "Serviceplaner och tidsgränser i kilometer, timmar eller datum. Påminnelser om det som kommer och det som är sent kommer med e-post eller i appen.",
      "Underhållshistorik och kostnader stannar hos enheten, så du ser vad som är gjort.",
      "Arbetsorder går mellan företaget och verkstaden, så ni talar om samma jobb.",
      "Färre samtal: läget finns redan i vyn.",
    ],
    shopTitle: "Underhåll",
    shopKicker: "Verkstadens vy",
    shopLead: "Fel, jobb och historik ligger i en lista, inte i en hög papper.",
    shop: [
      "Felanmälningar med foton kommer hit, inte till en meddelandetråd.",
      "Kvittera felet, markera det som pågående och klart. Föraren får besked i appen.",
      "Arbetsorder och enhetens historik följer med jobbet.",
      "QR-dekaler kan skrivas ut från vyn.",
    ],
    driverTitle: "Förare",
    driverKicker: "Förarens vy",
    driverLead: "Anmälan går iväg från vägkanten. Den behöver inte berättas om i en chatt.",
    driver: [
      "Skanna enhetens dekal med telefonens kamera.",
      "Gör en felanmälan med bild. Du kan markera om enheten inte ska ut i trafik.",
      "Skriv in kilometer och timmar, även för släpet.",
      "Du ser hur anmälan går vidare.",
    ],
    instructions: "Varje vy har egna instruktioner. Där syns nästa steg.",
    priceHeading: "Pris",
    priceLead: "Antalet användare är obegränsat. Priset följer flottans storlek. Räknaren visar månadspriset.",
    trial: "30 dagars gratis provperiod.",
    audience: "För företag. Registrering kräver ett finskt FO-nummer (Y-tunnus).",
    cta: "Starta 30 dagars prov",
    login: "Öppna tjänsten",
    contact: "Kontakta oss",
    pricing: "Prislista",
    terms: "Villkor",
    privacy: "Integritetsmeddelande",
    home: "Startsida",
    faqHeading: "Frågor",
    faq: [
      { q: "Behöver någon installera en app?", a: "Nej. Företaget, underhållet och förarna öppnar tjänsten i webbläsaren på telefon eller dator." },
      { q: "Vad händer med lapparna och WhatsApp-trådarna?", a: "Fel, kilometer, arbetsorder och servicepåminnelser finns på samma ställe. Varje vy har egna instruktioner." },
      { q: "Vad kostar det?", a: "Antalet användare är obegränsat. Priset följer flottan. Räknaren visar månadspriset, och provet är 30 dagar." },
    ],
    backApps: "Alla appar",
  },
  no: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync holder bedriften, vedlikeholdet og sjåførene på samme kart. Service og reparasjoner holdes oppdatert. I nettleseren, ingenting å installere. 30 dagers prøve.",
    kicker: "Bedrift, vedlikehold og sjåfør på samme sted.",
    lead: "iqFleetSync gjør kontakten enkel og holder service og reparasjoner oppdatert. Lappene og WhatsApp-trådene kan bli i hanskerommet. Du åpner det i nettleseren på telefon eller datamaskin. Ingenting å installere.",
    browser: "Samme tjeneste virker for bedriften, vedlikeholdet og sjåførene. Hver person åpner sitt eget vindu i nettleseren.",
    qr: "QR-merker settes på lastebiler, tilhengere, hjullastere, gravemaskiner og andre maskiner. Telefonkameraet åpner riktig enhet.",
    viewsHeading: "Tre vinduer",
    companyTitle: "Bedrift",
    companyKicker: "Administratorens vindu",
    companyLead: "Her holder du flåten samlet og servicen i orden.",
    company: [
      "Serviceplaner og frister i kilometer, timer eller dato. Påminnelser om det som kommer og det som er for sent, kommer på e-post eller i appen.",
      "Vedlikeholdshistorikk og kostnader blir hos enheten, så du ser hva som er gjort.",
      "Arbeidsordrer går mellom bedriften og verkstedet, så dere snakker om samme jobb.",
      "Færre telefoner: situasjonen ligger allerede i vinduet.",
    ],
    shopTitle: "Vedlikehold",
    shopKicker: "Verkstedets vindu",
    shopLead: "Feil, jobber og historikk ligger i én liste, ikke i en bunke papir.",
    shop: [
      "Feilmeldinger med bilder kommer hit, ikke i en meldingstråd.",
      "Kvitter feilen, merk den som i gang og ferdig. Sjåføren får beskjed i appen.",
      "Arbeidsordrer og enhetens historikk følger med jobben.",
      "QR-merker kan skrives ut fra vinduet.",
    ],
    driverTitle: "Sjåfør",
    driverKicker: "Sjåførens vindu",
    driverLead: "Meldingen går fra veikanten. Den trenger ikke fortelles om igjen i en chat.",
    driver: [
      "Skann enhetens merke med telefonkameraet.",
      "Lag en feilmelding med bilde. Du kan merke om enheten ikke skal ut på veien.",
      "Skriv inn kilometer og timer, også for tilhengeren.",
      "Du ser hvordan meldingen går videre.",
    ],
    instructions: "Hvert vindu har egne instruksjoner. Der ser du neste steg.",
    priceHeading: "Pris",
    priceLead: "Antall brukere er ubegrenset. Prisen følger flåtens størrelse. Kalkulatoren viser månedsprisen.",
    trial: "30 dagers gratis prøve.",
    audience: "For bedrifter. Registrering krever et finsk organisasjonsnummer (Y-tunnus).",
    cta: "Start 30 dagers prøve",
    login: "Åpne tjenesten",
    contact: "Ta kontakt",
    pricing: "Prisliste",
    terms: "Vilkår",
    privacy: "Personvernerklæring",
    home: "Hjem",
    faqHeading: "Spørsmål",
    faq: [
      { q: "Må noen installere en app?", a: "Nei. Bedriften, vedlikeholdet og sjåførene åpner tjenesten i nettleseren på telefon eller datamaskin." },
      { q: "Hva skjer med lappene og WhatsApp-trådene?", a: "Feil, kilometer, arbeidsordrer og servicepåminnelser ligger på samme sted. Hvert vindu har egne instruksjoner." },
      { q: "Hva koster det?", a: "Antall brukere er ubegrenset. Prisen følger flåten. Kalkulatoren viser månedsprisen, og prøven er 30 dager." },
    ],
    backApps: "Alle apper",
  },
  da: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync holder virksomheden, vedligeholdet og chaufførerne på samme kort. Service og reparationer holdes ajour. I browseren, intet at installere. 30 dages prøve.",
    kicker: "Virksomhed, vedligehold og chauffør samme sted.",
    lead: "iqFleetSync gør kontakten nem og holder service og reparationer ajour. Sedlerne og WhatsApp-trådene kan blive i handskerummet. Du åbner det i browseren på telefon eller computer. Intet at installere.",
    browser: "Samme tjeneste virker for virksomheden, vedligeholdet og chaufførerne. Hver person åbner sit eget vindue i browseren.",
    qr: "QR-mærker sættes på lastbiler, anhængere, gummigeder, gravemaskiner og andre maskiner. Telefonens kamera åbner den rigtige enhed.",
    viewsHeading: "Tre vinduer",
    companyTitle: "Virksomhed",
    companyKicker: "Administratorens vindue",
    companyLead: "Her holder du vognparken samlet og servicen i orden.",
    company: [
      "Serviceplaner og frister i kilometer, timer eller dato. Påmindelser om det der kommer, og det der er for sent, kommer på e-mail eller i appen.",
      "Vedligeholdelseshistorik og omkostninger bliver hos enheden, så du kan se hvad der er gjort.",
      "Arbejdsordrer går mellem virksomheden og værkstedet, så I taler om det samme job.",
      "Færre opkald: situationen ligger allerede i vinduet.",
    ],
    shopTitle: "Vedligehold",
    shopKicker: "Værkstedets vindue",
    shopLead: "Fejl, job og historik ligger i én liste, ikke i en bunke papir.",
    shop: [
      "Fejlmeldinger med billeder lander her, ikke i en beskedtråd.",
      "Kvittér fejlen, markér den som i gang og færdig. Chaufføren får besked i appen.",
      "Arbejdsordrer og enhedens historik følger med jobbet.",
      "QR-mærker kan udskrives fra vinduet.",
    ],
    driverTitle: "Chauffør",
    driverKicker: "Chaufførens vindue",
    driverLead: "Meldingen sendes fra vejkanten. Den skal ikke fortælles igen i en chat.",
    driver: [
      "Scan enhedens mærke med telefonens kamera.",
      "Lav en fejlmelding med billede. Du kan markere, hvis enheden ikke skal ud at køre.",
      "Skriv kilometer og timer, også for anhængeren.",
      "Du ser, hvordan meldingen skrider frem.",
    ],
    instructions: "Hvert vindue har sine egne instruktioner. Der står det næste skridt.",
    priceHeading: "Pris",
    priceLead: "Antallet af brugere er ubegrænset. Prisen følger vognparkens størrelse. Beregneren viser månedsprisen.",
    trial: "30 dages gratis prøve.",
    audience: "Til virksomheder. Registrering kræver et finsk virksomhedsnummer (Y-tunnus).",
    cta: "Start 30 dages prøve",
    login: "Åbn tjenesten",
    contact: "Kontakt os",
    pricing: "Prisliste",
    terms: "Vilkår",
    privacy: "Privatlivspolitik",
    home: "Forside",
    faqHeading: "Spørgsmål",
    faq: [
      { q: "Skal nogen installere en app?", a: "Nej. Virksomheden, vedligeholdet og chaufførerne åbner tjenesten i browseren på telefon eller computer." },
      { q: "Hvad sker der med sedlerne og WhatsApp-trådene?", a: "Fejl, kilometer, arbejdsordrer og servicepåmindelser ligger samme sted. Hvert vindue har sine egne instruktioner." },
      { q: "Hvad koster det?", a: "Antallet af brugere er ubegrænset. Prisen følger vognparken. Beregneren viser månedsprisen, og prøven er 30 dage." },
    ],
    backApps: "Alle apps",
  },
  de: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync hält Unternehmen, Werkstatt und Fahrer auf demselben Stand. Wartung und Reparaturen bleiben aktuell. Im Browser, nichts zu installieren. 30 Tage testen.",
    kicker: "Unternehmen, Werkstatt und Fahrer an einem Ort.",
    lead: "iqFleetSync macht die Abstimmung leicht und hält Wartung und Reparaturen aktuell. Zettel und WhatsApp-Verläufe können im Handschuhfach bleiben. Sie öffnen es im Browser auf dem Telefon oder Computer. Nichts zu installieren.",
    browser: "Derselbe Dienst gilt für Unternehmen, Werkstatt und Fahrer. Jede Person öffnet ihre eigene Ansicht im Browser.",
    qr: "QR-Aufkleber kommen an Lkw, Anhänger, Radlader, Bagger und andere Maschinen. Die Handykamera öffnet die richtige Einheit.",
    viewsHeading: "Drei Ansichten",
    companyTitle: "Unternehmen",
    companyKicker: "Ansicht der Administration",
    companyLead: "Hier bleibt der Fuhrpark beisammen und die Wartung in Ordnung.",
    company: [
      "Wartungspläne und Fristen nach Kilometern, Stunden oder Datum. Erinnerungen an das, was kommt, und das, was überfällig ist, per E-Mail oder in der App.",
      "Wartungshistorie und Kosten bleiben bei der Einheit, damit Sie sehen, was erledigt ist.",
      "Arbeitsaufträge laufen zwischen Unternehmen und Werkstatt, damit alle vom selben Auftrag sprechen.",
      "Weniger Anrufe: der Stand ist schon in der Ansicht.",
    ],
    shopTitle: "Werkstatt",
    shopKicker: "Ansicht der Werkstatt",
    shopLead: "Mängel, Aufträge und Historie liegen in einer Liste, nicht auf einem Stapel Papier.",
    shop: [
      "Mängelmeldungen mit Fotos landen hier, nicht in einem Nachrichtenverlauf.",
      "Mangel quittieren, als in Arbeit markieren und als erledigt markieren. Die fahrende Person bekommt die Nachricht in der App.",
      "Arbeitsaufträge und die Historie der Einheit bleiben beim Auftrag.",
      "QR-Aufkleber lassen sich aus der Ansicht drucken.",
    ],
    driverTitle: "Fahrer",
    driverKicker: "Ansicht der fahrenden Person",
    driverLead: "Die Meldung geht von der Straße aus. Sie muss nicht noch einmal im Chat erzählt werden.",
    driver: [
      "Den Aufkleber der Einheit mit der Handykamera scannen.",
      "Eine Mängelmeldung mit Foto senden. Sie können markieren, wenn die Einheit nicht auf die Straße soll.",
      "Kilometer und Stunden eintragen, auch für den Anhänger.",
      "Sie sehen, wie die Meldung weitergeht.",
    ],
    instructions: "Jede Ansicht hat eigene Hinweise. Der nächste Schritt steht dort.",
    priceHeading: "Preis",
    priceLead: "Die Zahl der Benutzer ist unbegrenzt. Der Preis folgt der Größe des Fuhrparks. Der Rechner zeigt den Monatspreis.",
    trial: "30 Tage kostenlos testen.",
    audience: "Für Unternehmen. Die Registrierung braucht eine finnische Geschäftskennnummer (Y-tunnus).",
    cta: "30 Tage kostenlos starten",
    login: "Dienst öffnen",
    contact: "Kontakt",
    pricing: "Preisliste",
    terms: "Bedingungen",
    privacy: "Datenschutz",
    home: "Startseite",
    faqHeading: "Fragen",
    faq: [
      { q: "Muss jemand eine App installieren?", a: "Nein. Unternehmen, Werkstatt und Fahrer öffnen den Dienst im Browser auf Telefon oder Computer." },
      { q: "Was wird aus den Zetteln und WhatsApp-Verläufen?", a: "Mängel, Kilometer, Arbeitsaufträge und Wartungserinnerungen liegen an einem Ort. Jede Ansicht hat eigene Hinweise." },
      { q: "Was kostet es?", a: "Die Zahl der Benutzer ist unbegrenzt. Der Preis folgt dem Fuhrpark. Der Rechner zeigt den Monatspreis, und der Test dauert 30 Tage." },
    ],
    backApps: "Alle Apps",
  },
  nl: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync houdt bedrijf, onderhoud en chauffeurs op één lijn. Onderhoud en reparaties blijven bij. In de browser, niets te installeren. 30 dagen proberen.",
    kicker: "Bedrijf, onderhoud en chauffeur op één plek.",
    lead: "iqFleetSync maakt het overleg makkelijk en houdt onderhoud en reparaties bij. Briefjes en WhatsApp-gesprekken mogen in het dashboardkastje blijven. U opent het in de browser op telefoon of computer. Niets te installeren.",
    browser: "Dezelfde dienst werkt voor het bedrijf, het onderhoud en de chauffeurs. Iedereen opent zijn eigen scherm in de browser.",
    qr: "QR-stickers komen op vrachtwagens, aanhangers, wielladers, graafmachines en andere machines. De camera van de telefoon opent de juiste eenheid.",
    viewsHeading: "Drie schermen",
    companyTitle: "Bedrijf",
    companyKicker: "Scherm van de beheerder",
    companyLead: "Hier houdt u het wagenpark bij elkaar en het onderhoud op orde.",
    company: [
      "Onderhoudsplannen en termijnen in kilometers, uren of datum. Herinneringen voor wat eraan komt en wat te laat is, per e-mail of in de app.",
      "Onderhoudshistorie en kosten blijven bij de eenheid, zodat u ziet wat er is gedaan.",
      "Werkorders gaan tussen bedrijf en werkplaats, zodat u over dezelfde klus praat.",
      "Minder bellen: de stand van zaken staat al in het scherm.",
    ],
    shopTitle: "Onderhoud",
    shopKicker: "Scherm van de werkplaats",
    shopLead: "Gebreken, klussen en historie staan in één lijst, niet op een stapel papier.",
    shop: [
      "Storingsmeldingen met foto’s komen hier, niet in een berichtendraad.",
      "Een storing afvinken, als bezig markeren en als klaar markeren. De chauffeur krijgt het bericht in de app.",
      "Werkorders en de historie van de eenheid reizen met de klus mee.",
      "QR-stickers kunt u vanuit het scherm afdrukken.",
    ],
    driverTitle: "Chauffeur",
    driverKicker: "Scherm van de chauffeur",
    driverLead: "De melding gaat vanaf de weg. U hoeft het niet nog eens in een chat te vertellen.",
    driver: [
      "Scan de sticker van de eenheid met de camera van de telefoon.",
      "Stuur een storingsmelding met een foto. U kunt aangeven als de eenheid de weg niet op mag.",
      "Vul kilometers en uren in, ook van de aanhanger.",
      "U ziet hoe de melding vordert.",
    ],
    instructions: "Elk scherm heeft eigen aanwijzingen. De volgende stap staat daar.",
    priceHeading: "Prijs",
    priceLead: "Het aantal gebruikers is onbeperkt. De prijs volgt de grootte van het wagenpark. De rekenhulp toont de maandprijs.",
    trial: "30 dagen gratis proberen.",
    audience: "Voor bedrijven. Registratie vraagt een Fins ondernemingsnummer (Y-tunnus).",
    cta: "Start 30 dagen proberen",
    login: "Dienst openen",
    contact: "Contact",
    pricing: "Prijslijst",
    terms: "Voorwaarden",
    privacy: "Privacy",
    home: "Home",
    faqHeading: "Vragen",
    faq: [
      { q: "Moet iemand een app installeren?", a: "Nee. Bedrijf, onderhoud en chauffeurs openen de dienst in de browser op telefoon of computer." },
      { q: "Wat gebeurt er met de briefjes en WhatsApp-gesprekken?", a: "Storingen, kilometers, werkorders en onderhoudsherinneringen staan op één plek. Elk scherm heeft eigen aanwijzingen." },
      { q: "Wat kost het?", a: "Het aantal gebruikers is onbeperkt. De prijs volgt het wagenpark. De rekenhulp toont de maandprijs, en de proef is 30 dagen." },
    ],
    backApps: "Alle apps",
  },
  fr: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync garde l’entreprise, l’entretien et les conducteurs sur la même page. Les entretiens et les réparations restent à jour. Dans le navigateur, rien à installer. Essai de 30 jours.",
    kicker: "Entreprise, entretien et conducteur au même endroit.",
    lead: "iqFleetSync rend les échanges simples et garde les entretiens et les réparations à jour. Les papiers et les fils WhatsApp peuvent rester dans la boîte à gants. Vous l’ouvrez dans le navigateur, sur un téléphone ou un ordinateur. Rien à installer.",
    browser: "Le même service sert à l’entreprise, à l’entretien et aux conducteurs. Chacun ouvre sa vue dans le navigateur.",
    qr: "Les autocollants QR se posent sur les camions, les remorques, les chargeuses, les pelles et les autres machines. L’appareil photo du téléphone ouvre la bonne unité.",
    viewsHeading: "Trois vues",
    companyTitle: "Entreprise",
    companyKicker: "Vue de l’administrateur",
    companyLead: "C’est ici que le parc reste ensemble et que l’entretien reste en ordre.",
    company: [
      "Plans d’entretien et échéances en kilomètres, en heures ou en date. Les rappels de ce qui arrive et de ce qui est en retard arrivent par e-mail ou dans l’application.",
      "L’historique d’entretien et les coûts restent avec l’unité, pour voir ce qui a été fait.",
      "Les ordres de travail circulent entre l’entreprise et l’atelier, pour parler du même travail.",
      "Moins d’appels : la situation est déjà dans la vue.",
    ],
    shopTitle: "Entretien",
    shopKicker: "Vue de l’atelier",
    shopLead: "Les défauts, les travaux et l’historique sont dans une liste, pas sur une pile de papiers.",
    shop: [
      "Les signalements de défaut, avec photos, arrivent ici, pas dans un fil de messages.",
      "Accusez le défaut, marquez-le en cours, puis réparé. Le conducteur reçoit la nouvelle dans l’application.",
      "Les ordres de travail et l’historique de l’unité suivent le travail.",
      "Les autocollants QR s’impriment depuis la vue.",
    ],
    driverTitle: "Conducteur",
    driverKicker: "Vue du conducteur",
    driverLead: "Le signalement part du bord de la route. Inutile de le raconter encore dans une discussion.",
    driver: [
      "Scannez l’autocollant de l’unité avec l’appareil photo du téléphone.",
      "Envoyez un signalement avec une photo. Vous pouvez indiquer si l’unité ne doit pas prendre la route.",
      "Saisissez les kilomètres et les heures, y compris pour la remorque.",
      "Vous voyez comment le signalement avance.",
    ],
    instructions: "Chaque vue a ses propres consignes. L’étape suivante est indiquée.",
    priceHeading: "Prix",
    priceLead: "Le nombre d’utilisateurs est illimité. Le prix suit la taille du parc. Le calculateur montre le prix du mois.",
    trial: "Essai gratuit de 30 jours.",
    audience: "Pour les entreprises. L’inscription demande un numéro d’entreprise finlandais (Y-tunnus).",
    cta: "Commencer l’essai de 30 jours",
    login: "Ouvrir le service",
    contact: "Nous contacter",
    pricing: "Tarifs",
    terms: "Conditions",
    privacy: "Confidentialité",
    home: "Accueil",
    faqHeading: "Questions",
    faq: [
      { q: "Faut-il installer une application ?", a: "Non. L’entreprise, l’entretien et les conducteurs ouvrent le service dans le navigateur, sur un téléphone ou un ordinateur." },
      { q: "Que deviennent les papiers et les fils WhatsApp ?", a: "Défauts, kilomètres, ordres de travail et rappels d’entretien sont au même endroit. Chaque vue a ses consignes." },
      { q: "Combien ça coûte ?", a: "Le nombre d’utilisateurs est illimité. Le prix suit le parc. Le calculateur montre le prix du mois, et l’essai dure 30 jours." },
    ],
    backApps: "Toutes les applications",
  },
  es: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync mantiene a la empresa, el mantenimiento y los conductores en la misma página. Los servicios y las reparaciones siguen al día. En el navegador, nada que instalar. Prueba de 30 días.",
    kicker: "Empresa, mantenimiento y conductor en el mismo sitio.",
    lead: "iqFleetSync hace fácil la comunicación y mantiene los servicios y las reparaciones al día. Los papeles y los hilos de WhatsApp pueden quedarse en la guantera. Se abre en el navegador, en el teléfono o en el ordenador. Nada que instalar.",
    browser: "El mismo servicio vale para la empresa, el mantenimiento y los conductores. Cada persona abre su vista en el navegador.",
    qr: "Las pegatinas QR van en camiones, remolques, palas cargadoras, excavadoras y otras máquinas. La cámara del teléfono abre la unidad correcta.",
    viewsHeading: "Tres vistas",
    companyTitle: "Empresa",
    companyKicker: "Vista del administrador",
    companyLead: "Aquí se tiene la flota junta y los servicios en orden.",
    company: [
      "Planes de servicio y plazos por kilómetros, horas o fecha. Los avisos de lo que viene y de lo que va tarde llegan por correo o en la aplicación.",
      "El historial de mantenimiento y los costes se quedan con la unidad, para ver qué se ha hecho.",
      "Las órdenes de trabajo van entre la empresa y el taller, para hablar del mismo trabajo.",
      "Menos llamadas: la situación ya está en la vista.",
    ],
    shopTitle: "Mantenimiento",
    shopKicker: "Vista del taller",
    shopLead: "Averías, trabajos e historial están en una lista, no en un montón de papeles.",
    shop: [
      "Los avisos de avería, con fotos, llegan aquí, no a un hilo de mensajes.",
      "Acuse la avería, márquela en curso y márquela reparada. El conductor recibe la noticia en la aplicación.",
      "Las órdenes de trabajo y el historial de la unidad viajan con el trabajo.",
      "Las pegatinas QR se imprimen desde la vista.",
    ],
    driverTitle: "Conductor",
    driverKicker: "Vista del conductor",
    driverLead: "El aviso sale desde la carretera. No hace falta contarlo otra vez en un chat.",
    driver: [
      "Escanee la pegatina de la unidad con la cámara del teléfono.",
      "Envíe un aviso de avería con una foto. Puede marcar si la unidad no debe salir a la carretera.",
      "Anote kilómetros y horas, también del remolque.",
      "Vea cómo avanza el aviso.",
    ],
    instructions: "Cada vista tiene sus propias indicaciones. El siguiente paso está ahí.",
    priceHeading: "Precio",
    priceLead: "Los usuarios son ilimitados. El precio sigue el tamaño de la flota. La calculadora muestra el precio del mes.",
    trial: "Prueba gratis de 30 días.",
    audience: "Para empresas. El registro pide un número de empresa finlandés (Y-tunnus).",
    cta: "Empezar la prueba de 30 días",
    login: "Abrir el servicio",
    contact: "Contacto",
    pricing: "Precios",
    terms: "Condiciones",
    privacy: "Privacidad",
    home: "Inicio",
    faqHeading: "Preguntas",
    faq: [
      { q: "¿Hay que instalar una aplicación?", a: "No. La empresa, el mantenimiento y los conductores abren el servicio en el navegador, en el teléfono o en el ordenador." },
      { q: "¿Qué pasa con los papeles y los hilos de WhatsApp?", a: "Averías, kilómetros, órdenes de trabajo y avisos de servicio están en el mismo sitio. Cada vista tiene sus indicaciones." },
      { q: "¿Cuánto cuesta?", a: "Los usuarios son ilimitados. El precio sigue la flota. La calculadora muestra el precio del mes, y la prueba es de 30 días." },
    ],
    backApps: "Todas las aplicaciones",
  },
  pt: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "O iqFleetSync mantém a empresa, a manutenção e os motoristas na mesma página. Revisões e reparações ficam em dia. No navegador, nada para instalar. Teste de 30 dias.",
    kicker: "Empresa, manutenção e motorista no mesmo sítio.",
    lead: "O iqFleetSync torna a conversa fácil e mantém as revisões e as reparações em dia. Os papéis e as conversas de WhatsApp podem ficar no porta-luvas. Abre-se no navegador, no telemóvel ou no computador. Nada para instalar.",
    browser: "O mesmo serviço serve a empresa, a manutenção e os motoristas. Cada pessoa abre a sua vista no navegador.",
    qr: "Os autocolantes QR vão para camiões, reboques, pás carregadoras, escavadoras e outras máquinas. A câmara do telemóvel abre a unidade certa.",
    viewsHeading: "Três vistas",
    companyTitle: "Empresa",
    companyKicker: "Vista do administrador",
    companyLead: "Aqui a frota fica junta e as revisões ficam em ordem.",
    company: [
      "Planos de revisão e prazos em quilómetros, horas ou data. Os lembretes do que vem e do que está atrasado chegam por e-mail ou na aplicação.",
      "O histórico de manutenção e os custos ficam com a unidade, para ver o que foi feito.",
      "As ordens de trabalho passam entre a empresa e a oficina, para falarem do mesmo trabalho.",
      "Menos telefonemas: a situação já está na vista.",
    ],
    shopTitle: "Manutenção",
    shopKicker: "Vista da oficina",
    shopLead: "Avarias, trabalhos e histórico estão numa lista, não numa pilha de papéis.",
    shop: [
      "Os avisos de avaria, com fotos, chegam aqui, não a um fio de mensagens.",
      "Confirme a avaria, marque-a em curso e marque-a reparada. O motorista recebe a novidade na aplicação.",
      "As ordens de trabalho e o histórico da unidade seguem com o trabalho.",
      "Os autocolantes QR imprimem-se a partir da vista.",
    ],
    driverTitle: "Motorista",
    driverKicker: "Vista do motorista",
    driverLead: "O aviso sai da berma da estrada. Não é preciso contá-lo outra vez numa conversa.",
    driver: [
      "Leia o autocolante da unidade com a câmara do telemóvel.",
      "Envie um aviso de avaria com uma foto. Pode marcar se a unidade não deve ir para a estrada.",
      "Registe quilómetros e horas, também do reboque.",
      "Vê como o aviso avança.",
    ],
    instructions: "Cada vista tem as suas indicações. O passo seguinte está ali.",
    priceHeading: "Preço",
    priceLead: "Os utilizadores são ilimitados. O preço segue o tamanho da frota. A calculadora mostra o preço do mês.",
    trial: "Teste grátis de 30 dias.",
    audience: "Para empresas. O registo pede um número de empresa finlandês (Y-tunnus).",
    cta: "Começar o teste de 30 dias",
    login: "Abrir o serviço",
    contact: "Contacto",
    pricing: "Preços",
    terms: "Condições",
    privacy: "Privacidade",
    home: "Início",
    faqHeading: "Perguntas",
    faq: [
      { q: "É preciso instalar uma aplicação?", a: "Não. A empresa, a manutenção e os motoristas abrem o serviço no navegador, no telemóvel ou no computador." },
      { q: "O que acontece aos papéis e às conversas de WhatsApp?", a: "Avarias, quilómetros, ordens de trabalho e lembretes de revisão ficam no mesmo sítio. Cada vista tem as suas indicações." },
      { q: "Quanto custa?", a: "Os utilizadores são ilimitados. O preço segue a frota. A calculadora mostra o preço do mês, e o teste é de 30 dias." },
    ],
    backApps: "Todas as aplicações",
  },
  it: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync tiene azienda, officina e conducenti sulla stessa pagina. Manutenzioni e riparazioni restano aggiornate. Nel browser, niente da installare. Prova di 30 giorni.",
    kicker: "Azienda, officina e conducente nello stesso posto.",
    lead: "iqFleetSync rende facili i contatti e tiene aggiornate manutenzioni e riparazioni. I foglietti e i fili di WhatsApp possono restare nel cassetto. Si apre nel browser, sul telefono o sul computer. Niente da installare.",
    browser: "Lo stesso servizio vale per l’azienda, l’officina e i conducenti. Ognuno apre la propria vista nel browser.",
    qr: "Gli adesivi QR vanno su camion, rimorchi, pale, escavatori e altre macchine. La fotocamera del telefono apre l’unità giusta.",
    viewsHeading: "Tre viste",
    companyTitle: "Azienda",
    companyKicker: "Vista dell’amministratore",
    companyLead: "Qui la flotta resta insieme e la manutenzione in ordine.",
    company: [
      "Piani di manutenzione e scadenze in chilometri, ore o data. I promemoria di ciò che arriva e di ciò che è in ritardo arrivano per e-mail o nell’app.",
      "Lo storico della manutenzione e i costi restano con l’unità, così si vede che cosa è stato fatto.",
      "Gli ordini di lavoro passano tra azienda e officina, per parlare dello stesso lavoro.",
      "Meno telefonate: la situazione è già nella vista.",
    ],
    shopTitle: "Officina",
    shopKicker: "Vista dell’officina",
    shopLead: "Difetti, lavori e storico stanno in un elenco, non in una pila di carte.",
    shop: [
      "Le segnalazioni di difetto, con le foto, arrivano qui, non in un filo di messaggi.",
      "Prendi in carico il difetto, segnalalo in corso e poi come riparato. Il conducente riceve la notizia nell’app.",
      "Gli ordini di lavoro e lo storico dell’unità seguono il lavoro.",
      "Gli adesivi QR si stampano dalla vista.",
    ],
    driverTitle: "Conducente",
    driverKicker: "Vista del conducente",
    driverLead: "La segnalazione parte dal bordo della strada. Non serve raccontarla di nuovo in una chat.",
    driver: [
      "Inquadra l’adesivo dell’unità con la fotocamera del telefono.",
      "Invia una segnalazione con una foto. Puoi indicare se l’unità non deve andare in strada.",
      "Inserisci chilometri e ore, anche del rimorchio.",
      "Vedi come procede la segnalazione.",
    ],
    instructions: "Ogni vista ha le sue indicazioni. Il passo successivo è lì.",
    priceHeading: "Prezzo",
    priceLead: "Gli utenti sono illimitati. Il prezzo segue la dimensione della flotta. Il calcolatore mostra il prezzo del mese.",
    trial: "Prova gratuita di 30 giorni.",
    audience: "Per imprese. La registrazione richiede un codice impresa finlandese (Y-tunnus).",
    cta: "Inizia la prova di 30 giorni",
    login: "Apri il servizio",
    contact: "Contatto",
    pricing: "Listino",
    terms: "Condizioni",
    privacy: "Privacy",
    home: "Home",
    faqHeading: "Domande",
    faq: [
      { q: "Qualcuno deve installare un’app?", a: "No. Azienda, officina e conducenti aprono il servizio nel browser, sul telefono o sul computer." },
      { q: "Che fine fanno i foglietti e i fili di WhatsApp?", a: "Difetti, chilometri, ordini di lavoro e promemoria di manutenzione stanno nello stesso posto. Ogni vista ha le sue indicazioni." },
      { q: "Quanto costa?", a: "Gli utenti sono illimitati. Il prezzo segue la flotta. Il calcolatore mostra il prezzo del mese, e la prova dura 30 giorni." },
    ],
    backApps: "Tutte le app",
  },
  pl: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync trzyma firmę, serwis i kierowców na tej samej stronie. Przeglądy i naprawy są na bieżąco. W przeglądarce, nic do instalacji. 30 dni próbnie.",
    kicker: "Firma, serwis i kierowca w jednym miejscu.",
    lead: "iqFleetSync ułatwia kontakt i trzyma przeglądy oraz naprawy na bieżąco. Kartki i wątki WhatsApp mogą zostać w schowku. Otwiera się w przeglądarce, w telefonie lub komputerze. Nic do instalacji.",
    browser: "Ta sama usługa służy firmie, serwisowi i kierowcom. Każdy otwiera swój widok w przeglądarce.",
    qr: "Naklejki QR trafiają na ciężarówki, naczepy, ładowarki, koparki i inne maszyny. Aparat telefonu otwiera właściwą jednostkę.",
    viewsHeading: "Trzy widoki",
    companyTitle: "Firma",
    companyKicker: "Widok administratora",
    companyLead: "Tutaj flota jest razem, a przeglądy w porządku.",
    company: [
      "Plany serwisowe i terminy w kilometrach, godzinach lub dacie. Przypomnienia o tym, co nadchodzi, i o tym, co jest spóźnione, przychodzą e-mailem lub w aplikacji.",
      "Historia utrzymania i koszty zostają przy jednostce, więc widać, co zostało zrobione.",
      "Zlecenia pracy idą między firmą a warsztatem, więc mowa o tej samej robocie.",
      "Mniej telefonów: sytuacja jest już w widoku.",
    ],
    shopTitle: "Serwis",
    shopKicker: "Widok warsztatu",
    shopLead: "Usterki, roboty i historia są na jednej liście, nie na stercie papieru.",
    shop: [
      "Zgłoszenia usterek ze zdjęciami trafiają tutaj, nie do wątku wiadomości.",
      "Potwierdź usterkę, oznacz ją jako w toku i jako naprawioną. Kierowca dostaje wiadomość w aplikacji.",
      "Zlecenia i historia jednostki idą razem z robotą.",
      "Naklejki QR można wydrukować z widoku.",
    ],
    driverTitle: "Kierowca",
    driverKicker: "Widok kierowcy",
    driverLead: "Zgłoszenie wychodzi z drogi. Nie trzeba opowiadać go jeszcze raz na czacie.",
    driver: [
      "Zeskanuj naklejkę jednostki aparatem telefonu.",
      "Wyślij zgłoszenie usterki ze zdjęciem. Możesz oznaczyć, że jednostka nie powinna wyjechać.",
      "Wpisz kilometry i godziny, także naczepy.",
      "Widzisz, jak zgłoszenie idzie dalej.",
    ],
    instructions: "Każdy widok ma własne wskazówki. Następny krok jest na miejscu.",
    priceHeading: "Cena",
    priceLead: "Liczba użytkowników jest nieograniczona. Cena wynika z wielkości floty. Kalkulator pokazuje cenę miesiąca.",
    trial: "30 dni bezpłatnie.",
    audience: "Dla firm. Rejestracja wymaga fińskiego numeru firmy (Y-tunnus).",
    cta: "Zacznij 30 dni próbnie",
    login: "Otwórz usługę",
    contact: "Kontakt",
    pricing: "Cennik",
    terms: "Warunki",
    privacy: "Prywatność",
    home: "Strona główna",
    faqHeading: "Pytania",
    faq: [
      { q: "Czy ktoś musi zainstalować aplikację?", a: "Nie. Firma, serwis i kierowcy otwierają usługę w przeglądarce, w telefonie lub komputerze." },
      { q: "Co z kartkami i wątkami WhatsApp?", a: "Usterki, kilometry, zlecenia i przypomnienia serwisowe są w jednym miejscu. Każdy widok ma własne wskazówki." },
      { q: "Ile to kosztuje?", a: "Liczba użytkowników jest nieograniczona. Cena wynika z floty. Kalkulator pokazuje cenę miesiąca, a próba trwa 30 dni." },
    ],
    backApps: "Wszystkie aplikacje",
  },
  cs: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync drží firmu, údržbu a řidiče na jedné stránce. Servisy a opravy zůstávají aktuální. V prohlížeči, nic k instalaci. 30 dní na zkoušku.",
    kicker: "Firma, údržba a řidič na jednom místě.",
    lead: "iqFleetSync usnadňuje domluvu a drží servisy a opravy aktuální. Papírky a vlákna WhatsApp mohou zůstat v přihrádce. Otevře se v prohlížeči na telefonu nebo počítači. Nic k instalaci.",
    browser: "Stejná služba slouží firmě, údržbě i řidičům. Každý si otevře svůj pohled v prohlížeči.",
    qr: "QR štítky patří na nákladní auta, návěsy, nakladače, bagry a další stroje. Fotoaparát telefonu otevře správnou jednotku.",
    viewsHeading: "Tři pohledy",
    companyTitle: "Firma",
    companyKicker: "Pohled správce",
    companyLead: "Tady držíte vozový park pohromadě a servisy v pořádku.",
    company: [
      "Servisní plány a termíny v kilometrech, hodinách nebo datu. Připomínky toho, co přichází, a toho, co je po termínu, přijdou e-mailem nebo v aplikaci.",
      "Historie údržby a náklady zůstávají u jednotky, takže je vidět, co se udělalo.",
      "Pracovní příkazy jdou mezi firmou a dílnou, takže mluvíte o stejné práci.",
      "Méně telefonátů: stav už je v pohledu.",
    ],
    shopTitle: "Údržba",
    shopKicker: "Pohled dílny",
    shopLead: "Závady, práce a historie jsou v jednom seznamu, ne na hromadě papírů.",
    shop: [
      "Hlášení závad s fotkami přijdou sem, ne do vlákna zpráv.",
      "Potvrďte závadu, označte ji jako rozpracovanou a jako opravenou. Řidič dostane zprávu v aplikaci.",
      "Pracovní příkazy a historie jednotky jdou s prací.",
      "QR štítky se tisknou z pohledu.",
    ],
    driverTitle: "Řidič",
    driverKicker: "Pohled řidiče",
    driverLead: "Hlášení odchází od silnice. Není třeba ho znovu vyprávět v chatu.",
    driver: [
      "Naskenujte štítek jednotky fotoaparátem telefonu.",
      "Pošlete hlášení závady s fotkou. Můžete označit, že jednotka nemá vyjet.",
      "Zapište kilometry a hodiny, i u návěsu.",
      "Vidíte, jak hlášení pokračuje.",
    ],
    instructions: "Každý pohled má vlastní pokyny. Další krok je na místě.",
    priceHeading: "Cena",
    priceLead: "Počet uživatelů je neomezený. Cena se řídí velikostí parku. Kalkulačka ukáže cenu za měsíc.",
    trial: "30 dní zdarma.",
    audience: "Pro firmy. Registrace vyžaduje finské IČ (Y-tunnus).",
    cta: "Začít 30 dní na zkoušku",
    login: "Otevřít službu",
    contact: "Kontakt",
    pricing: "Ceník",
    terms: "Podmínky",
    privacy: "Soukromí",
    home: "Domů",
    faqHeading: "Otázky",
    faq: [
      { q: "Musí někdo instalovat aplikaci?", a: "Ne. Firma, údržba i řidiči otevírají službu v prohlížeči na telefonu nebo počítači." },
      { q: "Co s papírky a vlákny WhatsApp?", a: "Závady, kilometry, pracovní příkazy a servisní připomínky jsou na jednom místě. Každý pohled má vlastní pokyny." },
      { q: "Kolik to stojí?", a: "Počet uživatelů je neomezený. Cena se řídí parkem. Kalkulačka ukáže cenu za měsíc a zkouška trvá 30 dní." },
    ],
    backApps: "Všechny aplikace",
  },
  ja: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSyncは会社、整備、ドライバーを同じ場所に置きます。点検と修理が最新のままです。ブラウザで、インストール不要。30日間の試用。",
    kicker: "会社、整備、ドライバーが同じ場所に。",
    lead: "iqFleetSyncは連絡をかんたんにして、点検と修理を最新に保ちます。紙のメモとWhatsAppのやりとりはグローブボックスに置いたままで大丈夫です。電話でもパソコンでも、ブラウザで開きます。インストールは不要です。",
    browser: "同じサービスを、会社、整備、ドライバーが使います。それぞれ自分の画面をブラウザで開きます。",
    qr: "QRシールはトラック、トレーラー、ホイールローダー、ショベル、その他の機械に貼ります。スマホのカメラで、その車両が開きます。",
    viewsHeading: "3つの画面",
    companyTitle: "会社",
    companyKicker: "管理者の画面",
    companyLead: "車両の様子をひとつにまとめ、点検を整えます。",
    company: [
      "走行距離、時間、または日付での点検計画と期限。近づいているものと遅れているものの通知が、メールかアプリに届きます。",
      "整備の履歴と費用が車両に残るので、何をしたかが見えます。",
      "作業指示が会社と整備の間を行き、同じ仕事の話ができます。",
      "電話が減ります。状況はすでに画面にあります。",
    ],
    shopTitle: "整備",
    shopKicker: "整備の画面",
    shopLead: "不具合、仕事、履歴がひとつのリストにあります。紙の山ではありません。",
    shop: [
      "写真つきの不具合報告は、メッセージのやりとりではなく、ここに届きます。",
      "不具合を受け取り、作業中にし、直ったことにします。ドライバーにはアプリで知らせます。",
      "作業指示と車両の履歴が、仕事と一緒に動きます。",
      "QRシールはこの画面から印刷できます。",
    ],
    driverTitle: "ドライバー",
    driverKicker: "ドライバーの画面",
    driverLead: "報告はその場から送れます。チャットでもう一度説明する必要はありません。",
    driver: [
      "スマホのカメラで車両のシールを読み取ります。",
      "写真つきで不具合を送ります。道路に出すべきでないときも印をつけられます。",
      "キロと時間を記録します。トレーラーも含みます。",
      "報告がどこまで進んだかが見えます。",
    ],
    instructions: "どの画面にも案内があります。次にすることをその場で確認できます。",
    priceHeading: "料金",
    priceLead: "ユーザー数に上限はありません。料金は車両の数に沿います。計算機が月額を表示します。",
    trial: "30日間の無料試用。",
    audience: "事業者向けです。登録にはフィンランドの事業者番号（Y-tunnus）が必要です。",
    cta: "30日間の試用を始める",
    login: "サービスを開く",
    contact: "問い合わせ",
    pricing: "料金表",
    terms: "利用条件",
    privacy: "プライバシー",
    home: "ホーム",
    faqHeading: "質問",
    faq: [
      { q: "アプリのインストールは必要ですか？", a: "不要です。会社、整備、ドライバーは、電話かパソコンのブラウザで開きます。" },
      { q: "紙のメモとWhatsAppのやりとりはどうなりますか？", a: "不具合、キロ、作業指示、点検の通知が同じ場所にあります。どの画面にも案内があります。" },
      { q: "料金はいくらですか？", a: "ユーザー数に上限はありません。料金は車両に沿います。計算機が月額を表示し、試用は30日です。" },
    ],
    backApps: "すべてのアプリ",
  },
  ko: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync는 회사, 정비, 운전자를 한곳에 둡니다. 점검과 수리가 최신으로 남습니다. 브라우저에서, 설치 없음. 30일 체험.",
    kicker: "회사, 정비, 운전자가 한곳에.",
    lead: "iqFleetSync는 연락을 쉽게 하고 점검과 수리를 최신으로 유지합니다. 종이 메모와 WhatsApp 대화는 글러브박스에 두어도 됩니다. 전화나 컴퓨터의 브라우저에서 엽니다. 설치할 것이 없습니다.",
    browser: "같은 서비스를 회사, 정비, 운전자가 씁니다. 각자 자기 화면을 브라우저에서 엽니다.",
    qr: "QR 스티커는 트럭, 트레일러, 휠로더, 굴착기, 그 밖의 장비에 붙입니다. 휴대폰 카메라가 그 장비를 엽니다.",
    viewsHeading: "세 가지 화면",
    companyTitle: "회사",
    companyKicker: "관리자 화면",
    companyLead: "여기서 장비 상황을 모아 두고 점검을 정리합니다.",
    company: [
      "킬로미터, 시간 또는 날짜로 된 점검 계획과 기한. 다가오는 일과 늦은 일의 알림이 이메일이나 앱으로 옵니다.",
      "정비 이력과 비용이 장비에 남아, 무엇을 했는지 보입니다.",
      "작업 지시가 회사와 정비 사이를 오가, 같은 일을 이야기합니다.",
      "전화가 줄어듭니다. 상황이 이미 화면에 있습니다.",
    ],
    shopTitle: "정비",
    shopKicker: "정비 화면",
    shopLead: "고장, 일, 이력이 한 목록에 있습니다. 종이 더미가 아닙니다.",
    shop: [
      "사진이 있는 고장 신고는 메시지 대화가 아니라 여기로 옵니다.",
      "고장을 확인하고, 진행 중으로, 그리고 수리됨으로 표시합니다. 운전자는 앱에서 소식을 받습니다.",
      "작업 지시와 장비 이력이 일과 함께 이동합니다.",
      "QR 스티커는 이 화면에서 인쇄합니다.",
    ],
    driverTitle: "운전자",
    driverKicker: "운전자 화면",
    driverLead: "신고는 길가에서 나갑니다. 채팅에서 다시 설명할 필요가 없습니다.",
    driver: [
      "휴대폰 카메라로 장비 스티커를 읽습니다.",
      "사진과 함께 고장을 보냅니다. 도로에 나가면 안 될 때도 표시할 수 있습니다.",
      "킬로미터와 시간을 적습니다. 트레일러도 포함합니다.",
      "신고가 어떻게 진행되는지 봅니다.",
    ],
    instructions: "각 화면에는 안내가 있습니다. 다음에 할 일이 그 자리에 있습니다.",
    priceHeading: "요금",
    priceLead: "사용자 수에는 제한이 없습니다. 요금은 장비 수에 따릅니다. 계산기가 월 요금을 보여 줍니다.",
    trial: "30일 무료 체험.",
    audience: "사업자용입니다. 가입에는 핀란드 사업자 번호(Y-tunnus)가 필요합니다.",
    cta: "30일 체험 시작",
    login: "서비스 열기",
    contact: "문의",
    pricing: "요금표",
    terms: "약관",
    privacy: "개인정보",
    home: "홈",
    faqHeading: "질문",
    faq: [
      { q: "앱을 설치해야 하나요?", a: "아니요. 회사, 정비, 운전자는 전화나 컴퓨터의 브라우저에서 엽니다." },
      { q: "종이 메모와 WhatsApp 대화는 어떻게 되나요?", a: "고장, 킬로미터, 작업 지시, 점검 알림이 한곳에 있습니다. 각 화면에는 안내가 있습니다." },
      { q: "요금은 얼마인가요?", a: "사용자 수에는 제한이 없습니다. 요금은 장비에 따릅니다. 계산기가 월 요금을 보여 주고, 체험은 30일입니다." },
    ],
    backApps: "모든 앱",
  },
  zh: {
    metaTitle: "iqFleetSync | IQSoftCore",
    metaDescription: "iqFleetSync 让公司、维修和驾驶员在同一页上。保养和修理保持最新。在浏览器里，无需安装。30 天试用。",
    kicker: "公司、维修和驾驶员在同一处。",
    lead: "iqFleetSync 让沟通变简单，并让保养和修理保持最新。纸条和 WhatsApp 对话可以留在手套箱里。用手机或电脑的浏览器打开。无需安装。",
    browser: "公司、维修和驾驶员用的是同一个服务。每个人在浏览器里打开自己的界面。",
    qr: "二维码贴在卡车、挂车、轮式装载机、挖掘机和其他设备上。手机相机打开对应的设备。",
    viewsHeading: "三个界面",
    companyTitle: "公司",
    companyKicker: "管理员界面",
    companyLead: "在这里把车队放在一起，把保养安排好。",
    company: [
      "按公里、小时或日期的保养计划和期限。即将到期和已经逾期的提醒通过电子邮件或应用送达。",
      "维修记录和费用留在设备上，看得出做过什么。",
      "工单在公司和维修之间传递，谈的是同一件工作。",
      "少打电话：情况已经在界面里。",
    ],
    shopTitle: "维修",
    shopKicker: "维修界面",
    shopLead: "缺陷、工作和记录在一张清单里，不在一摞纸上。",
    shop: [
      "带照片的缺陷报告来到这里，不进消息串。",
      "确认缺陷，标为进行中，再标为已修好。驾驶员在应用里收到消息。",
      "工单和设备记录跟着这件工作走。",
      "二维码贴可以从这个界面打印。",
    ],
    driverTitle: "驾驶员",
    driverKicker: "驾驶员界面",
    driverLead: "报告从路边发出。不必在聊天里再讲一遍。",
    driver: [
      "用手机相机扫描设备上的贴。",
      "带照片发送缺陷报告。如果设备不该上路，可以标明。",
      "填写公里和小时，也包括挂车。",
      "看得到报告进展到哪一步。",
    ],
    instructions: "每个界面都有自己的说明。下一步就在那里。",
    priceHeading: "价格",
    priceLead: "用户数量不限。价格随车队规模。计算器显示每月价格。",
    trial: "30 天免费试用。",
    audience: "面向企业。注册需要芬兰企业编号（Y-tunnus）。",
    cta: "开始 30 天试用",
    login: "打开服务",
    contact: "联系",
    pricing: "价格表",
    terms: "条款",
    privacy: "隐私说明",
    home: "首页",
    faqHeading: "问题",
    faq: [
      { q: "需要安装应用吗？", a: "不需要。公司、维修和驾驶员在手机或电脑的浏览器里打开。" },
      { q: "纸条和 WhatsApp 对话怎么办？", a: "缺陷、公里、工单和保养提醒在同一个地方。每个界面都有说明。" },
      { q: "费用是多少？", a: "用户数量不限。价格随车队。计算器显示每月价格，试用为 30 天。" },
    ],
    backApps: "全部应用",
  },
};

const FLEETSYNC_HELP = {
  fi: {
    label: "Ohjekeskus",
    lead: "Lyhyet ohjevideot ovat ohjekeskuksessa.",
  },
  en: {
    label: "Help center",
    lead: "Short how-to videos are in the help center.",
  },
  sv: {
    label: "Hjälpcenter",
    lead: "Korta instruktionsvideor finns i hjälpcentret.",
  },
  no: {
    label: "Hjelpesenter",
    lead: "Korte instruksjonsvideoer ligger i hjelpesenteret.",
  },
  da: {
    label: "Hjælpecenter",
    lead: "Korte vejledningsvideoer ligger i hjælpecentret.",
  },
  de: {
    label: "Hilfe",
    lead: "Kurze Anleitungsvideos stehen in der Hilfe.",
  },
  es: {
    label: "Ayuda",
    lead: "Los vídeos cortos de ayuda están en la ayuda.",
  },
  it: {
    label: "Guida",
    lead: "I video brevi sono nella guida.",
  },
  ja: {
    label: "ヘルプ",
    lead: "短い使い方動画はヘルプにあります。",
  },
  ko: {
    label: "도움말",
    lead: "짧은 안내 영상은 도움말에 있습니다.",
  },
  fr: {
    label: "Aide",
    lead: "De courtes vidéos d’aide sont dans l’aide.",
  },
  pt: {
    label: "Ajuda",
    lead: "Vídeos curtos de ajuda estão na ajuda.",
  },
  nl: {
    label: "Help",
    lead: "Korte instructievideo’s staan bij Help.",
  },
  pl: {
    label: "Pomoc",
    lead: "Krótkie filmy pomocy są w pomocy.",
  },
  cs: {
    label: "Nápověda",
    lead: "Krátká návodová videa jsou v nápovědě.",
  },
  zh: {
    label: "帮助",
    lead: "简短的使用视频在帮助里。",
  },
};

function escapeFleetHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderFleetSyncPage(lang) {
  const root = document.getElementById("fleetsync-root");
  if (!root) return;
  const page = FLEETSYNC_PAGE[lang] || FLEETSYNC_PAGE.en;
  const help = FLEETSYNC_HELP[lang] || FLEETSYNC_HELP.en;

  const titleEl = document.querySelector("title");
  if (titleEl) titleEl.textContent = page.metaTitle;
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc) metaDesc.setAttribute("content", page.metaDescription);

  const list = (items) => `<ul>${items.map((item) => `<li>${escapeFleetHtml(item)}</li>`).join("")}</ul>`;
  const view = (title, kicker, lead, items) => `<section class="view-block">
      <h2>${escapeFleetHtml(title)}</h2>
      <p class="view-kicker">${escapeFleetHtml(kicker)}</p>
      <p>${escapeFleetHtml(lead)}</p>
      ${list(items)}
    </section>`;
  const faq = (page.faq || [])
    .map((item) => `<h3>${escapeFleetHtml(item.q)}</h3><p>${escapeFleetHtml(item.a)}</p>`)
    .join("");

  const savedCounts = {};
  ["vehicles", "machines", "trailers", "attachments"].forEach((key) => {
    const input = document.getElementById(`fleet-calc-${key}`);
    if (input) savedCounts[key] = input.value;
  });

  root.innerHTML = `<h1>iqFleetSync</h1>
    <p class="app-short">${escapeFleetHtml(page.kicker)}</p>
    <p>${escapeFleetHtml(page.lead)}</p>
    <p>${escapeFleetHtml(page.browser)}</p>
    <p>${escapeFleetHtml(page.qr)}</p>
    <h2>${escapeFleetHtml(page.viewsHeading)}</h2>
    ${view(page.companyTitle, page.companyKicker, page.companyLead, page.company)}
    ${view(page.shopTitle, page.shopKicker, page.shopLead, page.shop)}
    ${view(page.driverTitle, page.driverKicker, page.driverLead, page.driver)}
    <p>${escapeFleetHtml(page.instructions)}</p>
    <p><a href="ohjekeskus.html">${escapeFleetHtml(help.lead)}</a></p>
    <h2>${escapeFleetHtml(page.priceHeading)}</h2>
    <p>${escapeFleetHtml(page.priceLead)}</p>
    <p>${escapeFleetHtml(page.trial)}</p>
    <div id="fleet-calc"></div>
    <p>${escapeFleetHtml(page.audience)}</p>
    <div class="app-actions">
      <a class="btn btn-primary" href="https://fleetsync.iqsoftcore.fi/rekisteroidy">${escapeFleetHtml(page.cta)}</a>
      <a class="btn btn-ghost" href="https://fleetsync.iqsoftcore.fi/login">${escapeFleetHtml(page.login)}</a>
      <a class="btn btn-ghost" href="index.html#contact">${escapeFleetHtml(page.contact)}</a>
    </div>
    <h2>${escapeFleetHtml(page.faqHeading)}</h2>
    ${faq}
    <p class="policy-nav">
      <a class="btn btn-ghost" href="ohjekeskus.html">${escapeFleetHtml(help.label)}</a>
      <a class="btn btn-ghost" href="hinnasto.html">${escapeFleetHtml(page.pricing)}</a>
      <a class="btn btn-ghost" href="kayttoehdot.html">${escapeFleetHtml(page.terms)}</a>
      <a class="btn btn-ghost" href="privacy.html#iqfleetsync">${escapeFleetHtml(page.privacy)}</a>
      <a class="btn btn-ghost" href="apps.html">${escapeFleetHtml(page.backApps)}</a>
      <a class="btn btn-ghost" href="index.html">${escapeFleetHtml(page.home)}</a>
    </p>`;

  if (typeof mountFleetSyncCalculator === "function") {
    mountFleetSyncCalculator(document.getElementById("fleet-calc"), lang, savedCounts);
  }
}
