/**
 * Pricing page. iqFleetSync prices are the ones supplied for this site.
 * Tuntilappu and iqRallyNote have no published price in the repo.
 */
const PRICE_LOCALES = {
  fi: "fi-FI",
  en: "en-GB",
  sv: "sv-SE",
  no: "nb-NO",
  da: "da-DK",
  de: "de-DE",
  nl: "nl-NL",
  fr: "fr-FR",
  es: "es-ES",
  pt: "pt-BR",
  it: "it-IT",
  pl: "pl-PL",
  cs: "cs-CZ",
  ja: "ja-JP",
  ko: "ko-KR",
  zh: "zh-CN",
};

const PRICING_PAGE = {
  fi: {
    metaTitle: "Hinnasto | IQSoftCore",
    metaDescription: "iqFleetSync-hinnasto. Hinnat ovat yritysasiakkaille ja alv 0 %. Arvonlisävero lisätään laskulle voimassa olevan verokannan mukaan. Perusmaksu ja porrastettu yksikköhinta.",
    title: "Hinnasto",
    intro: "iqFleetSync hinnoitellaan yrityksen perusmaksulla sekä ajoneuvoilla, työkoneilla, perävaunuilla ja laitteilla. Hinnat ovat yritysasiakkaille ja alv 0 %. Arvonlisävero lisätään laskulle voimassa olevan verokannan mukaan.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Perusmaksu",
    baseValue: "10,00 € / kuukausi / yritys",
    unitHeading: "Hintaportaat kuukautta kohden",
    unitNote: "Hinta on porrastettu: ensimmäiset 15 yksikköä ensimmäisellä hinnalla ja seuraavat yksiköt seuraavalla hinnalla.",
    colRange: "Yksiköt",
    colVehicle: "Ajoneuvo tai työkone / kk",
    colTrailer: "Perävaunu / kk",
    tiers: [
      ["1–15", "1,50 €", "0,75 €"],
      ["16–50", "1,30 €", "0,65 €"],
      ["51–100", "1,10 €", "0,55 €"],
      ["yli 100", "0,90 €", "0,45 €"],
    ],
    trailer: "Perävaunu on puoli yksikköä siinä portaassa, johon se osuu, joten se maksaa puolet saman portaan ajoneuvohinnasta. Ajoneuvot ja työkoneet täyttävät portaat ensin, ajoneuvot ennen työkoneita.",
    mounted: "Laite, esimerkiksi kauhanpyörittäjä, hydraulivasara tai harjalaite, maksaa 0 €.",
    attachmentsLine: "Laitteet: 0,00 €. Niistä ei tule maksua, eikä niitä lasketa yksiköihin.",
    users: "Käyttäjiä voi olla rajattomasti. Käyttäjämäärästä ei veloiteta.",
    peak: "Lasku perustuu kalenterikuukauden suurimpaan yksikkömäärään.",
    trial: "30 päivän ilmainen kokeilu. Laskuri näyttää hinnan kokeilun jälkeen.",
    archived: "Arkistoitua yksikköä ei laskuteta. Sen historia ja laskut säilyvät. Älä laske arkistoituja yksiköitä laskuriin.",
    invoice: "Maksu on kortilla Stripen kautta. Lasku on kuukausittainen ja jälkikäteen.",
    readOnly: "Jos kokeilu päättyy eikä maksua ole tehty, tai jos lasku on maksamatta 7 päivää eräpäivän jälkeen, tili on vain luku -tilassa. Palvelun voi irtisanoa milloin tahansa.",
    cta: "Kokeile ilmaiseksi 30 päivää",
    terms: "Käyttöehdot",
    calcTitle: "Kuukausihinnan laskuri",
    calcIntro: "Syötä ajoneuvot, työkoneet, perävaunut ja laitteet erikseen. Jokainen rivi näyttää, mistä summa tulee.",
    vehiclesLabel: "Ajoneuvot",
    vehiclesHint: "esimerkiksi kuorma-autot",
    machinesLabel: "Työkoneet",
    machinesHint: "esimerkiksi kaivinkoneet ja pyöräkuormaajat",
    attachmentsLabel: "Laitteet",
    attachmentsHint: "esimerkiksi kauhanpyörittäjä, hydraulivasara tai harjalaite",
    trailersLabel: "Perävaunut",
    trailersHint: "puoli yksikköä",
    vehiclesMath: "Ajoneuvot",
    machinesMath: "Työkoneet",
    attachmentsMath: "Laitteet",
    freeNote: "ei maksua",
    trailersMath: "Perävaunut × 0,5",
    trailersHalf: "Perävaunut (puoli yksikköä)",
    totalWord: "Yhteensä",
    perMonth: "/kk",
    examplesTitle: "Esimerkkejä",
    billingTitle: "Laskutus",
    billingNote: "Kuukauden hinta perustuu kalenterikuukauden suurimpaan yksikkömäärään. Ajoneuvot ja työkoneet ovat kokonaisia yksiköitä ja täyttävät portaat ensin. Perävaunu on puoli yksikköä omassa portaassaan. Laite on 0 €. Tarkemmin:",
    billingLink: "Käyttöehdot",
    example5: "5 ajoneuvoa",
    example20: "20 ajoneuvoa ja 5 perävaunua",
    exampleMix: "10 ajoneuvoa, 8 työkoneetta, 5 perävaunua ja 4 laitetta",
    totalUnits: "Yksiköitä yhteensä",
    unitsSum: "Yksiköiden hinta",
    baseLine: "Perusmaksu",
    monthTotal: "Kuukausihinta",
    vatNote: "Hinnat alv 0 %. Arvonlisävero lisätään laskulle voimassa olevan verokannan mukaan.",
    audience: "Yritysasiakkaille",
    otherTitle: "Muut tuotteet",
    otherIntro: "Julkaistua hintaa ei ole. Kun kuluttajahinta julkaistaan, se näytetään arvonlisäverollisena.",
    contact: "Ota yhteyttä",
    others: [
      ["tuntilappu.html", "Tuntilappu"],
      ["iqrallynote.html", "iqRallyNote"],
    ],
  },
  en: {
    metaTitle: "Pricing | IQSoftCore",
    metaDescription: "iqFleetSync pricing for business customers. Prices are VAT 0%. Value added tax is added on the invoice at the rate in force. A base fee plus a graduated per-unit price.",
    title: "Pricing",
    intro: "iqFleetSync is priced with a company base fee plus vehicles, work machines, trailers, and attachments. Prices are for business customers and are VAT 0%. Value added tax is added on the invoice at the rate in force.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Base fee",
    baseValue: "10.00 € / month / company",
    unitHeading: "Price tiers per month",
    unitNote: "The tiers are graduated: the first 15 units use the first price, and the next units use the next price.",
    colRange: "Units",
    colVehicle: "Vehicle or work machine / month",
    colTrailer: "Trailer / month",
    tiers: [
      ["1–15", "1.50 €", "0.75 €"],
      ["16–50", "1.30 €", "0.65 €"],
      ["51–100", "1.10 €", "0.55 €"],
      ["over 100", "0.90 €", "0.45 €"],
    ],
    trailer: "A trailer is half a unit in the tier it falls into, so it costs half the vehicle price of that tier. Vehicles and work machines fill the tiers first, vehicles before work machines.",
    mounted: "An attachment, such as a tiltrotator, a hydraulic breaker, or a sweeper, costs 0 €.",
    attachmentsLine: "Attachments: 0.00 €. There is no charge, and they are not counted as units.",
    users: "Users are unlimited. There is no charge per user.",
    peak: "The bill uses the highest unit count in that calendar month.",
    trial: "30-day free trial. The calculator shows the price after the trial.",
    archived: "An archived unit is not billed. Its history and invoices stay. Do not count archived units in the calculator.",
    invoice: "The charge is a card payment through Stripe. The invoice is monthly, in arrears.",
    readOnly: "If the trial ends with no payment, or if an invoice is unpaid 7 days after the due date, the account is read-only. You can cancel at any time.",
    cta: "Try free for 30 days",
    terms: "Terms of use",
    calcTitle: "Monthly price calculator",
    calcIntro: "Enter vehicles, work machines, trailers, and attachments separately. Each line shows where that part of the price comes from.",
    vehiclesLabel: "Vehicles",
    vehiclesHint: "for example trucks",
    machinesLabel: "Work machines",
    machinesHint: "for example excavators and wheel loaders",
    attachmentsLabel: "Attachments",
    attachmentsHint: "for example a tiltrotator, hydraulic breaker, or sweeper",
    trailersLabel: "Trailers",
    trailersHint: "half a unit",
    vehiclesMath: "Vehicles",
    machinesMath: "Work machines",
    attachmentsMath: "Attachments",
    freeNote: "no charge",
    trailersMath: "Trailers × 0.5",
    trailersHalf: "Trailers (half a unit)",
    totalWord: "Total",
    perMonth: "/month",
    examplesTitle: "Examples",
    billingTitle: "Billing",
    billingNote: "The monthly price uses the highest unit count in that calendar month. Vehicles and work machines are full units and fill the tiers first. A trailer is half a unit in its own tier. An attachment is 0 €. See the terms:",
    billingLink: "Terms of use",
    example5: "5 vehicles",
    example20: "20 vehicles and 5 trailers",
    exampleMix: "10 vehicles, 8 work machines, 5 trailers and 4 attachments",
    totalUnits: "Units in total",
    unitsSum: "Price of the units",
    baseLine: "Base fee",
    monthTotal: "Monthly price",
    vatNote: "Prices are VAT 0%. Value added tax is added on the invoice at the rate in force.",
    audience: "For business customers",
    otherTitle: "Other products",
    otherIntro: "There is no published price. A published consumer price is shown including VAT.",
    contact: "Get in touch",
    others: [
      ["tuntilappu.html", "Tuntilappu"],
      ["iqrallynote.html", "iqRallyNote"],
    ],
  },
  sv: {
    metaTitle: "Priser | IQSoftCore",
    metaDescription: "Pris för iqFleetSync för företagskunder. Priserna är moms 0 %. Mervärdesskatt läggs till på fakturan enligt den gällande skattesatsen. Grundavgift och stegvis enhetspris.",
    title: "Priser",
    intro: "iqFleetSync prissätts med en grundavgift per företag samt fordon, arbetsmaskiner, släp och redskap. Priserna gäller företagskunder och är moms 0 %. Mervärdesskatt läggs till på fakturan enligt den gällande skattesatsen.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Grundavgift",
    baseValue: "10,00 € / månad / företag",
    unitHeading: "Prissteg per månad",
    unitNote: "Stegen är progressiva: de första 15 enheterna har det första priset, och följande enheter har nästa pris.",
    colRange: "Enheter",
    colVehicle: "Fordon eller arbetsmaskin / mån",
    colTrailer: "Släp / mån",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["över 100", "0,90 €", "0,45 €"]],
    trailer: "Ett släp är en halv enhet i det steg det hamnar i, så det kostar hälften av fordonspriset i det steget. Fordon och arbetsmaskiner fyller stegen först, fordon före arbetsmaskiner.",
    mounted: "Ett redskap, till exempel en tiltrotator, en hydraulhammare eller en sopvals, kostar 0 €.",
    attachmentsLine: "Redskap: 0,00 €. De kostar inget och räknas inte som enheter.",
    users: "Antalet användare är obegränsat. Det finns ingen avgift per användare.",
    peak: "Fakturan utgår från det högsta enhetsantalet under kalendermånaden.",
    trial: "30 dagars gratis provperiod. Räknaren visar priset efter provperioden.",
    archived: "En arkiverad enhet faktureras inte. Dess historik och fakturor behålls. Räkna inte med arkiverade enheter i räknaren.",
    invoice: "Avgiften är en kortbetalning via Stripe. Fakturan är månadsvis i efterskott.",
    readOnly: "Om provperioden tar slut utan betalning, eller om en faktura är obetald 7 dagar efter förfallodagen, är kontot skrivskyddat. Tjänsten kan sägas upp när som helst.",
    cta: "Prova gratis i 30 dagar",
    terms: "Användarvillkor",
    calcTitle: "Räknare för månadspris",
    calcIntro: "Ange fordon, arbetsmaskiner, släp och redskap var för sig. Varje rad visar var den delen av priset kommer ifrån.",
    vehiclesLabel: "Fordon",
    vehiclesHint: "till exempel lastbilar",
    machinesLabel: "Arbetsmaskiner",
    machinesHint: "till exempel grävmaskiner och hjullastare",
    attachmentsLabel: "Redskap",
    attachmentsHint: "till exempel tiltrotator, hydraulhammare eller sopvals",
    trailersLabel: "Släp",
    trailersHint: "en halv enhet",
    vehiclesMath: "Fordon",
    machinesMath: "Arbetsmaskiner",
    attachmentsMath: "Redskap",
    freeNote: "ingen avgift",
    trailersMath: "Släp × 0,5",
    trailersHalf: "Släp (en halv enhet)",
    totalWord: "Totalt",
    perMonth: "/mån",
    examplesTitle: "Exempel",
    billingTitle: "Fakturering",
    billingNote: "Månadspriset utgår från det högsta enhetsantalet under kalendermånaden. Fordon och arbetsmaskiner är hela enheter och fyller stegen först. Ett släp är en halv enhet i sitt steg. Ett redskap är 0 €. Se villkoren:",
    billingLink: "Användarvillkor",
    example5: "5 fordon",
    example20: "20 fordon och 5 släp",
    exampleMix: "10 fordon, 8 arbetsmaskiner, 5 släp och 4 redskap",
    totalUnits: "Enheter totalt",
    unitsSum: "Pris för enheterna",
    baseLine: "Grundavgift",
    monthTotal: "Månadspris",
    vatNote: "Priserna är moms 0 %. Mervärdesskatt läggs till på fakturan enligt den gällande skattesatsen.",
    audience: "För företagskunder",
    otherTitle: "Övriga produkter",
    otherIntro: "Det finns inget publicerat pris. Ett publicerat konsumentpris visas inklusive moms.",
    contact: "Kontakta oss",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  no: {
    metaTitle: "Priser | IQSoftCore",
    metaDescription: "Pris for iqFleetSync for bedriftskunder. Prisene er mva. 0 %. Merverdiavgift legges til på fakturaen etter gjeldende sats. Grunnavgift og trinnvis enhetspris.",
    title: "Priser",
    intro: "iqFleetSync prises med en grunnavgift per bedrift samt kjøretøy, arbeidsmaskiner, tilhengere og utstyr. Prisene gjelder bedriftskunder og er mva. 0 %. Merverdiavgift legges til på fakturaen etter gjeldende sats.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Grunnavgift",
    baseValue: "10,00 € / måned / bedrift",
    unitHeading: "Prisnivåer per måned",
    unitNote: "Nivåene er trinnvise: de første 15 enhetene har den første prisen, og de neste enhetene har den neste prisen.",
    colRange: "Enheter",
    colVehicle: "Kjøretøy eller arbeidsmaskin / mnd",
    colTrailer: "Tilhenger / mnd",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["over 100", "0,90 €", "0,45 €"]],
    trailer: "En tilhenger er en halv enhet i nivået den havner i, så den koster halvparten av kjøretøyprisen i det nivået. Kjøretøy og arbeidsmaskiner fyller nivåene først, kjøretøy før arbeidsmaskiner.",
    mounted: "Et utstyr, for eksempel en tiltrotator, en hydraulisk hammer eller en feiekost, koster 0 €.",
    attachmentsLine: "Utstyr: 0,00 €. Det koster ingenting og telles ikke som enheter.",
    users: "Antall brukere er ubegrenset. Det er ingen pris per bruker.",
    peak: "Fakturaen bruker det høyeste enhetsantallet i kalendermåneden.",
    trial: "30 dagers gratis prøveperiode. Kalkulatoren viser prisen etter prøveperioden.",
    archived: "En arkivert enhet faktureres ikke. Historikk og fakturaer beholdes. Ikke ta med arkiverte enheter i kalkulatoren.",
    invoice: "Betalingen er en kortbetaling via Stripe. Fakturaen er månedlig og etterskuddsvis.",
    readOnly: "Hvis prøven slutter uten betaling, eller hvis en faktura er ubetalt 7 dager etter forfall, er kontoen skrivebeskyttet. Tjenesten kan sies opp når som helst.",
    cta: "Prøv gratis i 30 dager",
    terms: "Vilkår",
    calcTitle: "Kalkulator for månedspris",
    calcIntro: "Oppgi kjøretøy, arbeidsmaskiner, tilhengere og utstyr hver for seg. Hver linje viser hvor den delen av prisen kommer fra.",
    vehiclesLabel: "Kjøretøy",
    vehiclesHint: "for eksempel lastebiler",
    machinesLabel: "Arbeidsmaskiner",
    machinesHint: "for eksempel gravemaskiner og hjullastere",
    attachmentsLabel: "Utstyr",
    attachmentsHint: "for eksempel tiltrotator, hydraulisk hammer eller feiekost",
    trailersLabel: "Tilhengere",
    trailersHint: "en halv enhet",
    vehiclesMath: "Kjøretøy",
    machinesMath: "Arbeidsmaskiner",
    attachmentsMath: "Utstyr",
    freeNote: "ingen avgift",
    trailersMath: "Tilhengere × 0,5",
    trailersHalf: "Tilhengere (en halv enhet)",
    totalWord: "Totalt",
    perMonth: "/mnd",
    examplesTitle: "Eksempler",
    billingTitle: "Fakturering",
    billingNote: "Månedsprisen bruker det høyeste enhetsantallet i den kalendermåneden. Kjøretøy og arbeidsmaskiner er hele enheter og fyller nivåene først. En tilhenger er en halv enhet i sitt nivå. Utstyr er 0 €. Se vilkårene:",
    billingLink: "Vilkår",
    example5: "5 kjøretøy",
    example20: "20 kjøretøy og 5 tilhengere",
    exampleMix: "10 kjøretøy, 8 arbeidsmaskiner, 5 tilhengere og 4 utstyr",
    totalUnits: "Enheter totalt",
    unitsSum: "Pris for enhetene",
    baseLine: "Grunnavgift",
    monthTotal: "Månedspris",
    vatNote: "Prisene er mva. 0 %. Merverdiavgift legges til på fakturaen etter gjeldende sats.",
    audience: "For bedriftskunder",
    otherTitle: "Andre produkter",
    otherIntro: "Det er ingen offentlig pris. En publisert forbrukerpris vises inkludert merverdiavgift.",
    contact: "Ta kontakt",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  da: {
    metaTitle: "Priser | IQSoftCore",
    metaDescription: "Pris for iqFleetSync til erhvervskunder. Priserne er moms 0 %. Moms lægges til på fakturaen efter den gældende sats. Grundgebyr og trinvis enhedspris.",
    title: "Priser",
    intro: "iqFleetSync prissættes med et grundgebyr pr. virksomhed samt køretøjer, arbejdsmaskiner, anhængere og udstyr. Priserne gælder erhvervskunder og er moms 0 %. Moms lægges til på fakturaen efter den gældende sats.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Grundgebyr",
    baseValue: "10,00 € / måned / virksomhed",
    unitHeading: "Pristrin pr. måned",
    unitNote: "Trinnene er graduerede: de første 15 enheder har den første pris, og de næste enheder har den næste pris.",
    colRange: "Enheder",
    colVehicle: "Køretøj eller arbejdsmaskine / md.",
    colTrailer: "Anhænger / md.",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["over 100", "0,90 €", "0,45 €"]],
    trailer: "En anhænger er en halv enhed i det trin, den lander i, så den koster halvdelen af køretøjsprisen i det trin. Køretøjer og arbejdsmaskiner fylder trinnene først, køretøjer før arbejdsmaskiner.",
    mounted: "Et udstyr, for eksempel en tiltrotator, en hydraulisk hammer eller en fejekost, koster 0 €.",
    attachmentsLine: "Udstyr: 0,00 €. Det koster ingenting og tæller ikke som enheder.",
    users: "Antallet af brugere er ubegrænset. Der er ingen pris pr. bruger.",
    peak: "Regningen bruger det højeste enhedstal i kalendermåneden.",
    trial: "30 dages gratis prøve. Beregneren viser prisen efter prøven.",
    archived: "En arkiveret enhed faktureres ikke. Historik og fakturaer beholdes. Tæl ikke arkiverede enheder med i beregneren.",
    invoice: "Betalingen er en kortbetaling via Stripe. Fakturaen er månedlig og bagud.",
    readOnly: "Hvis prøven slutter uden betaling, eller hvis en faktura er ubetalt 7 dage efter forfald, er kontoen skrivebeskyttet. Tjenesten kan opsiges når som helst.",
    cta: "Prøv gratis i 30 dage",
    terms: "Vilkår",
    calcTitle: "Beregner til månedspris",
    calcIntro: "Angiv køretøjer, arbejdsmaskiner, anhængere og udstyr hver for sig. Hver linje viser, hvor den del af prisen kommer fra.",
    vehiclesLabel: "Køretøjer",
    vehiclesHint: "for eksempel lastbiler",
    machinesLabel: "Arbejdsmaskiner",
    machinesHint: "for eksempel gravemaskiner og gummigeder",
    attachmentsLabel: "Udstyr",
    attachmentsHint: "for eksempel tiltrotator, hydraulisk hammer eller fejekost",
    trailersLabel: "Anhængere",
    trailersHint: "en halv enhed",
    vehiclesMath: "Køretøjer",
    machinesMath: "Arbejdsmaskiner",
    attachmentsMath: "Udstyr",
    freeNote: "ingen betaling",
    trailersMath: "Anhængere × 0,5",
    trailersHalf: "Anhængere (en halv enhed)",
    totalWord: "I alt",
    perMonth: "/md.",
    examplesTitle: "Eksempler",
    billingTitle: "Fakturering",
    billingNote: "Månedsprisen bruger det højeste antal enheder i den kalendermåned. Køretøjer og arbejdsmaskiner er hele enheder og fylder trinnene først. En anhænger er en halv enhed i sit trin. Udstyr er 0 €. Se vilkårene:",
    billingLink: "Vilkår",
    example5: "5 køretøjer",
    example20: "20 køretøjer og 5 anhængere",
    exampleMix: "10 køretøjer, 8 arbejdsmaskiner, 5 anhængere og 4 stykker udstyr",
    totalUnits: "Enheder i alt",
    unitsSum: "Pris for enhederne",
    baseLine: "Grundgebyr",
    monthTotal: "Månedspris",
    vatNote: "Priserne er moms 0 %. Moms lægges til på fakturaen efter den gældende sats.",
    audience: "Til erhvervskunder",
    otherTitle: "Andre produkter",
    otherIntro: "Der er ingen offentlig pris. En offentliggjort forbrugerpris vises med moms.",
    contact: "Kontakt os",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  de: {
    metaTitle: "Preise | IQSoftCore",
    metaDescription: "Preise für iqFleetSync für Geschäftskunden. Preise sind MwSt. 0 %. Die Umsatzsteuer wird auf der Rechnung nach dem geltenden Steuersatz hinzugerechnet. Grundgebühr und gestaffelter Einheitspreis.",
    title: "Preise",
    intro: "iqFleetSync wird mit einer Grundgebühr je Unternehmen sowie Fahrzeugen, Arbeitsmaschinen, Anhängern und Anbaugeräten berechnet. Die Preise gelten für Geschäftskunden und sind MwSt. 0 %. Die Umsatzsteuer wird auf der Rechnung nach dem geltenden Steuersatz hinzugerechnet.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Grundgebühr",
    baseValue: "10,00 € / Monat / Unternehmen",
    unitHeading: "Preisstufen pro Monat",
    unitNote: "Die Stufen sind gestaffelt: die ersten 15 Einheiten zum ersten Preis, die nächsten Einheiten zum nächsten Preis.",
    colRange: "Einheiten",
    colVehicle: "Fahrzeug oder Arbeitsmaschine / Monat",
    colTrailer: "Anhänger / Monat",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["über 100", "0,90 €", "0,45 €"]],
    trailer: "Ein Anhänger ist eine halbe Einheit in der Stufe, in die er fällt, und kostet daher die Hälfte des Fahrzeugpreises dieser Stufe. Fahrzeuge und Arbeitsmaschinen füllen die Stufen zuerst, Fahrzeuge vor Arbeitsmaschinen.",
    mounted: "Ein Anbaugerät, zum Beispiel ein Tiltrotator, ein Hydraulikhammer oder eine Kehrmaschine, kostet 0 €.",
    attachmentsLine: "Anbaugeräte: 0,00 €. Dafür fällt kein Preis an, und sie zählen nicht als Einheiten.",
    users: "Die Zahl der Nutzer ist unbegrenzt. Es gibt keinen Preis je Nutzer.",
    peak: "Die Rechnung verwendet die höchste Einheitenanzahl im Kalendermonat.",
    trial: "30 Tage kostenlos testen. Der Rechner zeigt den Preis nach der Testphase.",
    archived: "Eine archivierte Einheit wird nicht berechnet. Historie und Rechnungen bleiben. Archivierte Einheiten nicht in den Rechner eintragen.",
    invoice: "Die Zahlung ist eine Kartenzahlung über Stripe. Die Rechnung ist monatlich und im Nachhinein.",
    readOnly: "Endet die Testphase ohne Zahlung, oder ist eine Rechnung 7 Tage nach dem Fälligkeitsdatum unbezahlt, ist das Konto nur lesbar. Der Dienst kann jederzeit gekündigt werden.",
    cta: "30 Tage kostenlos testen",
    terms: "Nutzungsbedingungen",
    calcTitle: "Rechner für den Monatspreis",
    calcIntro: "Geben Sie Fahrzeuge, Arbeitsmaschinen, Anhänger und Anbaugeräte getrennt ein. Jede Zeile zeigt, woher dieser Teil des Preises kommt.",
    vehiclesLabel: "Fahrzeuge",
    vehiclesHint: "zum Beispiel Lkw",
    machinesLabel: "Arbeitsmaschinen",
    machinesHint: "zum Beispiel Bagger und Radlader",
    attachmentsLabel: "Anbaugeräte",
    attachmentsHint: "zum Beispiel Tiltrotator, Hydraulikhammer oder Kehrmaschine",
    trailersLabel: "Anhänger",
    trailersHint: "eine halbe Einheit",
    vehiclesMath: "Fahrzeuge",
    machinesMath: "Arbeitsmaschinen",
    attachmentsMath: "Anbaugeräte",
    freeNote: "keine Gebühr",
    trailersMath: "Anhänger × 0,5",
    trailersHalf: "Anhänger (eine halbe Einheit)",
    totalWord: "Gesamt",
    perMonth: "/Monat",
    examplesTitle: "Beispiele",
    billingTitle: "Abrechnung",
    billingNote: "Der Monatspreis richtet sich nach der höchsten Einheitenzahl in diesem Kalendermonat. Fahrzeuge und Arbeitsmaschinen sind ganze Einheiten und füllen die Stufen zuerst. Ein Anhänger ist eine halbe Einheit in seiner Stufe. Ein Anbaugerät kostet 0 €. Siehe die Bedingungen:",
    billingLink: "Nutzungsbedingungen",
    example5: "5 Fahrzeuge",
    example20: "20 Fahrzeuge und 5 Anhänger",
    exampleMix: "10 Fahrzeuge, 8 Arbeitsmaschinen, 5 Anhänger und 4 Anbaugeräte",
    totalUnits: "Einheiten gesamt",
    unitsSum: "Preis der Einheiten",
    baseLine: "Grundgebühr",
    monthTotal: "Monatspreis",
    vatNote: "Preise sind MwSt. 0 %. Die Umsatzsteuer wird auf der Rechnung nach dem geltenden Steuersatz hinzugerechnet.",
    audience: "Für Geschäftskunden",
    otherTitle: "Weitere Produkte",
    otherIntro: "Für diese Produkte ist kein Preis veröffentlicht. Ein veröffentlichter Verbraucherpreis wird inklusive Umsatzsteuer angezeigt.",
    contact: "Kontakt aufnehmen",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  nl: {
    metaTitle: "Prijzen | IQSoftCore",
    metaDescription: "Prijzen voor iqFleetSync voor zakelijke klanten. Prijzen zijn btw 0%. Btw wordt op de factuur bijgeteld volgens het geldende tarief. Basisbedrag en staffelprijs per eenheid.",
    title: "Prijzen",
    intro: "iqFleetSync wordt gerekend met een basisbedrag per bedrijf plus voertuigen, werkmachines, aanhangers en uitrusting. De prijzen gelden voor zakelijke klanten en zijn btw 0%. Btw wordt op de factuur bijgeteld volgens het geldende tarief.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Basisbedrag",
    baseValue: "10,00 € / maand / bedrijf",
    unitHeading: "Prijsstaffels per maand",
    unitNote: "De staffels lopen op: de eerste 15 eenheden hebben de eerste prijs, en de volgende eenheden de volgende prijs.",
    colRange: "Eenheden",
    colVehicle: "Voertuig of werkmachine / mnd",
    colTrailer: "Aanhanger / mnd",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["meer dan 100", "0,90 €", "0,45 €"]],
    trailer: "Een aanhanger is een halve eenheid in de staffel waarin hij valt, en kost dus de helft van de voertuigprijs van die staffel. Voertuigen en werkmachines vullen de staffels eerst, voertuigen vóór werkmachines.",
    mounted: "Een uitrustingsstuk, bijvoorbeeld een tiltrotator, een hydraulische hamer of een veegmachine, kost 0 €.",
    attachmentsLine: "Uitrusting: 0,00 €. Daarvoor betaalt u niets, en ze tellen niet als eenheden.",
    users: "Het aantal gebruikers is onbeperkt. Er is geen prijs per gebruiker.",
    peak: "De rekening gebruikt het hoogste aantal eenheden in die kalendermaand.",
    trial: "30 dagen gratis proberen. De rekenhulp toont de prijs na de proefperiode.",
    archived: "Een gearchiveerde eenheid wordt niet gefactureerd. Geschiedenis en facturen blijven bewaard. Tel gearchiveerde eenheden niet mee in de rekenhulp.",
    invoice: "De betaling is een kaartbetaling via Stripe. De factuur is maandelijks en achteraf.",
    readOnly: "Eindigt de proef zonder betaling, of is een factuur 7 dagen na de vervaldatum onbetaald, dan is het account alleen-lezen. De dienst kan op elk moment worden opgezegd.",
    cta: "30 dagen gratis proberen",
    terms: "Gebruiksvoorwaarden",
    calcTitle: "Rekenhulp voor de maandprijs",
    calcIntro: "Vul voertuigen, werkmachines, aanhangers en uitrusting apart in. Elke regel laat zien waar dat deel van de prijs vandaan komt.",
    vehiclesLabel: "Voertuigen",
    vehiclesHint: "bijvoorbeeld vrachtwagens",
    machinesLabel: "Werkmachines",
    machinesHint: "bijvoorbeeld graafmachines en wielladers",
    attachmentsLabel: "Uitrusting",
    attachmentsHint: "bijvoorbeeld tiltrotator, hydraulische hamer of veegmachine",
    trailersLabel: "Aanhangers",
    trailersHint: "een halve eenheid",
    vehiclesMath: "Voertuigen",
    machinesMath: "Werkmachines",
    attachmentsMath: "Uitrusting",
    freeNote: "geen kosten",
    trailersMath: "Aanhangers × 0,5",
    trailersHalf: "Aanhangers (een halve eenheid)",
    totalWord: "Totaal",
    perMonth: "/mnd",
    examplesTitle: "Voorbeelden",
    billingTitle: "Facturatie",
    billingNote: "De maandprijs gebruikt het hoogste aantal eenheden in die kalendermaand. Voertuigen en werkmachines zijn hele eenheden en vullen de staffels eerst. Een aanhanger is een halve eenheid in zijn staffel. Uitrusting is 0 €. Zie de voorwaarden:",
    billingLink: "Gebruiksvoorwaarden",
    example5: "5 voertuigen",
    example20: "20 voertuigen en 5 aanhangers",
    exampleMix: "10 voertuigen, 8 werkmachines, 5 aanhangers en 4 stuks uitrusting",
    totalUnits: "Eenheden totaal",
    unitsSum: "Prijs van de eenheden",
    baseLine: "Basisbedrag",
    monthTotal: "Maandprijs",
    vatNote: "Prijzen zijn btw 0%. Btw wordt op de factuur bijgeteld volgens het geldende tarief.",
    audience: "Voor zakelijke klanten",
    otherTitle: "Andere producten",
    otherIntro: "Voor deze producten is geen prijs gepubliceerd. Een gepubliceerde consumentenprijs wordt inclusief btw getoond.",
    contact: "Neem contact op",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  fr: {
    metaTitle: "Tarifs | IQSoftCore",
    metaDescription: "Tarifs d’iqFleetSync. Les prix concernent les clients professionnels et sont TVA 0 %. La taxe sur la valeur ajoutée est ajoutée sur la facture au taux en vigueur. Forfait de base et prix unitaire par paliers.",
    title: "Tarifs",
    intro: "iqFleetSync se facture avec un forfait de base par entreprise, plus les véhicules, les engins, les remorques et les équipements. Les prix concernent les clients professionnels et sont TVA 0 %. La taxe sur la valeur ajoutée est ajoutée sur la facture au taux en vigueur.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Forfait de base",
    baseValue: "10,00 € / mois / entreprise",
    unitHeading: "Paliers de prix par mois",
    unitNote: "Les paliers sont progressifs : les 15 premières unités au premier prix, et les unités suivantes au prix suivant.",
    colRange: "Unités",
    colVehicle: "Véhicule ou engin / mois",
    colTrailer: "Remorque / mois",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["plus de 100", "0,90 €", "0,45 €"]],
    trailer: "Une remorque compte pour une demi-unité dans le palier où elle tombe, elle coûte donc la moitié du prix d’un véhicule de ce palier. Les véhicules et les engins remplissent les paliers d’abord, les véhicules avant les engins.",
    mounted: "Un équipement, par exemple un tiltrotateur, un brise-roche ou une balayeuse, coûte 0 €.",
    attachmentsLine: "Équipements : 0,00 €. Ils ne coûtent rien et ne comptent pas comme unités.",
    users: "Le nombre d’utilisateurs est illimité. Il n’y a pas de prix par utilisateur.",
    peak: "La facture utilise le nombre d’unités le plus élevé du mois civil.",
    trial: "Essai gratuit de 30 jours. Le calculateur montre le prix après l’essai.",
    archived: "Une unité archivée n’est pas facturée. L’historique et les factures sont conservés. Ne comptez pas les unités archivées dans le calculateur.",
    invoice: "Le paiement est une carte via Stripe. La facture est mensuelle et à terme échu.",
    readOnly: "Si l’essai se termine sans paiement, ou si une facture est impayée 7 jours après l’échéance, le compte passe en lecture seule. Le service peut être résilié à tout moment.",
    cta: "Essayer gratuitement 30 jours",
    terms: "Conditions d’utilisation",
    calcTitle: "Calculateur de prix mensuel",
    calcIntro: "Indiquez séparément les véhicules, les engins, les remorques et les équipements. Chaque ligne montre d’où vient cette partie du prix.",
    vehiclesLabel: "Véhicules",
    vehiclesHint: "par exemple des camions",
    machinesLabel: "Engins",
    machinesHint: "par exemple des pelles et des chargeuses",
    attachmentsLabel: "Équipements",
    attachmentsHint: "par exemple tiltrotateur, brise-roche ou balayeuse",
    trailersLabel: "Remorques",
    trailersHint: "une demi-unité",
    vehiclesMath: "Véhicules",
    machinesMath: "Engins",
    attachmentsMath: "Équipements",
    freeNote: "sans frais",
    trailersMath: "Remorques × 0,5",
    trailersHalf: "Remorques (une demi-unité)",
    totalWord: "Total",
    perMonth: "/mois",
    examplesTitle: "Exemples",
    billingTitle: "Facturation",
    billingNote: "Le prix du mois repose sur le nombre d’unités le plus élevé de ce mois calendaire. Les véhicules et les engins sont des unités entières et remplissent les paliers d’abord. Une remorque est une demi-unité dans son palier. Un équipement est à 0 €. Voir les conditions :",
    billingLink: "Conditions d’utilisation",
    example5: "5 véhicules",
    example20: "20 véhicules et 5 remorques",
    exampleMix: "10 véhicules, 8 engins, 5 remorques et 4 équipements",
    totalUnits: "Unités au total",
    unitsSum: "Prix des unités",
    baseLine: "Forfait de base",
    monthTotal: "Prix mensuel",
    vatNote: "Prix TVA 0 %. La taxe sur la valeur ajoutée est ajoutée sur la facture au taux en vigueur.",
    audience: "Pour les clients professionnels",
    otherTitle: "Autres produits",
    otherIntro: "Aucun prix n’est publié. Un prix consommateur publié est affiché TTC.",
    contact: "Nous contacter",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  es: {
    metaTitle: "Precios | IQSoftCore",
    metaDescription: "Precios de iqFleetSync. Los precios son para clientes de empresa y son IVA 0 %. El impuesto sobre el valor añadido se añade en la factura según el tipo vigente. Cuota base y precio por unidad en tramos.",
    title: "Precios",
    intro: "iqFleetSync se cobra con una cuota base por empresa más vehículos, máquinas de trabajo, remolques e implementos. Los precios son para clientes de empresa y son IVA 0 %. El impuesto sobre el valor añadido se añade en la factura según el tipo vigente.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Cuota base",
    baseValue: "10,00 € / mes / empresa",
    unitHeading: "Tramos de precio al mes",
    unitNote: "Los tramos son graduales: las primeras 15 unidades al primer precio y las siguientes al precio siguiente.",
    colRange: "Unidades",
    colVehicle: "Vehículo o máquina / mes",
    colTrailer: "Remolque / mes",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["más de 100", "0,90 €", "0,45 €"]],
    trailer: "Un remolque es media unidad en el tramo en el que cae, así que cuesta la mitad del precio del vehículo de ese tramo. Los vehículos y las máquinas llenan los tramos primero, los vehículos antes que las máquinas.",
    mounted: "Un implemento, por ejemplo un tiltrotator, un martillo hidráulico o una barredora, cuesta 0 €.",
    attachmentsLine: "Implementos: 0,00 €. No se cobran y no cuentan como unidades.",
    users: "Los usuarios son ilimitados. No hay un precio por usuario.",
    peak: "La factura usa el mayor número de unidades de ese mes natural.",
    trial: "Prueba gratis de 30 días. La calculadora muestra el precio después de la prueba.",
    archived: "Una unidad archivada no se factura. El historial y las facturas se conservan. No cuente las unidades archivadas en la calculadora.",
    invoice: "El pago es con tarjeta a través de Stripe. La factura es mensual y a mes vencido.",
    readOnly: "Si la prueba termina sin pago, o si una factura sigue impagada 7 días después del vencimiento, la cuenta queda en solo lectura. El servicio se puede cancelar en cualquier momento.",
    cta: "Probar gratis 30 días",
    terms: "Condiciones de uso",
    calcTitle: "Calculadora del precio mensual",
    calcIntro: "Indica por separado vehículos, máquinas, remolques e implementos. Cada línea muestra de dónde sale esa parte del precio.",
    vehiclesLabel: "Vehículos",
    vehiclesHint: "por ejemplo camiones",
    machinesLabel: "Máquinas de trabajo",
    machinesHint: "por ejemplo excavadoras y palas cargadoras",
    attachmentsLabel: "Implementos",
    attachmentsHint: "por ejemplo tiltrotator, martillo hidráulico o barredora",
    trailersLabel: "Remolques",
    trailersHint: "media unidad",
    vehiclesMath: "Vehículos",
    machinesMath: "Máquinas de trabajo",
    attachmentsMath: "Implementos",
    freeNote: "sin cargo",
    trailersMath: "Remolques × 0,5",
    trailersHalf: "Remolques (media unidad)",
    totalWord: "Total",
    perMonth: "/mes",
    examplesTitle: "Ejemplos",
    billingTitle: "Facturación",
    billingNote: "El precio del mes usa la cantidad más alta de unidades de ese mes natural. Los vehículos y las máquinas son unidades enteras y llenan los tramos primero. Un remolque es media unidad en su tramo. Un implemento es 0 €. Ver las condiciones:",
    billingLink: "Condiciones de uso",
    example5: "5 vehículos",
    example20: "20 vehículos y 5 remolques",
    exampleMix: "10 vehículos, 8 máquinas de trabajo, 5 remolques y 4 implementos",
    totalUnits: "Unidades en total",
    unitsSum: "Precio de las unidades",
    baseLine: "Cuota base",
    monthTotal: "Precio mensual",
    vatNote: "Precios IVA 0 %. El impuesto sobre el valor añadido se añade en la factura según el tipo vigente.",
    audience: "Para clientes de empresa",
    otherTitle: "Otros productos",
    otherIntro: "No hay un precio publicado. Un precio de consumidor publicado se muestra con IVA incluido.",
    contact: "Contactar",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  pt: {
    metaTitle: "Preços | IQSoftCore",
    metaDescription: "Preços do iqFleetSync. Os preços são para clientes empresariais e são IVA 0%. O imposto sobre o valor acrescentado é acrescentado na fatura à taxa em vigor. Taxa base e preço por unidade em faixas.",
    title: "Preços",
    intro: "O iqFleetSync é cobrado com uma taxa base por empresa mais veículos, máquinas de trabalho, reboques e equipamentos. Os preços são para clientes empresariais e são IVA 0%. O imposto sobre o valor acrescentado é acrescentado na fatura à taxa em vigor.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Taxa base",
    baseValue: "10,00 € / mês / empresa",
    unitHeading: "Faixas de preço por mês",
    unitNote: "As faixas são progressivas: as primeiras 15 unidades no primeiro preço e as seguintes no preço seguinte.",
    colRange: "Unidades",
    colVehicle: "Veículo ou máquina / mês",
    colTrailer: "Reboque / mês",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["acima de 100", "0,90 €", "0,45 €"]],
    trailer: "Um reboque é meia unidade na faixa em que cai, então custa metade do preço do veículo dessa faixa. Veículos e máquinas preenchem as faixas primeiro, os veículos antes das máquinas.",
    mounted: "Um equipamento, por exemplo um tiltrotator, um martelo hidráulico ou uma varredeira, custa 0 €.",
    attachmentsLine: "Equipamentos: 0,00 €. Não há cobrança e não contam como unidades.",
    users: "Os usuários são ilimitados. Não há preço por usuário.",
    peak: "A cobrança usa a maior quantidade de unidades daquele mês.",
    trial: "Teste grátis de 30 dias. A calculadora mostra o preço depois do teste.",
    archived: "Uma unidade arquivada não é faturada. O histórico e as faturas ficam guardados. Não conte unidades arquivadas na calculadora.",
    invoice: "O pagamento é com cartão através da Stripe. A fatura é mensal e a prazo.",
    readOnly: "Se o teste terminar sem pagamento, ou se uma fatura continuar por pagar 7 dias após o vencimento, a conta fica só de leitura. O serviço pode ser cancelado a qualquer momento.",
    cta: "Testar grátis por 30 dias",
    terms: "Termos de uso",
    calcTitle: "Calculadora do preço mensal",
    calcIntro: "Informe separadamente veículos, máquinas, reboques e equipamentos. Cada linha mostra de onde vem essa parte do preço.",
    vehiclesLabel: "Veículos",
    vehiclesHint: "por exemplo caminhões",
    machinesLabel: "Máquinas de trabalho",
    machinesHint: "por exemplo escavadeiras e pás carregadeiras",
    attachmentsLabel: "Equipamentos",
    attachmentsHint: "por exemplo tiltrotator, martelo hidráulico ou vassoura",
    trailersLabel: "Reboques",
    trailersHint: "meia unidade",
    vehiclesMath: "Veículos",
    machinesMath: "Máquinas de trabalho",
    attachmentsMath: "Equipamentos",
    freeNote: "sem cobrança",
    trailersMath: "Reboques × 0,5",
    trailersHalf: "Reboques (meia unidade)",
    totalWord: "Total",
    perMonth: "/mês",
    examplesTitle: "Exemplos",
    billingTitle: "Faturamento",
    billingNote: "O preço do mês usa a maior quantidade de unidades daquele mês. Veículos e máquinas são unidades inteiras e preenchem as faixas primeiro. Um reboque é meia unidade na sua faixa. Um equipamento é 0 €. Veja os termos:",
    billingLink: "Termos de uso",
    example5: "5 veículos",
    example20: "20 veículos e 5 reboques",
    exampleMix: "10 veículos, 8 máquinas de trabalho, 5 reboques e 4 equipamentos",
    totalUnits: "Unidades no total",
    unitsSum: "Preço das unidades",
    baseLine: "Taxa base",
    monthTotal: "Preço mensal",
    vatNote: "Preços IVA 0%. O imposto sobre o valor acrescentado é acrescentado na fatura à taxa em vigor.",
    audience: "Para clientes empresariais",
    otherTitle: "Outros produtos",
    otherIntro: "Não há preço publicado. Um preço de consumidor publicado é mostrado com IVA incluído.",
    contact: "Fale conosco",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  it: {
    metaTitle: "Prezzi | IQSoftCore",
    metaDescription: "Prezzi di iqFleetSync. I prezzi sono per clienti imprese e sono IVA 0%. L’imposta sul valore aggiunto si aggiunge in fattura all’aliquota in vigore. Quota base e prezzo a scaglioni per unità.",
    title: "Prezzi",
    intro: "iqFleetSync si paga con una quota base per azienda più veicoli, macchine operatrici, rimorchi e attrezzature. I prezzi sono per clienti imprese e sono IVA 0%. L’imposta sul valore aggiunto si aggiunge in fattura all’aliquota in vigore.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Quota base",
    baseValue: "10,00 € / mese / azienda",
    unitHeading: "Scaglioni di prezzo al mese",
    unitNote: "Gli scaglioni sono progressivi: le prime 15 unità al primo prezzo e le successive al prezzo successivo.",
    colRange: "Unità",
    colVehicle: "Veicolo o macchina / mese",
    colTrailer: "Rimorchio / mese",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["oltre 100", "0,90 €", "0,45 €"]],
    trailer: "Un rimorchio è mezza unità nello scaglione in cui cade, quindi costa la metà del prezzo del veicolo di quello scaglione. Veicoli e macchine riempiono gli scaglioni per primi, i veicoli prima delle macchine.",
    mounted: "Un’attrezzatura, per esempio un tiltrotator, un martello idraulico o una spazzatrice, costa 0 €.",
    attachmentsLine: "Attrezzature: 0,00 €. Non si pagano e non contano come unità.",
    users: "Gli utenti sono illimitati. Non c’è un prezzo per utente.",
    peak: "La fattura usa il numero di unità più alto di quel mese di calendario.",
    trial: "Prova gratuita di 30 giorni. Il calcolatore mostra il prezzo dopo la prova.",
    archived: "Un’unità archiviata non viene fatturata. Storico e fatture restano. Non contare le unità archiviate nel calcolatore.",
    invoice: "Il pagamento è con carta tramite Stripe. La fattura è mensile e posticipata.",
    readOnly: "Se la prova finisce senza pagamento, o se una fattura resta non pagata 7 giorni dopo la scadenza, l’account è in sola lettura. Il servizio si può disdire in qualsiasi momento.",
    cta: "Prova gratis per 30 giorni",
    terms: "Condizioni d’uso",
    calcTitle: "Calcolatore del prezzo mensile",
    calcIntro: "Inserisci separatamente veicoli, macchine, rimorchi e attrezzature. Ogni riga mostra da dove arriva quella parte del prezzo.",
    vehiclesLabel: "Veicoli",
    vehiclesHint: "per esempio camion",
    machinesLabel: "Macchine operatrici",
    machinesHint: "per esempio escavatori e pale gommate",
    attachmentsLabel: "Attrezzature",
    attachmentsHint: "per esempio tiltrotator, martello idraulico o spazzatrice",
    trailersLabel: "Rimorchi",
    trailersHint: "mezza unità",
    vehiclesMath: "Veicoli",
    machinesMath: "Macchine operatrici",
    attachmentsMath: "Attrezzature",
    freeNote: "senza costo",
    trailersMath: "Rimorchi × 0,5",
    trailersHalf: "Rimorchi (mezza unità)",
    totalWord: "Totale",
    perMonth: "/mese",
    examplesTitle: "Esempi",
    billingTitle: "Fatturazione",
    billingNote: "Il prezzo del mese usa il numero più alto di unità di quel mese di calendario. Veicoli e macchine sono unità intere e riempiono gli scaglioni per primi. Un rimorchio è mezza unità nel suo scaglione. Un’attrezzatura è 0 €. Vedi le condizioni:",
    billingLink: "Condizioni d’uso",
    example5: "5 veicoli",
    example20: "20 veicoli e 5 rimorchi",
    exampleMix: "10 veicoli, 8 macchine operatrici, 5 rimorchi e 4 attrezzature",
    totalUnits: "Unità in totale",
    unitsSum: "Prezzo delle unità",
    baseLine: "Quota base",
    monthTotal: "Prezzo mensile",
    vatNote: "Prezzi IVA 0%. L’imposta sul valore aggiunto si aggiunge in fattura all’aliquota in vigore.",
    audience: "Per clienti imprese",
    otherTitle: "Altri prodotti",
    otherIntro: "Non c’è un prezzo pubblicato. Un prezzo per consumatori pubblicato è mostrato IVA inclusa.",
    contact: "Contattaci",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  pl: {
    metaTitle: "Cennik | IQSoftCore",
    metaDescription: "Cennik iqFleetSync. Ceny są dla klientów firmowych i wynoszą VAT 0%. Podatek VAT dolicza się na fakturze według obowiązującej stawki. Opłata podstawowa i cena jednostkowa progami.",
    title: "Cennik",
    intro: "iqFleetSync jest rozliczany opłatą podstawową firmy oraz pojazdami, maszynami roboczymi, przyczepami i osprzętem. Ceny są dla klientów firmowych i wynoszą VAT 0%. Podatek VAT dolicza się na fakturze według obowiązującej stawki.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Opłata podstawowa",
    baseValue: "10,00 € / miesiąc / firma",
    unitHeading: "Progi cenowe na miesiąc",
    unitNote: "Progi są stopniowane: pierwsze 15 jednostek w pierwszej cenie, a kolejne jednostki w następnej cenie.",
    colRange: "Jednostki",
    colVehicle: "Pojazd lub maszyna / mies.",
    colTrailer: "Przyczepa / mies.",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["powyżej 100", "0,90 €", "0,45 €"]],
    trailer: "Przyczepa to pół jednostki w progu, do którego trafia, więc kosztuje połowę ceny pojazdu z tego progu. Pojazdy i maszyny wypełniają progi najpierw, pojazdy przed maszynami.",
    mounted: "Osprzęt, na przykład tiltrotator, młot hydrauliczny albo zamiatarka, kosztuje 0 €.",
    attachmentsLine: "Osprzęt: 0,00 €. Nie ma opłaty i nie liczy się jako jednostka.",
    users: "Liczba użytkowników jest nieograniczona. Nie ma opłaty za użytkownika.",
    peak: "Rachunek używa największej liczby jednostek w danym miesiącu kalendarzowym.",
    trial: "30 dni bezpłatnie. Kalkulator pokazuje cenę po okresie próbnym.",
    archived: "Zarchiwizowana jednostka nie jest rozliczana. Historia i faktury zostają. Nie wliczaj zarchiwizowanych jednostek do kalkulatora.",
    invoice: "Płatność to karta przez Stripe. Faktura jest miesięczna i z dołu.",
    readOnly: "Jeśli okres próbny kończy się bez płatności albo faktura jest niezapłacona 7 dni po terminie, konto jest tylko do odczytu. Usługę można wypowiedzieć w dowolnej chwili.",
    cta: "Wypróbuj bezpłatnie przez 30 dni",
    terms: "Regulamin",
    calcTitle: "Kalkulator ceny miesięcznej",
    calcIntro: "Podaj osobno pojazdy, maszyny, przyczepy i osprzęt. Każdy wiersz pokazuje, skąd bierze się ta część ceny.",
    vehiclesLabel: "Pojazdy",
    vehiclesHint: "na przykład samochody ciężarowe",
    machinesLabel: "Maszyny robocze",
    machinesHint: "na przykład koparki i ładowarki",
    attachmentsLabel: "Osprzęt",
    attachmentsHint: "na przykład tiltrotator, młot hydrauliczny albo zamiatarka",
    trailersLabel: "Przyczepy",
    trailersHint: "pół jednostki",
    vehiclesMath: "Pojazdy",
    machinesMath: "Maszyny robocze",
    attachmentsMath: "Osprzęt",
    freeNote: "bez opłaty",
    trailersMath: "Przyczepy × 0,5",
    trailersHalf: "Przyczepy (pół jednostki)",
    totalWord: "Razem",
    perMonth: "/mies.",
    examplesTitle: "Przykłady",
    billingTitle: "Rozliczenie",
    billingNote: "Cena miesiąca wynika z największej liczby jednostek w tym miesiącu kalendarzowym. Pojazdy i maszyny są pełnymi jednostkami i wypełniają progi najpierw. Przyczepa to pół jednostki w swoim progu. Osprzęt kosztuje 0 €. Zobacz warunki:",
    billingLink: "Warunki korzystania",
    example5: "5 pojazdów",
    example20: "20 pojazdów i 5 przyczep",
    exampleMix: "10 pojazdów, 8 maszyn roboczych, 5 przyczep i 4 sztuki osprzętu",
    totalUnits: "Jednostki łącznie",
    unitsSum: "Cena jednostek",
    baseLine: "Opłata podstawowa",
    monthTotal: "Cena miesięczna",
    vatNote: "Ceny VAT 0%. Podatek VAT dolicza się na fakturze według obowiązującej stawki.",
    audience: "Dla klientów firmowych",
    otherTitle: "Inne produkty",
    otherIntro: "Nie ma opublikowanej ceny. Opublikowana cena dla konsumenta jest pokazywana z VAT.",
    contact: "Skontaktuj się",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  cs: {
    metaTitle: "Ceník | IQSoftCore",
    metaDescription: "Ceník iqFleetSync. Ceny jsou pro firemní zákazníky a jsou DPH 0 %. Daň z přidané hodnoty se připočte na faktuře podle platné sazby. Základní poplatek a odstupňovaná cena za jednotku.",
    title: "Ceník",
    intro: "iqFleetSync se účtuje základním poplatkem firmy a dále vozidly, pracovními stroji, přívěsy a nástavbami. Ceny jsou pro firemní zákazníky a jsou DPH 0 %. Daň z přidané hodnoty se připočte na faktuře podle platné sazby.",
    fleetTitle: "iqFleetSync",
    baseLabel: "Základní poplatek",
    baseValue: "10,00 € / měsíc / firma",
    unitHeading: "Cenová pásma za měsíc",
    unitNote: "Pásma jsou odstupňovaná: prvních 15 jednotek za první cenu a další jednotky za následující cenu.",
    colRange: "Jednotky",
    colVehicle: "Vozidlo nebo stroj / měs.",
    colTrailer: "Přívěs / měs.",
    tiers: [["1–15", "1,50 €", "0,75 €"], ["16–50", "1,30 €", "0,65 €"], ["51–100", "1,10 €", "0,55 €"], ["nad 100", "0,90 €", "0,45 €"]],
    trailer: "Přívěs je půl jednotky v pásmu, do kterého spadá, takže stojí polovinu ceny vozidla toho pásma. Vozidla a stroje plní pásma první, vozidla před stroji.",
    mounted: "Nástavba, například tiltrotátor, hydraulické kladivo nebo zametač, stojí 0 €.",
    attachmentsLine: "Nástavby: 0,00 €. Nic se neúčtuje a nepočítají se jako jednotky.",
    users: "Počet uživatelů není omezen. Za uživatele se nic neúčtuje.",
    peak: "Faktura používá nejvyšší počet jednotek v daném kalendářním měsíci.",
    trial: "30 dní zdarma. Kalkulačka ukazuje cenu po zkušební době.",
    archived: "Archivovaná jednotka se neúčtuje. Historie a faktury zůstanou. Archivované jednotky do kalkulačky nezadávejte.",
    invoice: "Platba je kartou přes Stripe. Faktura je měsíční a zpětně.",
    readOnly: "Když zkušební doba skončí bez platby, nebo je faktura nezaplacená 7 dní po splatnosti, účet je jen ke čtení. Službu lze kdykoli zrušit.",
    cta: "Vyzkoušet zdarma na 30 dní",
    terms: "Podmínky použití",
    calcTitle: "Kalkulačka měsíční ceny",
    calcIntro: "Zadejte zvlášť vozidla, stroje, přívěsy a nástavby. Každý řádek ukazuje, odkud se ta část ceny bere.",
    vehiclesLabel: "Vozidla",
    vehiclesHint: "například nákladní auta",
    machinesLabel: "Pracovní stroje",
    machinesHint: "například bagry a kolové nakladače",
    attachmentsLabel: "Nástavby",
    attachmentsHint: "například tiltrotátor, hydraulické kladivo nebo zametač",
    trailersLabel: "Přívěsy",
    trailersHint: "půl jednotky",
    vehiclesMath: "Vozidla",
    machinesMath: "Pracovní stroje",
    attachmentsMath: "Nástavby",
    freeNote: "bez poplatku",
    trailersMath: "Přívěsy × 0,5",
    trailersHalf: "Přívěsy (půl jednotky)",
    totalWord: "Celkem",
    perMonth: "/měs.",
    examplesTitle: "Příklady",
    billingTitle: "Fakturace",
    billingNote: "Měsíční cena vychází z nejvyššího počtu jednotek v daném kalendářním měsíci. Vozidla a stroje jsou celé jednotky a plní pásma první. Přívěs je půl jednotky ve svém pásmu. Nástavba je 0 €. Viz podmínky:",
    billingLink: "Podmínky použití",
    example5: "5 vozidel",
    example20: "20 vozidel a 5 přívěsů",
    exampleMix: "10 vozidel, 8 pracovních strojů, 5 přívěsů a 4 nástavby",
    totalUnits: "Jednotek celkem",
    unitsSum: "Cena jednotek",
    baseLine: "Základní poplatek",
    monthTotal: "Měsíční cena",
    vatNote: "Ceny DPH 0 %. Daň z přidané hodnoty se připočte na faktuře podle platné sazby.",
    audience: "Pro firemní zákazníky",
    otherTitle: "Ostatní produkty",
    otherIntro: "Zveřejněná cena není. Zveřejněná spotřebitelská cena se ukazuje včetně DPH.",
    contact: "Kontaktujte nás",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  ja: {
    metaTitle: "料金 | IQSoftCore",
    metaDescription: "事業者顧客向けのiqFleetSync料金。価格は消費税0%です。消費税は適用される税率で請求書に加算します。基本料金と段階制の単価。",
    title: "料金",
    intro: "iqFleetSyncは、会社ごとの基本料金に加え、車両、作業機械、トレーラー、アタッチメントで計算します。価格は事業者顧客向けで、消費税0%です。消費税は適用される税率で請求書に加算します。",
    fleetTitle: "iqFleetSync",
    baseLabel: "基本料金",
    baseValue: "10.00 € / 月 / 会社",
    unitHeading: "月ごとの料金段階",
    unitNote: "段階は累進です。最初の15単位は最初の価格、その次の単位は次の価格です。",
    colRange: "単位",
    colVehicle: "車両または作業機械 / 月",
    colTrailer: "トレーラー / 月",
    tiers: [["1–15", "1.50 €", "0.75 €"], ["16–50", "1.30 €", "0.65 €"], ["51–100", "1.10 €", "0.55 €"], ["100超", "0.90 €", "0.45 €"]],
    trailer: "トレーラーは入った段階の0.5単位なので、その段階の車両価格の半分です。車両と作業機械が先に段階を埋め、車両が作業機械より先です。",
    mounted: "アタッチメント（チルトローテーター、油圧ブレーカー、スイーパーなど）は 0 € です。",
    attachmentsLine: "アタッチメント: 0.00 €。料金はかからず、単位にも数えません。",
    users: "ユーザー数は無制限です。ユーザーごとの料金はありません。",
    peak: "請求は、その暦月の最大単位数に基づきます。",
    trial: "30日間の無料試用。計算機は試用後の料金を表示します。",
    archived: "アーカイブした単位は請求しません。履歴と請求書は残ります。計算機にはアーカイブした単位を入れないでください。",
    invoice: "支払いはStripeのカードです。請求は毎月、後払いです。",
    readOnly: "試用が終わって支払いがない場合、または請求書の期限から7日過ぎても未払いの場合、アカウントは閲覧のみになります。いつでも解約できます。",
    cta: "30日間無料で試す",
    terms: "利用規約",
    calcTitle: "月額の計算機",
    calcIntro: "車両、作業機械、トレーラー、アタッチメントを別々に入力してください。各行が、その金額の内訳を示します。",
    vehiclesLabel: "車両",
    vehiclesHint: "例：トラック",
    machinesLabel: "作業機械",
    machinesHint: "例：油圧ショベル、ホイールローダー",
    attachmentsLabel: "アタッチメント",
    attachmentsHint: "例：チルトローテーター、油圧ブレーカー、スイーパー",
    trailersLabel: "トレーラー",
    trailersHint: "0.5単位",
    vehiclesMath: "車両",
    machinesMath: "作業機械",
    attachmentsMath: "アタッチメント",
    freeNote: "料金なし",
    trailersMath: "トレーラー × 0.5",
    trailersHalf: "トレーラー（0.5単位）",
    totalWord: "合計",
    perMonth: "/月",
    examplesTitle: "計算例",
    billingTitle: "請求",
    billingNote: "月額は、その暦月の最大単位数で計算します。車両と作業機械は1単位で、段階を先に埋めます。トレーラーはその段階の0.5単位です。アタッチメントは 0 € です。詳細は利用規約をご覧ください：",
    billingLink: "利用規約",
    example5: "車両 5 台",
    example20: "車両 20 台とトレーラー 5 台",
    exampleMix: "車両 10 台、作業機械 8 台、トレーラー 5 台、アタッチメント 4 台",
    totalUnits: "単位の合計",
    unitsSum: "単位の料金",
    baseLine: "基本料金",
    monthTotal: "月額",
    vatNote: "価格は消費税0%です。消費税は適用される税率で請求書に加算します。",
    audience: "事業者顧客向け",
    otherTitle: "その他の製品",
    otherIntro: "公開された価格はありません。消費者向け価格を公表する場合は税込で表示します。",
    contact: "お問い合わせ",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  ko: {
    metaTitle: "요금 | IQSoftCore",
    metaDescription: "사업자 고객용 iqFleetSync 요금. 가격은 부가세 0%입니다. 부가가치세는 적용 세율에 따라 청구서에 더합니다. 기본요금과 구간별 단위 가격.",
    title: "요금",
    intro: "iqFleetSync는 회사별 기본요금과 차량, 작업기계, 트레일러, 어태치먼트로 계산합니다. 가격은 사업자 고객용이며 부가세 0%입니다. 부가가치세는 적용 세율에 따라 청구서에 더합니다.",
    fleetTitle: "iqFleetSync",
    baseLabel: "기본요금",
    baseValue: "10.00 € / 월 / 회사",
    unitHeading: "월별 요금 구간",
    unitNote: "구간은 누진입니다. 처음 15단위는 첫 가격, 그다음 단위는 다음 가격입니다.",
    colRange: "단위",
    colVehicle: "차량 또는 작업기계 / 월",
    colTrailer: "트레일러 / 월",
    tiers: [["1–15", "1.50 €", "0.75 €"], ["16–50", "1.30 €", "0.65 €"], ["51–100", "1.10 €", "0.55 €"], ["100 초과", "0.90 €", "0.45 €"]],
    trailer: "트레일러는 해당 구간의 0.5단위라서 그 구간 차량 가격의 절반입니다. 차량과 작업기계가 구간을 먼저 채우고, 차량이 작업기계보다 먼저입니다.",
    mounted: "어태치먼트(틸트로테이터, 유압 브레이커, 스위퍼 등)는 0 €입니다.",
    attachmentsLine: "어태치먼트: 0.00 €. 요금이 없고 단위에도 포함하지 않습니다.",
    users: "사용자 수는 제한이 없습니다. 사용자별 요금은 없습니다.",
    peak: "청구는 해당 달의 최대 단위 수를 기준으로 합니다.",
    trial: "30일 무료 체험. 계산기는 체험 이후 요금을 보여 줍니다.",
    archived: "보관 처리한 단위는 청구하지 않습니다. 이력과 청구서는 남습니다. 계산기에는 보관 처리한 단위를 넣지 마세요.",
    invoice: "결제는 Stripe 카드입니다. 청구는 매월 후불입니다.",
    readOnly: "체험이 끝나고 결제가 없거나, 청구서 만기 후 7일이 지나도 미납이면 계정은 읽기 전용입니다. 언제든 해지할 수 있습니다.",
    cta: "30일 무료로 사용해 보기",
    terms: "이용약관",
    calcTitle: "월 요금 계산기",
    calcIntro: "차량, 작업기계, 트레일러, 어태치먼트를 따로 입력하세요. 각 줄이 그 금액이 어디서 나오는지 보여 줍니다.",
    vehiclesLabel: "차량",
    vehiclesHint: "예: 트럭",
    machinesLabel: "작업기계",
    machinesHint: "예: 굴착기, 휠로더",
    attachmentsLabel: "어태치먼트",
    attachmentsHint: "예: 틸트로테이터, 유압 브레이커, 스위퍼",
    trailersLabel: "트레일러",
    trailersHint: "0.5단위",
    vehiclesMath: "차량",
    machinesMath: "작업기계",
    attachmentsMath: "어태치먼트",
    freeNote: "요금 없음",
    trailersMath: "트레일러 × 0.5",
    trailersHalf: "트레일러(0.5단위)",
    totalWord: "합계",
    perMonth: "/월",
    examplesTitle: "계산 예",
    billingTitle: "청구",
    billingNote: "월 요금은 그 달의 최대 단위 수를 기준으로 합니다. 차량과 작업기계는 한 단위이며 구간을 먼저 채웁니다. 트레일러는 해당 구간의 0.5단위입니다. 어태치먼트는 0 €입니다. 자세한 내용은 이용약관을 보세요:",
    billingLink: "이용약관",
    example5: "차량 5대",
    example20: "차량 20대와 트레일러 5대",
    exampleMix: "차량 10대, 작업기계 8대, 트레일러 5대, 어태치먼트 4대",
    totalUnits: "단위 합계",
    unitsSum: "단위 요금",
    baseLine: "기본요금",
    monthTotal: "월 요금",
    vatNote: "가격은 부가세 0%입니다. 부가가치세는 적용 세율에 따라 청구서에 더합니다.",
    audience: "사업자 고객용",
    otherTitle: "다른 제품",
    otherIntro: "공개된 가격이 없습니다. 소비자 가격이 공개되면 부가세 포함 가격으로 표시합니다.",
    contact: "문의하기",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
  zh: {
    metaTitle: "价格 | IQSoftCore",
    metaDescription: "面向企业客户的 iqFleetSync 价格。价格为增值税 0%。增值税按适用税率加在账单上。基础费和分档单位价。",
    title: "价格",
    intro: "iqFleetSync 按每家公司的基础费，以及车辆、工程机械、挂车和属具计费。价格面向企业客户，为增值税 0%。增值税按适用税率加在账单上。",
    fleetTitle: "iqFleetSync",
    baseLabel: "基础费",
    baseValue: "10.00 € / 月 / 公司",
    unitHeading: "每月价格档",
    unitNote: "各档是累进的：前 15 个单位用第一档价格，其后的单位用下一档价格。",
    colRange: "单位",
    colVehicle: "车辆或工程机械 / 月",
    colTrailer: "挂车 / 月",
    tiers: [["1–15", "1.50 €", "0.75 €"], ["16–50", "1.30 €", "0.65 €"], ["51–100", "1.10 €", "0.55 €"], ["100 以上", "0.90 €", "0.45 €"]],
    trailer: "挂车按其落入的档计为半个单位，因此按该档车辆价格的一半收费。车辆和工程机械先填满各档，车辆先于工程机械。",
    mounted: "属具，例如倾斜旋转器、液压破碎锤或清扫器，价格为 0 €。",
    attachmentsLine: "属具：0.00 €。不收费，也不计入单位。",
    users: "用户数量不限。不按用户收费。",
    peak: "账单按该自然月的最高单位数计算。",
    trial: "30 天免费试用。计算器显示试用结束后的价格。",
    archived: "已归档的单位不计费。历史和发票会保留。请不要把已归档的单位填进计算器。",
    invoice: "付款通过 Stripe 用卡支付。账单按月开具，事后结算。",
    readOnly: "如果试用结束而没有付款，或者发票在到期日后 7 天仍未支付，账户变为只读。可以随时取消。",
    cta: "免费试用 30 天",
    terms: "使用条款",
    calcTitle: "月费计算器",
    calcIntro: "请分别输入车辆、工程机械、挂车和属具。每一行都显示这部分价格从哪里来。",
    vehiclesLabel: "车辆",
    vehiclesHint: "例如卡车",
    machinesLabel: "工程机械",
    machinesHint: "例如挖掘机和轮式装载机",
    attachmentsLabel: "属具",
    attachmentsHint: "例如倾斜旋转器、液压破碎锤或清扫器",
    trailersLabel: "挂车",
    trailersHint: "半个单位",
    vehiclesMath: "车辆",
    machinesMath: "工程机械",
    attachmentsMath: "属具",
    freeNote: "不收费",
    trailersMath: "挂车 × 0.5",
    trailersHalf: "挂车（半个单位）",
    totalWord: "合计",
    perMonth: "/月",
    examplesTitle: "计算示例",
    billingTitle: "计费",
    billingNote: "月费按该自然月的最高单位数计算。车辆和工程机械是完整单位，并先填满各档。挂车是其所在档的半个单位。属具为 0 €。详见条款：",
    billingLink: "使用条款",
    example5: "5 辆车",
    example20: "20 辆车和 5 辆挂车",
    exampleMix: "10 辆车、8 台工程机械、5 辆挂车和 4 件属具",
    totalUnits: "单位合计",
    unitsSum: "单位费用",
    baseLine: "基础费",
    monthTotal: "月费",
    vatNote: "价格为增值税 0%。增值税按适用税率加在账单上。",
    audience: "面向企业客户",
    otherTitle: "其他产品",
    otherIntro: "没有公布价格。公布消费者价格时，按含税价展示。",
    contact: "联系我们",
    others: [["tuntilappu.html", "Tuntilappu"], ["iqrallynote.html", "iqRallyNote"]],
  },
};

function escapePriceHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatPriceAmount(cents, lang) {
  const locale = PRICE_LOCALES[lang] || "fi-FI";
  const formatted = new Intl.NumberFormat(locale, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(cents / 100);
  return formatted + " €";
}

const PRICE_EXAMPLES = [
  { vehicles: 5, machines: 0, trailers: 0, attachments: 0, titleKey: "example5" },
  { vehicles: 20, machines: 0, trailers: 5, attachments: 0, titleKey: "example20" },
  { vehicles: 10, machines: 8, trailers: 5, attachments: 4, titleKey: "exampleMix" },
];

const PRICE_LINE_LABELS = {
  vehicle: "vehiclesMath",
  machine: "machinesMath",
  trailer: "trailersHalf",
  attachment: "attachmentsMath",
};

function formatFormulaCount(count, lang) {
  const locale = PRICE_LOCALES[lang] || "fi-FI";
  const digits = Number.isInteger(count) ? 0 : 1;
  return new Intl.NumberFormat(locale, {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  }).format(count);
}

function renderPriceQuote(lang, page, quote) {
  const lines = [
    `<li class="calc-pair"><span>${escapePriceHtml(page.baseLine)}</span><span>${escapePriceHtml(formatPriceAmount(quote.baseCents, lang))}</span></li>`,
  ];

  ["vehicle", "machine", "trailer", "attachment"].forEach((kind) => {
    const group = quote.lines.filter((line) => line.kind === kind);
    if (!group.length) return;
    const label = page[PRICE_LINE_LABELS[kind]];
    group.forEach((line) => {
      let formula = `${formatFormulaCount(line.count, lang)} × ${formatPriceAmount(line.rateCents, lang)} = ${formatPriceAmount(line.amountCents, lang)}`;
      if (kind === "attachment") formula += ` (${page.freeNote})`;
      lines.push(
        `<li class="calc-formula"><span class="calc-kind">${escapePriceHtml(label)}:</span> ${escapePriceHtml(formula)}</li>`
      );
    });
  });

  const total = `${formatPriceAmount(quote.totalCents, lang)}${page.perMonth}`;
  lines.push(
    `<li class="calc-total calc-pair"><span>${escapePriceHtml(page.totalWord)}</span><span class="calc-total-amount">${escapePriceHtml(total)}</span></li>`
  );

  return `<ul class="calc-lines">${lines.join("")}</ul>`;
}

function renderPricingPage(lang) {
  const root = document.getElementById("pricing-root");
  if (!root || typeof quoteFleetSync !== "function") return;

  const page = PRICING_PAGE[lang] || PRICING_PAGE.en;
  const previousVehicles = document.getElementById("calc-vehicles");
  const previousMachines = document.getElementById("calc-machines");
  const previousTrailers = document.getElementById("calc-trailers");
  const previousAttachments = document.getElementById("calc-attachments");
  const vehicleValue = previousVehicles ? previousVehicles.value : "";
  const machineValue = previousMachines ? previousMachines.value : "";
  const trailerValue = previousTrailers ? previousTrailers.value : "";
  const attachmentValue = previousAttachments ? previousAttachments.value : "";

  const titleEl = document.querySelector("title");
  if (titleEl) titleEl.textContent = page.metaTitle;
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc) metaDesc.setAttribute("content", page.metaDescription);

  const tierRows = page.tiers
    .map(
      ([range, vehiclePrice, trailerPrice]) =>
        `<tr><td>${escapePriceHtml(range)}</td><td>${escapePriceHtml(vehiclePrice)}</td><td>${escapePriceHtml(trailerPrice)}</td></tr>`
    )
    .join("");

  const others = page.others
    .map(
      ([href, name]) => `<article class="other-product">
        <h3><a href="${escapePriceHtml(href)}">${escapePriceHtml(name)}</a></h3>
        <p><a href="index.html#contact">${escapePriceHtml(page.contact)}</a></p>
      </article>`
    )
    .join("");

  root.innerHTML = `<h1>${escapePriceHtml(page.title)}</h1>
    <p>${escapePriceHtml(page.intro)}</p>
    <h2>${escapePriceHtml(page.fleetTitle)}</h2>
    <p class="price-aside"><strong>${escapePriceHtml(page.audience)}</strong></p>
    <h2>${escapePriceHtml(page.unitHeading)}</h2>
    <p>${escapePriceHtml(page.unitNote)}</p>
    <div class="price-scroll">
      <table class="price-table">
        <thead><tr><th>${escapePriceHtml(page.colRange)}</th><th>${escapePriceHtml(page.colVehicle)}</th><th>${escapePriceHtml(page.colTrailer)}</th></tr></thead>
        <tbody>${tierRows}</tbody>
      </table>
    </div>
    <p class="price-aside">${escapePriceHtml(page.attachmentsLine)}</p>
    <p class="price-aside"><strong>${escapePriceHtml(page.baseLabel)}:</strong> ${escapePriceHtml(page.baseValue)}.</p>
    <p class="vat-note">${escapePriceHtml(page.vatNote)}</p>
    <ul>
      <li>${escapePriceHtml(page.trailer)}</li>
      <li>${escapePriceHtml(page.mounted)}</li>
      <li>${escapePriceHtml(page.users)}</li>
      <li>${escapePriceHtml(page.peak)}</li>
      <li>${escapePriceHtml(page.archived)}</li>
      <li>${escapePriceHtml(page.invoice)}</li>
      <li>${escapePriceHtml(page.trial)}</li>
      <li>${escapePriceHtml(page.readOnly)}</li>
    </ul>
    <h2>${escapePriceHtml(page.billingTitle)}</h2>
    <p class="billing-note">${escapePriceHtml(page.billingNote)} <a href="kayttoehdot.html">${escapePriceHtml(page.billingLink)}</a></p>
    <div class="app-actions">
      <a class="btn btn-primary" href="https://fleetsync.iqsoftcore.fi/rekisteroidy">${escapePriceHtml(page.cta)}</a>
      <a class="btn btn-ghost" href="kayttoehdot.html">${escapePriceHtml(page.terms)}</a>
    </div>
    <h2>${escapePriceHtml(page.calcTitle)}</h2>
    <p>${escapePriceHtml(page.calcIntro)}</p>
    <p>${escapePriceHtml(page.trailer)}</p>
    <div class="calc-box">
      <div class="calc-fields">
        <div class="field">
          <label for="calc-vehicles">${escapePriceHtml(page.vehiclesLabel)}</label>
          <span class="field-hint" id="calc-vehicles-hint">${escapePriceHtml(page.vehiclesHint)}</span>
          <input id="calc-vehicles" type="number" inputmode="numeric" min="0" step="1" value="" aria-describedby="calc-vehicles-hint">
        </div>
        <div class="field">
          <label for="calc-machines">${escapePriceHtml(page.machinesLabel)}</label>
          <span class="field-hint" id="calc-machines-hint">${escapePriceHtml(page.machinesHint)}</span>
          <input id="calc-machines" type="number" inputmode="numeric" min="0" step="1" value="" aria-describedby="calc-machines-hint">
        </div>
        <div class="field">
          <label for="calc-trailers">${escapePriceHtml(page.trailersLabel)}</label>
          <span class="field-hint" id="calc-trailers-hint">${escapePriceHtml(page.trailersHint)}</span>
          <input id="calc-trailers" type="number" inputmode="numeric" min="0" step="1" value="" aria-describedby="calc-trailers-hint">
        </div>
        <div class="field">
          <label for="calc-attachments">${escapePriceHtml(page.attachmentsLabel)}</label>
          <span class="field-hint" id="calc-attachments-hint">${escapePriceHtml(page.attachmentsHint)}</span>
          <input id="calc-attachments" type="number" inputmode="numeric" min="0" step="1" value="" aria-describedby="calc-attachments-hint">
        </div>
      </div>
      <div id="calc-result" aria-live="polite"></div>
      <p class="calc-total-vat">${escapePriceHtml(page.vatNote)}</p>
      <p class="calc-note">${escapePriceHtml(page.mounted)} ${escapePriceHtml(page.peak)} ${escapePriceHtml(page.archived)}</p>
    </div>
    <h2>${escapePriceHtml(page.examplesTitle)}</h2>
    <p class="vat-note">${escapePriceHtml(page.vatNote)}</p>
    <div class="example-list">
      ${PRICE_EXAMPLES.map((example) => {
        const quote = quoteFleetSync(example.vehicles, example.machines, example.trailers, example.attachments);
        return `<article class="example-card">
          <h3>${escapePriceHtml(page[example.titleKey])}</h3>
          ${renderPriceQuote(lang, page, quote)}
        </article>`;
      }).join("")}
    </div>
    <h2>${escapePriceHtml(page.otherTitle)}</h2>
    <p>${escapePriceHtml(page.otherIntro)}</p>
    <div class="other-products">${others}</div>`;

  const vehiclesInput = document.getElementById("calc-vehicles");
  const machinesInput = document.getElementById("calc-machines");
  const trailersInput = document.getElementById("calc-trailers");
  const attachmentsInput = document.getElementById("calc-attachments");
  const result = document.getElementById("calc-result");
  vehiclesInput.value = vehicleValue;
  machinesInput.value = machineValue;
  trailersInput.value = trailerValue;
  attachmentsInput.value = attachmentValue;

  const update = () => {
    const quote = quoteFleetSync(
      vehiclesInput.value,
      machinesInput.value,
      trailersInput.value,
      attachmentsInput.value
    );
    result.innerHTML = renderPriceQuote(lang, page, quote);
  };

  [vehiclesInput, machinesInput, trailersInput, attachmentsInput].forEach((input) => {
    input.addEventListener("input", update);
  });
  update();
}
