/**
 * Draft terms for iqFleetSync. Plain language, not legal advice.
 * The visible note says the provider must review the text before publishing.
 */
const TERMS_PAGE = {
  fi: {
    metaTitle: "Käyttöehdot | IQSoftCore",
    metaDescription: "iqFleetSync-palvelun käyttöehdot. Luonnos.",
    title: "Käyttöehdot",
    draft: "Luonnos. Tämä on selkokielinen luonnos iqFleetSync-palvelun käyttöehdoiksi. Se ei ole oikeudellinen neuvo. Palveluntarjoajan on tarkistettava teksti ennen julkaisua.",
    updated: "Luonnos päivitetty 2026-09-30.",
    scope: "Nämä ehdot koskevat iqFleetSync-palvelua. IQSoftCoren muut tuotteet eivät kuulu näihin ehtoihin, ellei siitä ole erikseen sovittu.",
    sections: [
      ["1. Palveluntarjoaja", ["Palveluntarjoaja on toiminimi iqsoftcore, joka toimii nimellä IQSoftCore, Suomi. Yhteys: info@iqsoftcore.fi ja +358 45 133 4009."]],
      ["2. Palvelu", [
        "iqFleetSync on verkkopalvelu kaluston huoltoon osoitteessa fleetsync.iqsoftcore.fi. Palvelu on moniasiakasympäristö: kunkin asiakasyrityksen tiedot pidetään erillään.",
        "Kuljettaja lukee koneessa tai ajoneuvossa olevan QR-tarran ja avaa tavallisen mobiilisivun. Erillistä sovellusta ei asenneta. Kirjautuminen tapahtuu samassa välilehdessä sähköpostiin tulevalla 6-numeroisella koodilla. Kuljettaja voi ilmoittaa kilometrit tai käyttötunnit sekä viat.",
        "Ylläpito- ja huoltopuolella ovat kalustoluettelo, huolto- ja korjaushistoria, osavaihdot, tarkastusmuistutukset, mahdollisuus liittää perävaunu kuorma-autoon sekä sisäänrakennettu ohjekeskus.",
      ]],
      ["3. Kokeilu", ["Uusi asiakas voi kokeilla palvelua 30 päivää ilmaiseksi. Kokeilun alkaessa ei tarvita maksukorttia. Kokeilun voi lopettaa milloin tahansa ennen sen päättymistä, eikä siitä tule maksua."]],
      ["4. Hinnat ja laskutus", [
        "Hinnat alv 0 %. Voimassa oleva hinnasto on osa näitä ehtoja.",
        "Perusmaksu on 10,00 € kuukaudessa asiakasyritystä kohden. Sen lisäksi veloitetaan ajoneuvoista ja koneista portaittain: ensimmäiset 15 yksikköä 1,50 €, seuraavat yksiköt 16–50 hintaan 1,30 €, yksiköt 51–100 hintaan 1,10 € ja sitä suuremmat hintaan 0,90 € kultakin yksiköltä.",
        "Perävaunu on puoli yksikköä eli 50 % ajoneuvon tai koneen hinnasta samassa portaassa. Asennettu laite on maksuton. Käyttäjämäärää ei ole rajoitettu, eikä käyttäjistä veloiteta erikseen.",
        "Kuukauden hinta lasketaan kyseisen kalenterikuukauden suurimman yksikkömäärän mukaan. Maksullinen käyttö laskutetaan kuukausittain. Maksutapa on se, jonka palvelu näyttää maksuhetkellä.",
      ]],
      ["5. Vain luku -tila", ["Jos kokeilu päättyy eikä maksua ole tehty, tili siirtyy vain luku -tilaan. Vain luku -tilassa tallennettuja tietoja voi tarkastella, mutta uusia ilmoituksia ja muutoksia ei voi tallentaa, ennen kuin maksu on tehty."]],
      ["6. Tietojen säilytys", [
        "Asiakkaan palveluun tallentamat tiedot säilytetään kokeilun jälkeen sekä vain luku -tilassa ja peruutuksen jälkeen, jotta tietoja voi vielä lukea.",
        "Asiakas voi pyytää tietojensa poistoa osoitteeseen info@iqsoftcore.fi. Palveluntarjoaja poistaa tai anonymisoi tiedot, kun pyyntö on käsitelty, ellei laki tai kirjanpito edellytä pidempää säilytystä.",
      ]],
      ["7. Peruutus", ["Asiakas voi peruuttaa maksullisen käytön palvelussa tai sähköpostitse info@iqsoftcore.fi. Peruutus tulee voimaan sen laskutuskauden lopussa, joka on jo alkanut. Jo laskutettua kuukautta ei palauteta, ellei pakottava laki sitä vaadi. Kokeilun keskeyttäminen ei maksa mitään. Peruutuksen jälkeen tili on vain luku -tilassa, ja tiedot säilytetään edellä kuvatulla tavalla."]],
      ["8. Asiakkaan vastuu", [
        "Asiakas vastaa omista käyttäjistään ja siitä, kenelle hän antaa pääsyn. Asiakas vastaa myös siitä, että ilmoitetut kilometrit, käyttötunnit, viat ja muut tiedot saa tallentaa palveluun.",
        "Palvelu on kirjaamisen työkalu. Se ei korvaa koneen tai ajoneuvon tarkastusta, huoltoa eikä päätöstä siitä, onko kalusto turvallista käyttää.",
      ]],
      ["9. Saatavuus", ["Palvelua pidetään käytettävissä kohtuullisin toimin. Huolto, vika tai tietoliikenne voi aiheuttaa katkon. Palvelu tarjotaan sellaisena kuin se on."]],
      ["10. Vastuunrajoitus", [
        "Siltä osin kuin Suomen pakottava laki sen sallii, palveluntarjoaja ei vastaa välillisistä vahingoista, saamatta jääneestä tuotosta eikä menetetyistä tiedoista.",
        "Korvausvastuu välittömästä vahingosta on enintään niiden maksujen suuruinen, jotka asiakas on maksanut iqFleetSyncistä vahinkoa edeltäneiden 12 kuukauden aikana. Jos maksuja ei ole ollut, tämä enimmäismäärä on 0 €.",
        "Rajoitus ei koske vahinkoa, joka on aiheutettu tahallaan tai törkeällä huolimattomuudella, eikä muutakaan vastuuta, jota ei voi lain mukaan rajoittaa.",
      ]],
      ["11. Muutokset", ["Palveluntarjoaja voi muuttaa näitä ehtoja ja hintoja. Muutoksesta kerrotaan palvelussa tai sähköpostitse etukäteen. Jos asiakas ei hyväksy muutosta, hän voi peruuttaa käytön ennen kuin muutos tulee voimaan. Käytön jatkaminen muutoksen jälkeen tarkoittaa, että asiakas hyväksyy päivitetyt ehdot."]],
      ["12. Sovellettava laki", ["Ehtoihin sovelletaan Suomen lakia. Erimielisyys pyritään ratkaisemaan ensin yhdessä. Ellei se onnistu, riidan käsittelee palveluntarjoajan kotipaikan käräjäoikeus Suomessa."]],
      ["13. Yhteystiedot", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Hinnasto",
    product: "iqFleetSync",
    home: "Etusivu",
  },
  en: {
    metaTitle: "Terms of use | IQSoftCore",
    metaDescription: "Terms of use for the iqFleetSync service. Draft.",
    title: "Terms of use",
    draft: "Draft. This is a plain-language draft of the terms for the iqFleetSync service. It is not legal advice. The provider must review the text before it is published.",
    updated: "Draft updated 2026-09-30.",
    scope: "These terms apply to the iqFleetSync service. IQSoftCore’s other products are not covered unless that is agreed separately.",
    sections: [
      ["1. Provider", ["The provider is the Finnish sole proprietorship iqsoftcore, trading as IQSoftCore, Finland. Contact: info@iqsoftcore.fi and +358 45 133 4009."]],
      ["2. The service", [
        "iqFleetSync is a web service for fleet maintenance at fleetsync.iqsoftcore.fi. It is multi-tenant: each customer company’s data is kept separate.",
        "A driver scans a QR sticker on the machine or vehicle and opens a plain mobile web page. There is no app to install. Login happens in the same tab with a 6-digit code sent by email. The driver can report kilometres or engine hours, and defects.",
        "The admin and maintenance side has a fleet list, service and repair history, part changes, inspection reminders, the option to pair a trailer with a truck, and a built-in help center.",
      ]],
      ["3. Trial", ["A new customer can try the service free for 30 days. No payment card is required to start the trial. The trial can be stopped at any time before it ends, and that does not create a charge."]],
      ["4. Prices and billing", [
        "Prices are VAT 0%. The current pricing page is part of these terms.",
        "The base fee is 10.00 € per month per customer company. Vehicles and machines are then charged in tiers: the first 15 units at 1.50 €, units 16–50 at 1.30 €, units 51–100 at 1.10 €, and units above that at 0.90 € each.",
        "A trailer is half a unit, which is 50% of the vehicle or machine price in the same tier. Mounted equipment is free. The number of users is unlimited, and users are not charged separately.",
        "The monthly price uses the highest unit count in that calendar month. Paid use is billed monthly. The payment method is the one the service shows at the time of payment.",
      ]],
      ["5. Read-only mode", ["If the trial ends and no payment has been made, the account becomes read-only. In read-only mode the saved data can still be viewed, but new reports and changes cannot be saved until payment is made."]],
      ["6. Keeping data", [
        "Data the customer has stored in the service is kept after the trial, in read-only mode, and after cancellation, so that it can still be read.",
        "The customer can ask for the data to be deleted by emailing info@iqsoftcore.fi. The provider deletes or anonymises the data once the request has been handled, unless the law or bookkeeping requires it to be kept longer.",
      ]],
      ["7. Cancellation", ["The customer can cancel paid use in the service or by email to info@iqsoftcore.fi. Cancellation takes effect at the end of the billing period that has already started. A month that has already been billed is not refunded, unless mandatory law requires it. Stopping the trial does not cost anything. After cancellation the account is read-only, and the data is kept as described above."]],
      ["8. The customer’s responsibility", [
        "The customer is responsible for their own users and for who is given access. The customer is also responsible for having the right to store the kilometres, engine hours, defects, and other data they enter.",
        "The service is a tool for recording. It does not replace an inspection or maintenance of a machine or vehicle, or the decision about whether the fleet is safe to use.",
      ]],
      ["9. Availability", ["The service is kept available with reasonable effort. Maintenance, a fault, or the network may cause a break. The service is provided as it is."]],
      ["10. Limit of liability", [
        "To the extent Finnish mandatory law allows it, the provider is not liable for indirect damage, lost profit, or lost data.",
        "Liability for direct damage is limited to the fees the customer has paid for iqFleetSync during the 12 months before the damage. If no fees have been paid, that cap is 0 €.",
        "The limit does not apply to damage caused intentionally or by gross negligence, or to any other liability that cannot be limited by law.",
      ]],
      ["11. Changes", ["The provider may change these terms and the prices. A change is told in advance in the service or by email. If the customer does not accept the change, they can cancel before it takes effect. Continuing to use the service after the change means the customer accepts the updated terms."]],
      ["12. Governing law", ["These terms are governed by the law of Finland. A disagreement is first handled between the parties. If that does not resolve it, the case is heard by the district court of the provider’s domicile in Finland."]],
      ["13. Contact", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Pricing",
    product: "iqFleetSync",
    home: "Home",
  },
  sv: {
    metaTitle: "Användarvillkor | IQSoftCore",
    metaDescription: "Användarvillkor för tjänsten iqFleetSync. Utkast.",
    title: "Användarvillkor",
    draft: "Utkast. Det här är ett utkast på klarspråk till villkoren för iqFleetSync. Det är inte juridisk rådgivning. Leverantören måste granska texten innan den publiceras.",
    updated: "Utkast uppdaterat 2026-09-30.",
    scope: "Villkoren gäller tjänsten iqFleetSync. IQSoftCores övriga produkter omfattas inte, om det inte avtalas särskilt.",
    sections: [
      ["1. Leverantör", ["Leverantören är den finska enskilda firman iqsoftcore, som verkar under namnet IQSoftCore, Finland. Kontakt: info@iqsoftcore.fi och +358 45 133 4009."]],
      ["2. Tjänsten", ["iqFleetSync är en webbtjänst för underhåll av en flotta på fleetsync.iqsoftcore.fi. Tjänsten har flera kunder: varje kundföretags uppgifter hålls åtskilda.", "Föraren skannar en QR-dekal och öppnar en vanlig mobilsida. Inget installeras. Inloggning sker i samma flik med en 6-siffrig kod via e-post. Föraren kan rapportera kilometer eller motortimmar och fel.", "Administrationen har en flottlista, service- och reparationshistorik, byte av delar, påminnelser om inspektion, möjlighet att koppla ett släp till en lastbil och en inbyggd hjälpcentral."]],
      ["3. Provperiod", ["En ny kund kan prova tjänsten gratis i 30 dagar. Inget kort behövs för att börja. Provperioden kan avbrytas när som helst innan den tar slut, utan kostnad."]],
      ["4. Priser och fakturering", ["Priserna är moms 0 %. Prislistan är en del av villkoren.", "Grundavgiften är 10,00 € per månad och kundföretag. Fordon och maskiner debiteras stegvis: de första 15 enheterna 1,50 €, enheterna 16–50 1,30 €, enheterna 51–100 1,10 € och enheter däröver 0,90 € styck.", "Ett släp är en halv enhet, alltså 50 % av priset för ett fordon eller en maskin i samma steg. Monterad utrustning är gratis. Antalet användare är obegränsat.", "Månadspriset utgår från det högsta enhetsantalet under kalendermånaden. Betald användning faktureras varje månad."]],
      ["5. Skrivskyddat läge", ["Om provperioden tar slut och ingen betalning har gjorts blir kontot skrivskyddat. Sparade uppgifter kan läsas, men nya anmälningar och ändringar kan inte sparas förrän betalning har gjorts."]],
      ["6. Bevarande av uppgifter", ["Uppgifter som kunden har sparat behålls efter provperioden, i skrivskyddat läge och efter uppsägning, så att de fortfarande kan läsas.", "Kunden kan be om radering via info@iqsoftcore.fi. Leverantören raderar eller anonymiserar uppgifterna när begäran har hanterats, om inte lag eller bokföring kräver längre förvaring."]],
      ["7. Uppsägning", ["Kunden kan säga upp betald användning i tjänsten eller via e-post till info@iqsoftcore.fi. Uppsägningen gäller från slutet av den påbörjade faktureringsperioden. En redan fakturerad månad återbetalas inte, om inte tvingande lag kräver det. Att avbryta provperioden kostar inget. Därefter är kontot skrivskyddat och uppgifterna behålls."]],
      ["8. Kundens ansvar", ["Kunden ansvarar för sina användare och för vem som får tillgång. Kunden ansvarar också för att få spara de kilometer, motortimmar, fel och andra uppgifter som läggs in.", "Tjänsten är ett verktyg för registrering. Den ersätter inte kontroll, underhåll eller beslutet om flottan är säker att använda."]],
      ["9. Tillgänglighet", ["Tjänsten hålls tillgänglig med rimliga åtgärder. Underhåll, fel eller nätet kan orsaka avbrott. Tjänsten tillhandahålls som den är."]],
      ["10. Ansvarsbegränsning", ["I den mån tvingande finsk lag tillåter det ansvarar leverantören inte för indirekt skada, utebliven vinst eller förlorade uppgifter.", "Ansvaret för direkt skada är högst de avgifter kunden har betalat för iqFleetSync under de 12 månader som föregick skadan. Om inga avgifter har betalats är taket 0 €.", "Begränsningen gäller inte skada som orsakats uppsåtligen eller av grov oaktsamhet, och inte heller ansvar som inte får begränsas enligt lag."]],
      ["11. Ändringar", ["Leverantören kan ändra villkoren och priserna. En ändring meddelas i förväg i tjänsten eller via e-post. Om kunden inte godkänner ändringen kan användningen sägas upp innan den träder i kraft. Fortsatt användning betyder att kunden godkänner de uppdaterade villkoren."]],
      ["12. Tillämplig lag", ["Finsk lag tillämpas. En oenighet försöks först lösas tillsammans. Om det inte lyckas prövas tvisten av tingsrätten på leverantörens hemort i Finland."]],
      ["13. Kontakt", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Priser",
    product: "iqFleetSync",
    home: "Startsida",
  },
  no: {
    metaTitle: "Vilkår | IQSoftCore",
    metaDescription: "Vilkår for tjenesten iqFleetSync. Utkast.",
    title: "Vilkår",
    draft: "Utkast. Dette er et utkast på klart språk til vilkårene for iqFleetSync. Det er ikke juridisk råd. Leverandøren må gå gjennom teksten før den publiseres.",
    updated: "Utkast oppdatert 2026-09-30.",
    scope: "Vilkårene gjelder tjenesten iqFleetSync. IQSoftCores andre produkter er ikke omfattet, med mindre det er avtalt særskilt.",
    sections: [
      ["1. Leverandør", ["Leverandøren er det finske enkeltpersonforetaket iqsoftcore, som driver under navnet IQSoftCore, Finland. Kontakt: info@iqsoftcore.fi og +358 45 133 4009."]],
      ["2. Tjenesten", ["iqFleetSync er en nettjeneste for vedlikehold av flåte på fleetsync.iqsoftcore.fi. Tjenesten har flere kunder: hvert kundeforetaks data holdes atskilt.", "Sjåføren skanner et QR-merke og åpner en vanlig side i mobilnettleseren. Ingenting installeres. Innlogging skjer i samme fane med en 6-sifret kode på e-post. Sjåføren kan melde kilometer eller motortimer og feil.", "Administrasjonen har en flåteliste, service- og reparasjonshistorikk, bytte av deler, påminnelser om kontroll, mulighet til å koble en tilhenger til en lastebil og et innebygd hjelpesenter."]],
      ["3. Prøveperiode", ["En ny kunde kan prøve tjenesten gratis i 30 dager. Ingen kort trengs for å starte. Prøveperioden kan stoppes når som helst før den er slutt, uten kostnad."]],
      ["4. Priser og fakturering", ["Prisene er mva. 0 %. Prislisten er en del av vilkårene.", "Grunnavgiften er 10,00 € per måned per kundeforetak. Kjøretøy og maskiner faktureres trinnvis: de første 15 enhetene 1,50 €, enhetene 16–50 1,30 €, enhetene 51–100 1,10 € og enheter over det 0,90 € hver.", "En tilhenger er en halv enhet, altså 50 % av prisen for et kjøretøy eller en maskin i samme trinn. Montert utstyr er gratis. Antall brukere er ubegrenset.", "Månedsprisen bruker det høyeste enhetsantallet i kalendermåneden. Betalt bruk faktureres hver måned."]],
      ["5. Skrivebeskyttet", ["Hvis prøveperioden slutter og det ikke er betalt, blir kontoen skrivebeskyttet. Lagrede data kan leses, men nye meldinger og endringer kan ikke lagres før det er betalt."]],
      ["6. Oppbevaring", ["Data kunden har lagret, beholdes etter prøveperioden, i skrivebeskyttet tilstand og etter oppsigelse, slik at de fortsatt kan leses.", "Kunden kan be om sletting til info@iqsoftcore.fi. Leverandøren sletter eller anonymiserer dataene når forespørselen er behandlet, med mindre lov eller regnskap krever lengre oppbevaring."]],
      ["7. Oppsigelse", ["Kunden kan si opp betalt bruk i tjenesten eller på e-post til info@iqsoftcore.fi. Oppsigelsen gjelder fra slutten av den påbegynte fakturaperioden. En måned som allerede er fakturert, betales ikke tilbake, med mindre ufravikelig lov krever det. Å stoppe prøveperioden koster ingenting. Deretter er kontoen skrivebeskyttet, og dataene beholdes."]],
      ["8. Kundens ansvar", ["Kunden svarer for egne brukere og for hvem som får tilgang. Kunden svarer også for at kilometer, motortimer, feil og andre data kan lagres.", "Tjenesten er et verktøy for registrering. Den erstatter ikke kontroll, vedlikehold eller avgjørelsen av om flåten er trygg å bruke."]],
      ["9. Tilgjengelighet", ["Tjenesten holdes tilgjengelig med rimelig innsats. Vedlikehold, feil eller nett kan gi avbrudd. Tjenesten leveres som den er."]],
      ["10. Ansvarsbegrensning", ["Så langt ufravikelig finsk lov tillater det, svarer leverandøren ikke for indirekte tap, tapt fortjeneste eller tapte data.", "Ansvaret for direkte tap er høyst de beløpene kunden har betalt for iqFleetSync i de 12 månedene før skaden. Hvis ingenting er betalt, er taket 0 €.", "Begrensningen gjelder ikke skade som er forårsaket forsettlig eller ved grov uaktsomhet, og heller ikke ansvar som ikke kan begrenses etter loven."]],
      ["11. Endringer", ["Leverandøren kan endre vilkårene og prisene. En endring varsles på forhånd i tjenesten eller på e-post. Hvis kunden ikke godtar endringen, kan bruken sies opp før den trer i kraft. Videre bruk betyr at kunden godtar de oppdaterte vilkårene."]],
      ["12. Lovvalg", ["Finsk lov gjelder. En uenighet forsøkes først løst sammen. Hvis det ikke lykkes, behandles saken av tingretten på leverandørens hjemsted i Finland."]],
      ["13. Kontakt", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Priser",
    product: "iqFleetSync",
    home: "Forside",
  },
  da: {
    metaTitle: "Vilkår | IQSoftCore",
    metaDescription: "Vilkår for tjenesten iqFleetSync. Udkast.",
    title: "Vilkår",
    draft: "Udkast. Dette er et udkast i klart sprog til vilkårene for iqFleetSync. Det er ikke juridisk rådgivning. Udbyderen skal gennemgå teksten, før den offentliggøres.",
    updated: "Udkast opdateret 2026-09-30.",
    scope: "Vilkårene gælder tjenesten iqFleetSync. IQSoftCores andre produkter er ikke omfattet, medmindre det er aftalt særskilt.",
    sections: [
      ["1. Udbyder", ["Udbyderen er den finske enkeltmandsvirksomhed iqsoftcore, der driver virksomhed som IQSoftCore, Finland. Kontakt: info@iqsoftcore.fi og +358 45 133 4009."]],
      ["2. Tjenesten", ["iqFleetSync er en webtjeneste til vedligehold af en flåde på fleetsync.iqsoftcore.fi. Tjenesten har flere kunder: hver kundes data holdes adskilt.", "Chaufføren scanner et QR-mærke og åbner en almindelig mobilside. Intet installeres. Login sker i samme fane med en 6-cifret kode på e-mail. Chaufføren kan melde kilometer eller motortimer og fejl.", "Administrationen har en flådeliste, service- og reparationshistorik, udskiftning af dele, påmindelser om eftersyn, mulighed for at koble en anhænger til en lastbil og et indbygget hjælpecenter."]],
      ["3. Prøve", ["En ny kunde kan prøve tjenesten gratis i 30 dage. Der kræves ikke et kort for at starte. Prøven kan stoppes når som helst før den slutter, uden betaling."]],
      ["4. Priser og fakturering", ["Priserne er moms 0 %. Prislisten er en del af vilkårene.", "Grundgebyret er 10,00 € pr. måned pr. kundevirksomhed. Køretøjer og maskiner faktureres trinvist: de første 15 enheder 1,50 €, enhederne 16–50 1,30 €, enhederne 51–100 1,10 € og enheder derover 0,90 € hver.", "En anhænger er en halv enhed, altså 50 % af prisen for et køretøj eller en maskine i samme trin. Monteret udstyr er gratis. Antallet af brugere er ubegrænset.", "Månedsprisen bruger det højeste enhedstal i kalendermåneden. Betalt brug faktureres hver måned."]],
      ["5. Skrivebeskyttet", ["Hvis prøven slutter, og der ikke er betalt, bliver kontoen skrivebeskyttet. Gemte data kan læses, men nye meldinger og ændringer kan ikke gemmes, før der er betalt."]],
      ["6. Opbevaring", ["Data, som kunden har gemt, beholdes efter prøven, i skrivebeskyttet tilstand og efter opsigelse, så de stadig kan læses.", "Kunden kan bede om sletning på info@iqsoftcore.fi. Udbyderen sletter eller anonymiserer data, når anmodningen er behandlet, medmindre lov eller bogføring kræver længere opbevaring."]],
      ["7. Opsigelse", ["Kunden kan opsige betalt brug i tjenesten eller på e-mail til info@iqsoftcore.fi. Opsigelsen gælder fra slutningen af den påbegyndte faktureringsperiode. En måned, der allerede er faktureret, refunderes ikke, medmindre ufravigelig lov kræver det. At stoppe prøven koster ikke noget. Derefter er kontoen skrivebeskyttet, og data beholdes."]],
      ["8. Kundens ansvar", ["Kunden har ansvaret for sine brugere og for, hvem der får adgang. Kunden har også ansvaret for, at kilometer, motortimer, fejl og andre data må gemmes.", "Tjenesten er et værktøj til registrering. Den erstatter ikke eftersyn, vedligehold eller afgørelsen af, om flåden er sikker at bruge."]],
      ["9. Tilgængelighed", ["Tjenesten holdes tilgængelig med en rimelig indsats. Vedligehold, fejl eller nettet kan give afbrydelse. Tjenesten leveres, som den er."]],
      ["10. Ansvarsbegrænsning", ["I det omfang ufravigelig finsk lov tillader det, hæfter udbyderen ikke for indirekte tab, tabt fortjeneste eller mistede data.", "Ansvaret for direkte tab er højst de beløb, kunden har betalt for iqFleetSync i de 12 måneder før skaden. Hvis intet er betalt, er loftet 0 €.", "Begrænsningen gælder ikke skade, der er forvoldt forsætligt eller ved grov uagtsomhed, og heller ikke ansvar, som ikke må begrænses efter loven."]],
      ["11. Ændringer", ["Udbyderen kan ændre vilkårene og priserne. En ændring varsles på forhånd i tjenesten eller på e-mail. Hvis kunden ikke accepterer ændringen, kan brugen opsiges, før den træder i kraft. Fortsat brug betyder, at kunden accepterer de opdaterede vilkår."]],
      ["12. Lovvalg", ["Finsk lov gælder. En uenighed forsøges først løst i fællesskab. Hvis det ikke lykkes, behandles sagen ved byretten på udbyderens hjemsted i Finland."]],
      ["13. Kontakt", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Priser",
    product: "iqFleetSync",
    home: "Forside",
  },
  de: {
    metaTitle: "Nutzungsbedingungen | IQSoftCore",
    metaDescription: "Nutzungsbedingungen für den Dienst iqFleetSync. Entwurf.",
    title: "Nutzungsbedingungen",
    draft: "Entwurf. Dies ist ein Entwurf der Bedingungen für iqFleetSync in einfacher Sprache. Er ist keine Rechtsberatung. Der Anbieter muss den Text vor der Veröffentlichung prüfen.",
    updated: "Entwurf aktualisiert am 2026-09-30.",
    scope: "Diese Bedingungen gelten für den Dienst iqFleetSync. Andere Produkte von IQSoftCore sind nicht erfasst, sofern das nicht gesondert vereinbart wird.",
    sections: [
      ["1. Anbieter", ["Anbieter ist das finnische Einzelunternehmen iqsoftcore, das unter dem Namen IQSoftCore, Finnland, auftritt. Kontakt: info@iqsoftcore.fi und +358 45 133 4009."]],
      ["2. Der Dienst", ["iqFleetSync ist ein Webdienst für die Wartung eines Bestands unter fleetsync.iqsoftcore.fi. Der Dienst ist mehrmandantenfähig: die Daten jedes Kundenunternehmens bleiben getrennt.", "Die fahrende Person scannt einen QR-Aufkleber und öffnet eine gewöhnliche Mobilseite. Es wird nichts installiert. Die Anmeldung erfolgt im selben Tab mit einem 6-stelligen Code per E-Mail. Gemeldet werden können Kilometer oder Betriebsstunden sowie Mängel.", "Die Verwaltung umfasst eine Bestandsliste, Wartungs- und Reparaturhistorie, Teilewechsel, Erinnerungen an Prüfungen, die Zuordnung eines Anhängers zu einem Lkw und ein eingebautes Hilfe-Center."]],
      ["3. Test", ["Ein neuer Kunde kann den Dienst 30 Tage kostenlos testen. Zum Start ist keine Karte nötig. Der Test kann jederzeit vor dem Ende beendet werden, ohne dass Kosten entstehen."]],
      ["4. Preise und Abrechnung", ["Die Preise sind MwSt. 0 %. Die Preisliste ist Teil dieser Bedingungen.", "Die Grundgebühr beträgt 10,00 € pro Monat und Kundenunternehmen. Fahrzeuge und Maschinen werden gestaffelt berechnet: die ersten 15 Einheiten 1,50 €, die Einheiten 16–50 1,30 €, die Einheiten 51–100 1,10 € und weitere Einheiten 0,90 € je Einheit.", "Ein Anhänger ist eine halbe Einheit, also 50 % des Preises eines Fahrzeugs oder einer Maschine in derselben Stufe. Anbaugeräte sind kostenlos. Die Zahl der Nutzer ist unbegrenzt.", "Der Monatspreis verwendet die höchste Einheitenanzahl im Kalendermonat. Die kostenpflichtige Nutzung wird monatlich berechnet."]],
      ["5. Nur-Lesen", ["Endet der Test ohne Zahlung, wird das Konto nur lesbar. Gespeicherte Daten können angesehen werden, neue Meldungen und Änderungen lassen sich erst nach Zahlung speichern."]],
      ["6. Aufbewahrung", ["Daten, die der Kunde gespeichert hat, bleiben nach dem Test, im Nur-Lesen-Modus und nach der Kündigung erhalten, damit sie weiter gelesen werden können.", "Der Kunde kann die Löschung an info@iqsoftcore.fi verlangen. Der Anbieter löscht oder anonymisiert die Daten, sobald das Verlangen bearbeitet ist, sofern Gesetz oder Buchhaltung keine längere Aufbewahrung verlangen."]],
      ["7. Kündigung", ["Der Kunde kann die kostenpflichtige Nutzung im Dienst oder per E-Mail an info@iqsoftcore.fi kündigen. Die Kündigung gilt zum Ende des bereits begonnenen Abrechnungszeitraums. Ein bereits berechneter Monat wird nicht erstattet, sofern zwingendes Recht das nicht verlangt. Das Beenden des Tests kostet nichts. Danach ist das Konto nur lesbar, und die Daten bleiben erhalten."]],
      ["8. Verantwortung des Kunden", ["Der Kunde ist für die eigenen Nutzer und dafür verantwortlich, wer Zugang erhält. Der Kunde ist auch dafür verantwortlich, dass Kilometer, Betriebsstunden, Mängel und andere Daten gespeichert werden dürfen.", "Der Dienst ist ein Werkzeug zum Erfassen. Er ersetzt nicht Prüfung, Wartung oder die Entscheidung, ob der Bestand sicher genutzt werden kann."]],
      ["9. Verfügbarkeit", ["Der Dienst wird mit zumutbarem Aufwand verfügbar gehalten. Wartung, ein Fehler oder das Netz können eine Unterbrechung verursachen. Der Dienst wird bereitgestellt, wie er ist."]],
      ["10. Haftungsbegrenzung", ["Soweit zwingendes finnisches Recht es erlaubt, haftet der Anbieter nicht für indirekte Schäden, entgangenen Gewinn oder verlorene Daten.", "Die Haftung für unmittelbaren Schaden ist auf die Entgelte begrenzt, die der Kunde in den 12 Monaten vor dem Schaden für iqFleetSync gezahlt hat. Wenn nichts gezahlt wurde, ist die Obergrenze 0 €.", "Die Grenze gilt nicht für vorsätzlich oder grob fahrlässig verursachten Schaden und nicht für eine Haftung, die gesetzlich nicht beschränkt werden darf."]],
      ["11. Änderungen", ["Der Anbieter kann diese Bedingungen und die Preise ändern. Eine Änderung wird vorab im Dienst oder per E-Mail mitgeteilt. Wer die Änderung nicht annimmt, kann vor ihrem Inkrafttreten kündigen. Weitere Nutzung bedeutet, dass der Kunde die aktualisierten Bedingungen annimmt."]],
      ["12. Anwendbares Recht", ["Es gilt finnisches Recht. Eine Meinungsverschiedenheit wird zuerst gemeinsam geklärt. Gelingt das nicht, ist das Amtsgericht am Sitz des Anbieters in Finnland zuständig."]],
      ["13. Kontakt", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Preise",
    product: "iqFleetSync",
    home: "Startseite",
  },
  nl: {
    metaTitle: "Gebruiksvoorwaarden | IQSoftCore",
    metaDescription: "Gebruiksvoorwaarden voor de dienst iqFleetSync. Concept.",
    title: "Gebruiksvoorwaarden",
    draft: "Concept. Dit is een concept in gewone taal van de voorwaarden voor iqFleetSync. Het is geen juridisch advies. De aanbieder moet de tekst nakijken vóór publicatie.",
    updated: "Concept bijgewerkt op 2026-09-30.",
    scope: "Deze voorwaarden gelden voor de dienst iqFleetSync. Andere producten van IQSoftCore vallen er niet onder, tenzij dat apart is afgesproken.",
    sections: [
      ["1. Aanbieder", ["De aanbieder is de Finse eenmanszaak iqsoftcore, die werkt onder de naam IQSoftCore, Finland. Contact: info@iqsoftcore.fi en +358 45 133 4009."]],
      ["2. De dienst", ["iqFleetSync is een webdienst voor onderhoud van een park op fleetsync.iqsoftcore.fi. De dienst heeft meerdere klanten: de gegevens van elk klantbedrijf blijven apart.", "De bestuurder scant een QR-sticker en opent een gewone mobiele pagina. Er is niets te installeren. Inloggen gebeurt in hetzelfde tabblad met een 6-cijferige code per e-mail. Kilometers of motoruren en gebreken kunnen worden gemeld.", "Het beheer heeft een parlijst, onderhouds- en reparatiegeschiedenis, onderdeelwissels, herinneringen voor keuringen, de mogelijkheid een aanhanger aan een vrachtwagen te koppelen en een ingebouwd helpcentrum."]],
      ["3. Proefperiode", ["Een nieuwe klant kan de dienst 30 dagen gratis proberen. Er is geen kaart nodig om te starten. De proef kan op elk moment vóór het einde worden gestopt, zonder kosten."]],
      ["4. Prijzen en facturering", ["De prijzen zijn btw 0%. De prijslijst hoort bij deze voorwaarden.", "Het basisbedrag is 10,00 € per maand per klantbedrijf. Voertuigen en machines worden gestaffeld gerekend: de eerste 15 eenheden 1,50 €, eenheden 16–50 1,30 €, eenheden 51–100 1,10 € en eenheden daarboven 0,90 € per stuk.", "Een aanhanger is een halve eenheid, dus 50% van de prijs van een voertuig of machine in dezelfde staffel. Gemonteerde apparatuur is gratis. Het aantal gebruikers is onbeperkt.", "De maandprijs gebruikt het hoogste aantal eenheden in die kalendermaand. Betaald gebruik wordt maandelijks gefactureerd."]],
      ["5. Alleen lezen", ["Als de proef eindigt en er niet is betaald, wordt het account alleen-lezen. Opgeslagen gegevens kunnen worden bekeken, maar nieuwe meldingen en wijzigingen kunnen pas worden opgeslagen na betaling."]],
      ["6. Bewaren van gegevens", ["Gegevens die de klant heeft opgeslagen, blijven bewaard na de proef, in de alleen-lezenstand en na opzegging, zodat ze nog gelezen kunnen worden.", "De klant kan verwijdering vragen via info@iqsoftcore.fi. De aanbieder verwijdert of anonimiseert de gegevens zodra het verzoek is afgehandeld, tenzij wet of boekhouding langere bewaring vraagt."]],
      ["7. Opzegging", ["De klant kan betaald gebruik opzeggen in de dienst of per e-mail aan info@iqsoftcore.fi. De opzegging gaat in aan het einde van de al begonnen factuurperiode. Een maand die al is gefactureerd, wordt niet terugbetaald, tenzij dwingend recht dat vraagt. De proef stoppen kost niets. Daarna is het account alleen-lezen en blijven de gegevens bewaard."]],
      ["8. Verantwoordelijkheid van de klant", ["De klant is verantwoordelijk voor de eigen gebruikers en voor wie toegang krijgt. De klant is er ook verantwoordelijk voor dat kilometers, motoruren, gebreken en andere gegevens mogen worden opgeslagen.", "De dienst is een hulpmiddel om te registreren. Hij vervangt geen keuring, onderhoud of het besluit of het park veilig te gebruiken is."]],
      ["9. Beschikbaarheid", ["De dienst wordt met redelijke inspanning beschikbaar gehouden. Onderhoud, een storing of het netwerk kan een onderbreking geven. De dienst wordt geleverd zoals hij is."]],
      ["10. Beperking van aansprakelijkheid", ["Voor zover dwingend Fins recht dat toestaat, is de aanbieder niet aansprakelijk voor indirecte schade, gederfde winst of verloren gegevens.", "De aansprakelijkheid voor directe schade is ten hoogste de bedragen die de klant in de 12 maanden vóór de schade voor iqFleetSync heeft betaald. Als er niets is betaald, is dat plafond 0 €.", "De beperking geldt niet voor schade door opzet of grove nalatigheid, en ook niet voor aansprakelijkheid die wettelijk niet mag worden beperkt."]],
      ["11. Wijzigingen", ["De aanbieder kan deze voorwaarden en de prijzen wijzigen. Een wijziging wordt vooraf in de dienst of per e-mail meegedeeld. Wie de wijziging niet aanvaardt, kan opzeggen vóórdat zij ingaat. Verder gebruik betekent dat de klant de bijgewerkte voorwaarden aanvaardt."]],
      ["12. Toepasselijk recht", ["Fins recht is van toepassing. Een geschil wordt eerst samen opgelost. Lukt dat niet, dan behandelt de rechtbank van de vestigingsplaats van de aanbieder in Finland de zaak."]],
      ["13. Contact", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Prijzen",
    product: "iqFleetSync",
    home: "Home",
  },
  fr: {
    metaTitle: "Conditions d’utilisation | IQSoftCore",
    metaDescription: "Conditions d’utilisation du service iqFleetSync. Projet.",
    title: "Conditions d’utilisation",
    draft: "Projet. Ceci est un projet, en langage clair, des conditions d’iqFleetSync. Ce n’est pas un conseil juridique. Le prestataire doit relire le texte avant publication.",
    updated: "Projet mis à jour le 2026-09-30.",
    scope: "Ces conditions concernent le service iqFleetSync. Les autres produits d’IQSoftCore n’y sont pas soumis, sauf accord distinct.",
    sections: [
      ["1. Prestataire", ["Le prestataire est l’entreprise individuelle finlandaise iqsoftcore, qui opère sous le nom IQSoftCore, Finlande. Contact : info@iqsoftcore.fi et +358 45 133 4009."]],
      ["2. Le service", ["iqFleetSync est un service web de maintenance de parc à l’adresse fleetsync.iqsoftcore.fi. Le service est multi-clients : les données de chaque entreprise cliente restent séparées.", "Le conducteur scanne un autocollant QR et ouvre une page mobile ordinaire. Rien à installer. La connexion se fait dans le même onglet avec un code à 6 chiffres envoyé par e-mail. Il peut signaler les kilomètres ou les heures moteur, et les défauts.", "L’administration comprend la liste du parc, l’historique d’entretien et de réparation, les changements de pièces, les rappels de contrôle, la possibilité d’associer une remorque à un camion et un centre d’aide intégré."]],
      ["3. Essai", ["Un nouveau client peut essayer le service gratuitement pendant 30 jours. Aucune carte n’est demandée pour commencer. L’essai peut être arrêté à tout moment avant la fin, sans frais."]],
      ["4. Prix et facturation", ["Les prix sont TVA 0 %. Le tarif fait partie de ces conditions.", "Le forfait de base est de 10,00 € par mois et par entreprise cliente. Les véhicules et machines sont facturés par paliers : les 15 premières unités à 1,50 €, les unités 16–50 à 1,30 €, les unités 51–100 à 1,10 € et les unités au-delà à 0,90 € chacune.", "Une remorque compte pour une demi-unité, soit 50 % du prix d’un véhicule ou d’une machine dans le même palier. Un équipement monté est gratuit. Le nombre d’utilisateurs est illimité.", "Le prix du mois utilise le nombre d’unités le plus élevé de ce mois civil. L’usage payant est facturé chaque mois."]],
      ["5. Lecture seule", ["Si l’essai se termine sans paiement, le compte passe en lecture seule. Les données enregistrées peuvent être consultées, mais les nouveaux signalements et les modifications ne peuvent pas être enregistrés tant qu’un paiement n’a pas été fait."]],
      ["6. Conservation des données", ["Les données enregistrées par le client sont conservées après l’essai, en lecture seule et après la résiliation, afin de pouvoir encore être lues.", "Le client peut demander leur suppression à info@iqsoftcore.fi. Le prestataire les supprime ou les anonymise une fois la demande traitée, sauf si la loi ou la comptabilité impose une conservation plus longue."]],
      ["7. Résiliation", ["Le client peut résilier l’usage payant dans le service ou par e-mail à info@iqsoftcore.fi. La résiliation prend effet à la fin de la période de facturation déjà commencée. Un mois déjà facturé n’est pas remboursé, sauf si une loi impérative l’exige. Arrêter l’essai ne coûte rien. Ensuite le compte est en lecture seule et les données sont conservées."]],
      ["8. Responsabilité du client", ["Le client répond de ses utilisateurs et des personnes à qui il donne accès. Il répond aussi du droit d’enregistrer les kilomètres, les heures moteur, les défauts et les autres données.", "Le service est un outil d’enregistrement. Il ne remplace pas un contrôle, un entretien, ni la décision de savoir si le parc peut être utilisé en sécurité."]],
      ["9. Disponibilité", ["Le service est maintenu disponible avec un effort raisonnable. Une maintenance, une panne ou le réseau peuvent provoquer une interruption. Le service est fourni tel quel."]],
      ["10. Limite de responsabilité", ["Dans la mesure où la loi finlandaise impérative le permet, le prestataire n’est pas responsable des dommages indirects, du manque à gagner ni des données perdues.", "La responsabilité pour un dommage direct est limitée aux sommes que le client a payées pour iqFleetSync pendant les 12 mois précédant le dommage. Si rien n’a été payé, ce plafond est de 0 €.", "La limite ne s’applique pas à un dommage causé intentionnellement ou par négligence grave, ni à une responsabilité que la loi interdit de limiter."]],
      ["11. Modifications", ["Le prestataire peut modifier ces conditions et les prix. Une modification est annoncée à l’avance dans le service ou par e-mail. Si le client ne l’accepte pas, il peut résilier avant qu’elle ne prenne effet. Continuer à utiliser le service signifie que le client accepte les conditions mises à jour."]],
      ["12. Droit applicable", ["Le droit finlandais s’applique. Un désaccord est d’abord traité entre les parties. À défaut, le tribunal du domicile du prestataire en Finlande est compétent."]],
      ["13. Contact", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Tarifs",
    product: "iqFleetSync",
    home: "Accueil",
  },
  es: {
    metaTitle: "Condiciones de uso | IQSoftCore",
    metaDescription: "Condiciones de uso del servicio iqFleetSync. Borrador.",
    title: "Condiciones de uso",
    draft: "Borrador. Este es un borrador en lenguaje claro de las condiciones de iqFleetSync. No es asesoramiento jurídico. El prestador debe revisar el texto antes de publicarlo.",
    updated: "Borrador actualizado el 2026-09-30.",
    scope: "Estas condiciones se aplican al servicio iqFleetSync. Los demás productos de IQSoftCore no quedan cubiertos, salvo que se acuerde aparte.",
    sections: [
      ["1. Prestador", ["El prestador es el empresario individual finlandés iqsoftcore, que opera como IQSoftCore, Finlandia. Contacto: info@iqsoftcore.fi y +358 45 133 4009."]],
      ["2. El servicio", ["iqFleetSync es un servicio web de mantenimiento de flotas en fleetsync.iqsoftcore.fi. Es multiempresa: los datos de cada empresa cliente se mantienen separados.", "El conductor escanea una pegatina QR y abre una página móvil normal. No hay que instalar nada. El acceso es en la misma pestaña con un código de 6 dígitos enviado por correo. Puede anotar kilómetros u horas de motor y defectos.", "La administración incluye la lista de la flota, el historial de servicio y reparación, los cambios de piezas, los avisos de inspección, la posibilidad de vincular un remolque a un camión y un centro de ayuda integrado."]],
      ["3. Prueba", ["Un cliente nuevo puede probar el servicio gratis durante 30 días. No hace falta tarjeta para empezar. La prueba se puede dejar en cualquier momento antes de que acabe, sin coste."]],
      ["4. Precios y facturación", ["Los precios son IVA 0 %. La lista de precios forma parte de estas condiciones.", "La cuota base es de 10,00 € al mes por empresa cliente. Los vehículos y las máquinas se cobran por tramos: las primeras 15 unidades a 1,50 €, las unidades 16–50 a 1,30 €, las unidades 51–100 a 1,10 € y las que superan 100 a 0,90 € cada una.", "Un remolque es media unidad, es decir el 50 % del precio de un vehículo o una máquina en el mismo tramo. El equipo montado es gratuito. El número de usuarios no está limitado.", "El precio del mes usa el mayor número de unidades de ese mes natural. El uso de pago se factura cada mes."]],
      ["5. Solo lectura", ["Si la prueba termina y no hay pago, la cuenta pasa a solo lectura. Los datos guardados se pueden consultar, pero no se pueden guardar avisos ni cambios nuevos hasta que se pague."]],
      ["6. Conservación de los datos", ["Los datos que el cliente ha guardado se conservan después de la prueba, en solo lectura y después de la cancelación, para que se puedan seguir leyendo.", "El cliente puede pedir su eliminación en info@iqsoftcore.fi. El prestador los elimina o anonimiza cuando la solicitud está atendida, salvo que la ley o la contabilidad exijan conservarlos más tiempo."]],
      ["7. Cancelación", ["El cliente puede cancelar el uso de pago en el servicio o por correo a info@iqsoftcore.fi. La cancelación surte efecto al final del periodo de facturación ya iniciado. Un mes ya facturado no se devuelve, salvo que una ley imperativa lo exija. Dejar la prueba no cuesta nada. Después la cuenta queda en solo lectura y los datos se conservan."]],
      ["8. Responsabilidad del cliente", ["El cliente responde de sus usuarios y de a quién da acceso. También responde de poder guardar los kilómetros, las horas de motor, los defectos y los demás datos.", "El servicio es una herramienta de registro. No sustituye una inspección, un mantenimiento ni la decisión de si la flota es segura de usar."]],
      ["9. Disponibilidad", ["El servicio se mantiene disponible con un esfuerzo razonable. El mantenimiento, un fallo o la red pueden causar una interrupción. El servicio se ofrece tal cual es."]],
      ["10. Límite de responsabilidad", ["En la medida en que lo permita la ley finlandesa imperativa, el prestador no responde de daños indirectos, de lucro cesante ni de datos perdidos.", "La responsabilidad por daño directo se limita a las cantidades que el cliente haya pagado por iqFleetSync en los 12 meses anteriores al daño. Si no se ha pagado nada, ese tope es 0 €.", "El límite no se aplica al daño causado con dolo o negligencia grave, ni a una responsabilidad que la ley no permita limitar."]],
      ["11. Cambios", ["El prestador puede cambiar estas condiciones y los precios. Un cambio se avisa antes en el servicio o por correo. Si el cliente no lo acepta, puede cancelar antes de que entre en vigor. Seguir usando el servicio significa que acepta las condiciones actualizadas."]],
      ["12. Ley aplicable", ["Se aplica la ley de Finlandia. Un desacuerdo se intenta resolver primero entre las partes. Si no se consigue, lo conoce el tribunal del domicilio del prestador en Finlandia."]],
      ["13. Contacto", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Precios",
    product: "iqFleetSync",
    home: "Inicio",
  },
  pt: {
    metaTitle: "Termos de uso | IQSoftCore",
    metaDescription: "Termos de uso do serviço iqFleetSync. Rascunho.",
    title: "Termos de uso",
    draft: "Rascunho. Este é um rascunho, em linguagem simples, dos termos do iqFleetSync. Não é aconselhamento jurídico. O prestador precisa revisar o texto antes da publicação.",
    updated: "Rascunho atualizado em 2026-09-30.",
    scope: "Estes termos valem para o serviço iqFleetSync. Os outros produtos da IQSoftCore não estão cobertos, salvo acordo separado.",
    sections: [
      ["1. Prestador", ["O prestador é o empresário individual finlandês iqsoftcore, que atua como IQSoftCore, Finlândia. Contato: info@iqsoftcore.fi e +358 45 133 4009."]],
      ["2. O serviço", ["O iqFleetSync é um serviço web de manutenção de frota em fleetsync.iqsoftcore.fi. Ele atende várias empresas: os dados de cada cliente ficam separados.", "O motorista lê um adesivo QR e abre uma página comum no celular. Não há nada para instalar. O acesso é na mesma aba, com um código de 6 dígitos enviado por e-mail. É possível informar quilômetros ou horas de motor e defeitos.", "A administração tem a lista da frota, o histórico de serviço e reparo, as trocas de peças, os lembretes de inspeção, a possibilidade de vincular um reboque a um caminhão e uma central de ajuda integrada."]],
      ["3. Teste", ["Um cliente novo pode testar o serviço grátis por 30 dias. Não é preciso cartão para começar. O teste pode ser encerrado a qualquer momento antes do fim, sem custo."]],
      ["4. Preços e cobrança", ["Os preços são IVA 0%. A tabela de preços faz parte destes termos.", "A taxa base é de 10,00 € por mês por empresa cliente. Veículos e máquinas são cobrados em faixas: as primeiras 15 unidades a 1,50 €, as unidades 16–50 a 1,30 €, as unidades 51–100 a 1,10 € e as unidades acima disso a 0,90 € cada.", "Um reboque é meia unidade, ou seja, 50% do preço de um veículo ou máquina na mesma faixa. Equipamento montado é gratuito. O número de usuários não é limitado.", "O preço do mês usa a maior quantidade de unidades daquele mês. O uso pago é cobrado todo mês."]],
      ["5. Somente leitura", ["Se o teste termina e não há pagamento, a conta fica somente leitura. Os dados salvos podem ser vistos, mas novos registros e alterações não podem ser salvos até o pagamento."]],
      ["6. Conservação dos dados", ["Os dados que o cliente gravou são mantidos depois do teste, no modo somente leitura e depois do cancelamento, para que ainda possam ser lidos.", "O cliente pode pedir a exclusão em info@iqsoftcore.fi. O prestador apaga ou anonimiza os dados quando o pedido é tratado, salvo se a lei ou a contabilidade exigir guarda mais longa."]],
      ["7. Cancelamento", ["O cliente pode cancelar o uso pago no serviço ou por e-mail para info@iqsoftcore.fi. O cancelamento vale no fim do período de cobrança já iniciado. Um mês já cobrado não é devolvido, salvo se uma lei obrigatória exigir. Encerrar o teste não custa nada. Depois a conta fica somente leitura e os dados são mantidos."]],
      ["8. Responsabilidade do cliente", ["O cliente responde pelos próprios usuários e por quem recebe acesso. Também responde por ter o direito de gravar quilômetros, horas de motor, defeitos e outros dados.", "O serviço é uma ferramenta de registro. Ele não substitui inspeção, manutenção nem a decisão de a frota estar segura para uso."]],
      ["9. Disponibilidade", ["O serviço é mantido disponível com esforço razoável. Manutenção, falha ou a rede podem causar uma interrupção. O serviço é oferecido como está."]],
      ["10. Limite de responsabilidade", ["Na medida em que a lei finlandesa obrigatória permitir, o prestador não responde por dano indireto, lucro cessante ou dados perdidos.", "A responsabilidade por dano direto fica limitada aos valores que o cliente pagou pelo iqFleetSync nos 12 meses anteriores ao dano. Se nada foi pago, esse teto é 0 €.", "O limite não vale para dano causado de propósito ou por negligência grave, nem para responsabilidade que a lei não permita limitar."]],
      ["11. Alterações", ["O prestador pode alterar estes termos e os preços. Uma alteração é avisada antes no serviço ou por e-mail. Se o cliente não aceitar, pode cancelar antes de ela valer. Continuar a usar o serviço significa aceitar os termos atualizados."]],
      ["12. Lei aplicável", ["Aplica-se a lei da Finlândia. Um desacordo é tratado primeiro entre as partes. Se isso não resolver, o caso cabe ao tribunal do domicílio do prestador na Finlândia."]],
      ["13. Contato", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Preços",
    product: "iqFleetSync",
    home: "Início",
  },
  it: {
    metaTitle: "Condizioni d’uso | IQSoftCore",
    metaDescription: "Condizioni d’uso del servizio iqFleetSync. Bozza.",
    title: "Condizioni d’uso",
    draft: "Bozza. Questo è una bozza in linguaggio semplice delle condizioni di iqFleetSync. Non è una consulenza legale. Il fornitore deve rivedere il testo prima della pubblicazione.",
    updated: "Bozza aggiornata il 2026-09-30.",
    scope: "Queste condizioni riguardano il servizio iqFleetSync. Gli altri prodotti di IQSoftCore non sono inclusi, salvo accordo separato.",
    sections: [
      ["1. Fornitore", ["Il fornitore è l’impresa individuale finlandese iqsoftcore, che opera come IQSoftCore, Finlandia. Contatto: info@iqsoftcore.fi e +358 45 133 4009."]],
      ["2. Il servizio", ["iqFleetSync è un servizio web per la manutenzione della flotta all’indirizzo fleetsync.iqsoftcore.fi. È multi-cliente: i dati di ogni azienda cliente restano separati.", "Il conducente legge un adesivo QR e apre una normale pagina web mobile. Non c’è nulla da installare. L’accesso avviene nella stessa scheda con un codice di 6 cifre inviato via e-mail. Si possono segnalare chilometri o ore motore e difetti.", "L’amministrazione comprende l’elenco della flotta, lo storico di assistenza e riparazione, le sostituzioni di parti, i promemoria di controllo, la possibilità di abbinare un rimorchio a un camion e un centro assistenza integrato."]],
      ["3. Prova", ["Un nuovo cliente può provare il servizio gratis per 30 giorni. Per iniziare non serve una carta. La prova si può interrompere in qualsiasi momento prima della fine, senza costi."]],
      ["4. Prezzi e fatturazione", ["I prezzi sono IVA 0%. Il listino fa parte di queste condizioni.", "La quota base è di 10,00 € al mese per azienda cliente. Veicoli e macchine si calcolano a scaglioni: le prime 15 unità a 1,50 €, le unità 16–50 a 1,30 €, le unità 51–100 a 1,10 € e le unità oltre 100 a 0,90 € ciascuna.", "Un rimorchio è mezza unità, cioè il 50% del prezzo di un veicolo o di una macchina nello stesso scaglione. L’attrezzatura montata è gratuita. Il numero di utenti non è limitato.", "Il prezzo del mese usa il numero di unità più alto di quel mese di calendario. L’uso a pagamento si fattura ogni mese."]],
      ["5. Sola lettura", ["Se la prova finisce e non c’è un pagamento, l’account diventa di sola lettura. I dati salvati si possono vedere, ma nuove segnalazioni e modifiche non si possono salvare finché non si paga."]],
      ["6. Conservazione dei dati", ["I dati che il cliente ha salvato restano dopo la prova, in sola lettura e dopo la disdetta, così si possono ancora leggere.", "Il cliente può chiederne la cancellazione a info@iqsoftcore.fi. Il fornitore li cancella o li anonimizza quando la richiesta è gestita, salvo che la legge o la contabilità impongano una conservazione più lunga."]],
      ["7. Disdetta", ["Il cliente può disdire l’uso a pagamento nel servizio o via e-mail a info@iqsoftcore.fi. La disdetta ha effetto alla fine del periodo di fatturazione già iniziato. Un mese già fatturato non viene rimborsato, salvo che una legge inderogabile lo imponga. Interrompere la prova non costa nulla. Dopo, l’account è di sola lettura e i dati restano conservati."]],
      ["8. Responsabilità del cliente", ["Il cliente risponde dei propri utenti e di chi riceve l’accesso. Risponde anche del diritto di salvare chilometri, ore motore, difetti e altri dati.", "Il servizio è uno strumento di registrazione. Non sostituisce un controllo, una manutenzione né la decisione se la flotta sia sicura da usare."]],
      ["9. Disponibilità", ["Il servizio è tenuto disponibile con uno sforzo ragionevole. Manutenzione, un guasto o la rete possono causare un’interruzione. Il servizio è fornito così com’è."]],
      ["10. Limite di responsabilità", ["Nella misura in cui la legge finlandese inderogabile lo consente, il fornitore non risponde di danni indiretti, mancato guadagno o dati persi.", "La responsabilità per danno diretto è limitata alle somme che il cliente ha pagato per iqFleetSync nei 12 mesi precedenti il danno. Se non è stato pagato nulla, quel tetto è 0 €.", "Il limite non vale per un danno causato con dolo o colpa grave, né per una responsabilità che la legge non consente di limitare."]],
      ["11. Modifiche", ["Il fornitore può modificare queste condizioni e i prezzi. Una modifica è comunicata in anticipo nel servizio o via e-mail. Se il cliente non l’accetta, può disdire prima che entri in vigore. Continuare a usare il servizio significa accettare le condizioni aggiornate."]],
      ["12. Legge applicabile", ["Si applica la legge della Finlandia. Un disaccordo si cerca prima di risolverlo insieme. Se non si riesce, è competente il tribunale del domicilio del fornitore in Finlandia."]],
      ["13. Contatto", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Prezzi",
    product: "iqFleetSync",
    home: "Home",
  },
  pl: {
    metaTitle: "Regulamin | IQSoftCore",
    metaDescription: "Regulamin usługi iqFleetSync. Projekt.",
    title: "Regulamin",
    draft: "Projekt. To projekt regulaminu iqFleetSync prostym językiem. Nie jest poradą prawną. Usługodawca musi sprawdzić tekst przed publikacją.",
    updated: "Projekt zaktualizowany 2026-09-30.",
    scope: "Regulamin dotyczy usługi iqFleetSync. Inne produkty IQSoftCore nie są nim objęte, chyba że uzgodniono to osobno.",
    sections: [
      ["1. Usługodawca", ["Usługodawcą jest fińska działalność jednoosobowa iqsoftcore, działająca jako IQSoftCore, Finlandia. Kontakt: info@iqsoftcore.fi i +358 45 133 4009."]],
      ["2. Usługa", ["iqFleetSync to usługa internetowa do utrzymania floty pod adresem fleetsync.iqsoftcore.fi. Obsługuje wielu klientów: dane każdej firmy są osobno.", "Kierowca skanuje naklejkę QR i otwiera zwykłą stronę w telefonie. Nic nie trzeba instalować. Logowanie odbywa się w tej samej karcie 6-cyfrowym kodem z e-maila. Można zgłosić kilometry lub motogodziny oraz usterki.", "Administracja ma listę floty, historię serwisu i napraw, wymiany części, przypomnienia o przeglądach, możliwość powiązania przyczepy z ciężarówką oraz wbudowane centrum pomocy."]],
      ["3. Okres próbny", ["Nowy klient może korzystać z usługi bezpłatnie przez 30 dni. Do rozpoczęcia nie potrzeba karty. Okres próbny można przerwać w dowolnej chwili przed końcem, bez opłaty."]],
      ["4. Ceny i rozliczenie", ["Ceny są VAT 0%. Cennik jest częścią regulaminu.", "Opłata podstawowa to 10,00 € miesięcznie za firmę klienta. Pojazdy i maszyny liczone są progami: pierwsze 15 jednostek 1,50 €, jednostki 16–50 1,30 €, jednostki 51–100 1,10 €, a powyżej 100 po 0,90 €.", "Przyczepa to pół jednostki, czyli 50% ceny pojazdu lub maszyny w tym samym progu. Zamontowane wyposażenie jest bezpłatne. Liczba użytkowników nie jest ograniczona.", "Cena miesiąca używa największej liczby jednostek w tym miesiącu kalendarzowym. Płatne użycie jest rozliczane co miesiąc."]],
      ["5. Tylko odczyt", ["Jeśli okres próbny kończy się bez płatności, konto przechodzi w tryb tylko do odczytu. Zapisane dane można oglądać, ale nowych zgłoszeń i zmian nie można zapisać, dopóki nie zostanie dokonana płatność."]],
      ["6. Przechowywanie danych", ["Dane zapisane przez klienta są przechowywane po okresie próbnym, w trybie tylko do odczytu i po rezygnacji, aby nadal można je było czytać.", "Klient może poprosić o usunięcie na info@iqsoftcore.fi. Usługodawca usuwa lub anonimizuje dane po obsłużeniu prośby, chyba że prawo lub księgowość wymaga dłuższego przechowywania."]],
      ["7. Rezygnacja", ["Klient może zrezygnować z płatnego użycia w usłudze lub e-mailem na info@iqsoftcore.fi. Rezygnacja działa od końca już rozpoczętego okresu rozliczeniowego. Opłaconego miesiąca nie zwraca się, chyba że bezwzględne prawo tego wymaga. Przerwanie okresu próbnego nic nie kosztuje. Potem konto jest tylko do odczytu, a dane pozostają."]],
      ["8. Odpowiedzialność klienta", ["Klient odpowiada za swoich użytkowników i za to, komu daje dostęp. Odpowiada też za prawo do zapisania kilometrów, motogodzin, usterek i innych danych.", "Usługa jest narzędziem do zapisów. Nie zastępuje przeglądu, utrzymania ani decyzji, czy flota jest bezpieczna w użyciu."]],
      ["9. Dostępność", ["Usługa jest utrzymywana dostępną w rozsądnym zakresie. Konserwacja, awaria lub sieć mogą spowodować przerwę. Usługa jest świadczona taka, jaka jest."]],
      ["10. Ograniczenie odpowiedzialności", ["W zakresie, w jakim pozwala na to bezwzględne prawo fińskie, usługodawca nie odpowiada za szkodę pośrednią, utracony zysk ani utracone dane.", "Odpowiedzialność za szkodę bezpośrednią jest ograniczona do opłat, które klient zapłacił za iqFleetSync w ciągu 12 miesięcy przed szkodą. Jeśli nic nie zapłacono, limit wynosi 0 €.", "Ograniczenie nie dotyczy szkody wyrządzonej umyślnie lub przez rażące niedbalstwo ani odpowiedzialności, której prawo nie pozwala ograniczyć."]],
      ["11. Zmiany", ["Usługodawca może zmienić regulamin i ceny. O zmianie informuje wcześniej w usłudze lub e-mailem. Jeśli klient jej nie przyjmuje, może zrezygnować, zanim wejdzie w życie. Dalsze korzystanie oznacza przyjęcie zaktualizowanego regulaminu."]],
      ["12. Prawo", ["Stosuje się prawo Finlandii. Spór najpierw próbuje się rozwiązać wspólnie. Jeśli się nie uda, sprawę rozpoznaje sąd miejsca siedziby usługodawcy w Finlandii."]],
      ["13. Kontakt", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Cennik",
    product: "iqFleetSync",
    home: "Strona główna",
  },
  cs: {
    metaTitle: "Podmínky použití | IQSoftCore",
    metaDescription: "Podmínky použití služby iqFleetSync. Návrh.",
    title: "Podmínky použití",
    draft: "Návrh. Toto je návrh podmínek iqFleetSync jednoduchým jazykem. Není to právní rada. Poskytovatel musí text zkontrolovat před zveřejněním.",
    updated: "Návrh aktualizován 2026-09-30.",
    scope: "Tyto podmínky platí pro službu iqFleetSync. Ostatní produkty IQSoftCore jimi nejsou pokryty, pokud to není dohodnuto zvlášť.",
    sections: [
      ["1. Poskytovatel", ["Poskytovatelem je finská živnost iqsoftcore, která vystupuje jako IQSoftCore, Finsko. Kontakt: info@iqsoftcore.fi a +358 45 133 4009."]],
      ["2. Služba", ["iqFleetSync je webová služba pro údržbu flotily na adrese fleetsync.iqsoftcore.fi. Slouží více zákazníkům: data každé firmy jsou oddělená.", "Řidič načte QR štítek a otevře obyčejnou mobilní stránku. Nic se neinstaluje. Přihlášení proběhne ve stejné kartě 6místným kódem z e-mailu. Lze zapsat kilometry nebo motohodiny a závady.", "Správa má seznam flotily, historii servisu a oprav, výměny dílů, připomínky kontrol, možnost spárovat přívěs s nákladním autem a vestavěné centrum nápovědy."]],
      ["3. Zkouška", ["Nový zákazník může službu zkoušet 30 dní zdarma. K začátku není potřeba karta. Zkoušku lze kdykoli před koncem ukončit bez poplatku."]],
      ["4. Ceny a účtování", ["Ceny jsou DPH 0 %. Ceník je součástí těchto podmínek.", "Základní poplatek je 10,00 € měsíčně za zákaznickou firmu. Vozidla a stroje se účtují po pásmech: prvních 15 jednotek 1,50 €, jednotky 16–50 za 1,30 €, jednotky 51–100 za 1,10 € a jednotky nad 100 za 0,90 €.", "Přívěs je půl jednotky, tedy 50 % ceny vozidla nebo stroje ve stejném pásmu. Namontované zařízení je zdarma. Počet uživatelů není omezen.", "Měsíční cena používá nejvyšší počet jednotek v daném kalendářním měsíci. Placené užívání se účtuje každý měsíc."]],
      ["5. Jen pro čtení", ["Pokud zkouška skončí a není zaplaceno, účet přejde do režimu jen pro čtení. Uložená data lze prohlížet, ale nová hlášení a změny nelze uložit, dokud není zaplaceno."]],
      ["6. Uchování dat", ["Data, která zákazník uložil, se uchovávají po zkoušce, v režimu jen pro čtení i po zrušení, aby je bylo možné dál číst.", "Zákazník může požádat o výmaz na info@iqsoftcore.fi. Poskytovatel data smaže nebo anonymizuje, jakmile je žádost vyřízena, pokud zákon nebo účetnictví nevyžadují delší uchování."]],
      ["7. Zrušení", ["Zákazník může placené užívání zrušit ve službě nebo e-mailem na info@iqsoftcore.fi. Zrušení platí od konce již zahájeného zúčtovacího období. Již vyúčtovaný měsíc se nevrací, pokud to kogentní zákon nevyžaduje. Ukončení zkoušky nic nestojí. Potom je účet jen pro čtení a data zůstávají."]],
      ["8. Odpovědnost zákazníka", ["Zákazník odpovídá za své uživatele a za to, komu dá přístup. Odpovídá také za to, že kilometry, motohodiny, závady a další data smí uložit.", "Služba je nástroj pro zápis. Nenahrazuje kontrolu, údržbu ani rozhodnutí, zda je flotila bezpečná k použití."]],
      ["9. Dostupnost", ["Služba je udržována dostupná s přiměřeným úsilím. Údržba, závada nebo síť mohou způsobit výpadek. Služba se poskytuje tak, jak je."]],
      ["10. Omezení odpovědnosti", ["V rozsahu, který dovoluje kogentní finské právo, poskytovatel neodpovídá za nepřímou škodu, ušlý zisk ani ztracená data.", "Odpovědnost za přímou škodu je omezena na poplatky, které zákazník zaplatil za iqFleetSync za 12 měsíců před škodou. Pokud nic zaplaceno nebylo, je strop 0 €.", "Omezení se netýká škody způsobené úmyslně nebo hrubou nedbalostí ani odpovědnosti, kterou zákon nedovoluje omezit."]],
      ["11. Změny", ["Poskytovatel může tyto podmínky a ceny změnit. Změna se oznámí předem ve službě nebo e-mailem. Pokud ji zákazník nepřijme, může užívání zrušit, než začne platit. Další užívání znamená, že přijímá aktualizované podmínky."]],
      ["12. Rozhodné právo", ["Použije se právo Finska. Neshoda se nejdřív řeší společně. Pokud se to nepodaří, věc projedná soud v sídle poskytovatele ve Finsku."]],
      ["13. Kontakt", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "Ceník",
    product: "iqFleetSync",
    home: "Úvod",
  },
  ja: {
    metaTitle: "利用規約 | IQSoftCore",
    metaDescription: "iqFleetSyncの利用規約。草案です。",
    title: "利用規約",
    draft: "草案です。これは iqFleetSync の利用規約を平易な言葉で書いた草案であり、法的助言ではありません。公開前に提供者が本文を確認する必要があります。",
    updated: "草案の更新日 2026-09-30。",
    scope: "この規約は iqFleetSync に適用されます。IQSoftCore の他の製品は、別途合意しない限り対象外です。",
    sections: [
      ["1. 提供者", ["提供者は、IQSoftCore の名称で事業を行うフィンランドの個人事業 iqsoftcore です。連絡先は info@iqsoftcore.fi および +358 45 133 4009 です。"]],
      ["2. サービス", ["iqFleetSync は fleetsync.iqsoftcore.fi にある、車両・機械の整備向けウェブサービスです。複数の会社が利用し、各顧客の情報は分けて保管されます。", "運転者は QR シールを読み取り、普通のモバイルページを開きます。インストールは不要です。同じタブで、メールの6桁コードによりログインし、走行距離または稼働時間と不具合を報告します。", "管理側には一覧、整備と修理の履歴、部品交換、点検の通知、トレーラーとトラックの紐づけ、組み込みのヘルプセンターがあります。"]],
      ["3. 試用", ["新しい顧客は 30 日間無料で試せます。開始時にカードは不要です。終了前であればいつでも止められ、料金は発生しません。"]],
      ["4. 料金と請求", ["価格は消費税 0% です。料金ページは本規約の一部です。", "基本料金は顧客企業あたり月 10.00 € です。車両と機械は段階制です。最初の 15 単位は 1.50 €、16–50 は 1.30 €、51–100 は 1.10 €、それを超える単位は 1 単位 0.90 € です。", "トレーラーは 0.5 単位で、同じ段階の車両または機械の価格の 50% です。装着した機器は無料です。ユーザー数に制限はなく、別料金はありません。", "月額は、その暦月の最大単位数で計算します。有料利用は月ごとに請求します。"]],
      ["5. 閲覧のみ", ["試用が終わり、支払いがない場合、アカウントは閲覧のみになります。保存済みの情報は見られますが、支払いが済むまで新しい報告や変更は保存できません。"]],
      ["6. データの保管", ["顧客が保存したデータは、試用後、閲覧のみの間、解約後も、読めるように保管します。", "削除は info@iqsoftcore.fi に依頼できます。提供者は依頼を処理したあとデータを削除または匿名化します。ただし法令または会計上、より長く保管する必要がある場合を除きます。"]],
      ["7. 解約", ["有料利用はサービス内、または info@iqsoftcore.fi へのメールで解約できます。解約は、すでに始まった請求期間の終わりに効力を生じます。すでに請求した月は、強行法規が求める場合を除き返金しません。試用の中止に料金はありません。解約後は閲覧のみとなり、データは上記のとおり保管します。"]],
      ["8. 顧客の責任", ["顧客は自分のユーザーと、誰にアクセスを与えるかに責任を負います。走行距離、稼働時間、不具合、その他のデータを保存する権利があることにも責任を負います。", "サービスは記録のための道具です。機械や車両の点検、整備、安全に使えるかどうかの判断に代わるものではありません。"]],
      ["9. 可用性", ["サービスは合理的な努力で利用できる状態を保ちます。保守、障害、通信により中断することがあります。サービスはその時の状態で提供されます。"]],
      ["10. 責任の上限", ["フィンランドの強行法規が許す範囲で、提供者は間接損害、得られなかった利益、失われたデータについて責任を負いません。", "直接損害の責任は、損害の前 12 か月に顧客が iqFleetSync に支払った料金を上限とします。支払いがなければ上限は 0 € です。", "故意または重大な過失による損害、および法律上制限できない責任には、この上限は適用しません。"]],
      ["11. 変更", ["提供者は本規約と料金を変更できます。変更は事前にサービス内またはメールで知らせます。顧客が変更を受け入れない場合は、効力発生前に解約できます。変更後も利用を続けることは、更新後の規約への同意を意味します。"]],
      ["12. 準拠法", ["フィンランド法を適用します。争いはまず当事者間で解決を試みます。解決できない場合は、フィンランドにある提供者の住所地の地方裁判所が扱います。"]],
      ["13. 連絡先", ["IQSoftCore、info@iqsoftcore.fi、+358 45 133 4009。"]],
    ],
    pricing: "料金",
    product: "iqFleetSync",
    home: "ホーム",
  },
  ko: {
    metaTitle: "이용약관 | IQSoftCore",
    metaDescription: "iqFleetSync 서비스 이용약관. 초안입니다.",
    title: "이용약관",
    draft: "초안입니다. 이것은 iqFleetSync 약관을 쉬운 말로 쓴 초안이며 법률 자문이 아닙니다. 공개 전에 제공자가 글을 검토해야 합니다.",
    updated: "초안 업데이트 2026-09-30.",
    scope: "이 약관은 iqFleetSync에 적용됩니다. 별도로 정하지 않으면 IQSoftCore의 다른 제품에는 적용되지 않습니다.",
    sections: [
      ["1. 제공자", ["제공자는 IQSoftCore라는 이름으로 영업하는 핀란드 개인사업자 iqsoftcore입니다. 연락처는 info@iqsoftcore.fi 및 +358 45 133 4009입니다."]],
      ["2. 서비스", ["iqFleetSync는 fleetsync.iqsoftcore.fi의 차량·장비 정비 웹 서비스입니다. 여러 회사가 쓰며, 각 고객의 정보는 분리됩니다.", "운전자는 QR 스티커를 읽고 일반 모바일 페이지를 엽니다. 설치는 없습니다. 같은 탭에서 이메일 6자리 코드로 로그인한 뒤 주행거리 또는 가동시간과 고장을 보고합니다.", "관리 쪽에는 목록, 정비·수리 이력, 부품 교체, 점검 알림, 트레일러와 트럭의 연결, 내장 도움말 센터가 있습니다."]],
      ["3. 체험", ["새 고객은 30일 동안 무료로 써 볼 수 있습니다. 시작할 때 카드는 필요 없습니다. 끝나기 전이면 언제든 멈출 수 있고, 비용은 없습니다."]],
      ["4. 요금과 청구", ["가격은 부가세 0%입니다. 요금 페이지는 이 약관의 일부입니다.", "기본요금은 고객 회사당 월 10.00 €입니다. 차량과 기계는 구간제로 계산합니다. 처음 15단위는 1.50 €, 16–50은 1.30 €, 51–100은 1.10 €, 그 위는 단위당 0.90 €입니다.", "트레일러는 0.5단위이며 같은 구간 차량 또는 기계 가격의 50%입니다. 장착 장비는 무료입니다. 사용자 수에는 제한이 없고 별도 요금도 없습니다.", "월 요금은 그 달의 최대 단위 수를 기준으로 합니다. 유료 사용은 매월 청구합니다."]],
      ["5. 읽기 전용", ["체험이 끝나고 결제가 없으면 계정은 읽기 전용이 됩니다. 저장된 정보는 볼 수 있지만, 결제 전까지 새 보고와 변경은 저장할 수 없습니다."]],
      ["6. 데이터 보관", ["고객이 저장한 데이터는 체험 후, 읽기 전용 상태, 해지 후에도 읽을 수 있도록 보관합니다.", "삭제는 info@iqsoftcore.fi로 요청할 수 있습니다. 제공자는 요청을 처리한 뒤 데이터를 삭제하거나 익명화합니다. 다만 법이나 회계가 더 긴 보관을 요구하면 그렇지 않습니다."]],
      ["7. 해지", ["유료 사용은 서비스에서, 또는 info@iqsoftcore.fi 이메일로 해지할 수 있습니다. 해지는 이미 시작된 청구 기간의 끝에 효력이 있습니다. 이미 청구된 달은 강행 법규가 요구하지 않으면 환불하지 않습니다. 체험을 멈추는 데는 비용이 없습니다. 이후 계정은 읽기 전용이고 데이터는 위와 같이 보관합니다."]],
      ["8. 고객의 책임", ["고객은 자신의 사용자와 누구에게 접근을 주는지에 책임이 있습니다. 주행거리, 가동시간, 고장, 그 밖의 데이터를 저장할 권리가 있는지도 고객의 책임입니다.", "서비스는 기록을 위한 도구입니다. 기계나 차량의 점검, 정비, 안전하게 쓸 수 있는지에 대한 판단을 대신하지 않습니다."]],
      ["9. 가용성", ["서비스는 합리적인 노력으로 사용할 수 있게 유지합니다. 유지보수, 장애, 통신 때문에 중단될 수 있습니다. 서비스는 그 상태 그대로 제공됩니다."]],
      ["10. 책임의 한계", ["핀란드 강행 법규가 허용하는 범위에서 제공자는 간접 손해, 얻지 못한 이익, 잃은 데이터에 대해 책임지지 않습니다.", "직접 손해에 대한 책임은 손해 전 12개월 동안 고객이 iqFleetSync에 낸 요금을 한도로 합니다. 낸 요금이 없으면 한도는 0 €입니다.", "이 한도는 고의 또는 중대한 과실로 인한 손해와, 법으로 제한할 수 없는 책임에는 적용하지 않습니다."]],
      ["11. 변경", ["제공자는 이 약관과 요금을 바꿀 수 있습니다. 변경은 미리 서비스 또는 이메일로 알립니다. 고객이 받아들이지 않으면 효력 전에 해지할 수 있습니다. 변경 뒤에도 계속 쓰면 바뀐 약관에 동의한 것입니다."]],
      ["12. 준거법", ["핀란드 법을 적용합니다. 다툼은 먼저 당사자 사이에서 해결합니다. 해결되지 않으면 핀란드에 있는 제공자 주소지의 법원이 다룹니다."]],
      ["13. 연락처", ["IQSoftCore, info@iqsoftcore.fi, +358 45 133 4009."]],
    ],
    pricing: "요금",
    product: "iqFleetSync",
    home: "홈",
  },
  zh: {
    metaTitle: "使用条款 | IQSoftCore",
    metaDescription: "iqFleetSync 服务的使用条款。草案。",
    title: "使用条款",
    draft: "草案。这是用平白语言写的 iqFleetSync 条款草案，不是法律意见。提供者必须在发布前审阅本文。",
    updated: "草案更新日期 2026-09-30。",
    scope: "本条款适用于 iqFleetSync。除非另行约定，不适用于 IQSoftCore 的其他产品。",
    sections: [
      ["1. 提供者", ["提供者是以 IQSoftCore 名义经营的芬兰个体工商户 iqsoftcore，位于芬兰。联系方式：info@iqsoftcore.fi 和 +358 45 133 4009。"]],
      ["2. 服务", ["iqFleetSync 是位于 fleetsync.iqsoftcore.fi 的车队维护网页服务。它供多家公司使用，每家客户的数据彼此分开。", "驾驶员扫描二维码贴并打开一个普通的手机网页。无需安装。在同一标签页用电子邮件收到的 6 位数字登录，然后填报公里数或发动机小时以及缺陷。", "管理端包括车队列表、保养与维修记录、零件更换、检验提醒、把挂车配对到卡车，以及内置帮助中心。"]],
      ["3. 试用", ["新客户可以免费试用 30 天。开始时不需要银行卡。试用结束前可以随时停止，不会产生费用。"]],
      ["4. 价格与账单", ["价格为增值税 0%。价格页是本条款的一部分。", "基础费为每家客户公司每月 10.00 €。车辆和机器按档计费：前 15 个单位 1.50 €，第 16–50 个 1.30 €，第 51–100 个 1.10 €，超过 100 的每个单位 0.90 €。", "挂车计为半个单位，即同一档中车辆或机器价格的 50%。安装的设备免费。用户数量不限，也不另收费。", "月费按该自然月的最高单位数计算。付费使用按月结算。"]],
      ["5. 只读", ["如果试用结束且没有付款，账户变为只读。已保存的数据仍可查看，但在付款之前不能保存新的填报和修改。"]],
      ["6. 数据保留", ["客户保存在服务中的数据，在试用之后、只读期间以及取消之后仍然保留，以便继续阅读。", "客户可以发邮件到 info@iqsoftcore.fi 要求删除。提供者在处理请求后删除或匿名化数据，除非法律或会计要求保留更久。"]],
      ["7. 取消", ["客户可以在服务中，或发邮件到 info@iqsoftcore.fi 取消付费使用。取消在已经开始的计费周期结束时生效。已经计费的月份不予退还，除非强制性法律要求退还。停止试用不产生费用。之后账户为只读，数据按上文保留。"]],
      ["8. 客户的责任", ["客户对自己的用户以及把访问权给谁负责。客户也负责自己有权保存所填写的公里数、发动机小时、缺陷和其他数据。", "本服务是记录工具。它不代替对机器或车辆的检验、维护，也不代替关于设备能否安全使用的决定。"]],
      ["9. 可用性", ["提供者会以合理努力保持服务可用。维护、故障或网络可能导致中断。服务按当时的状态提供。"]],
      ["10. 责任限制", ["在芬兰强制性法律允许的范围内，提供者不对间接损失、未获得的利润或丢失的数据负责。", "对直接损失的责任，以客户在损失发生前 12 个月内为 iqFleetSync 支付的费用为上限。如果没有支付过费用，该上限为 0 €。", "该限制不适用于故意或重大过失造成的损失，也不适用于法律不允许限制的责任。"]],
      ["11. 变更", ["提供者可以修改本条款和价格。变更会事先在服务中或通过电子邮件说明。如果客户不接受，可以在变更生效前取消。变更后继续使用，即表示客户接受更新后的条款。"]],
      ["12. 适用法律", ["适用芬兰法律。争议首先由双方协商。协商不成的，由提供者在芬兰住所地的地区法院审理。"]],
      ["13. 联系方式", ["IQSoftCore，info@iqsoftcore.fi，+358 45 133 4009。"]],
    ],
    pricing: "价格",
    product: "iqFleetSync",
    home: "首页",
  },
};

function escapeTermsHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderTermsPage(lang) {
  const root = document.getElementById("terms-root");
  if (!root || typeof TERMS_PAGE === "undefined") return;
  const page = TERMS_PAGE[lang] || TERMS_PAGE.en;

  const titleEl = document.querySelector("title");
  if (titleEl) titleEl.textContent = page.metaTitle;
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc) metaDesc.setAttribute("content", page.metaDescription);

  const sections = page.sections
    .map(([heading, paragraphs]) => {
      const body = paragraphs.map((paragraph) => `<p>${escapeTermsHtml(paragraph)}</p>`).join("");
      return `<section class="policy-section"><h2>${escapeTermsHtml(heading)}</h2>${body}</section>`;
    })
    .join("");

  root.innerHTML = `<h1>${escapeTermsHtml(page.title)}</h1>
    <p class="note">${escapeTermsHtml(page.draft)}</p>
    <p class="policy-updated">${escapeTermsHtml(page.updated)}</p>
    <p>${escapeTermsHtml(page.scope)}</p>
    ${sections}
    <p class="policy-nav">
      <a class="btn btn-ghost" href="hinnasto.html">${escapeTermsHtml(page.pricing)}</a>
      <a class="btn btn-ghost" href="iqfleetsync.html">${escapeTermsHtml(page.product)}</a>
      <a class="btn btn-ghost" href="index.html">${escapeTermsHtml(page.home)}</a>
    </p>`;
}
